- tests/helpers.js
Nest mocha hooks within describe
> Fix custom describe

- .travis.yml
- src/index.js
- webpack.config.js
Also adds AppContainer wrapper from react-hot-loader which does
nothing in production
> In production remove webpack hot reload config

- package.json
- platform/package.json
- platform/yarn.lock
- yarn.lock
We need to make changes to core stripes libraries from time to time, and we don't necessarily want to have to wait on them to get merged. The branch `eholdings-demo-support` on a given library will contain whatever set of independent patches are necessary to make the eholdings demo platform and test cases work.
This allows the individual enhancements to not be dependent on each other and submitted and considered as separate PRS. There is currently only one such enhancement, but there could be many.
As PRS make it to master, they should be removed from this branch.
> Use custom fork of stripes-core.

- mirage/config.js
- mirage/factories/package.js
- mirage/factories/vendor.js
- mirage/models/package.js
- mirage/scenarios/default.js
- mirage/serializers/application.js
- src/components/app.js
- src/components/vendor-details.js
- src/components/vendor-show.js
- src/index.js
- src/routes/vendor/vendor-show.js
- tests/app-test.js
- tests/helpers.js
- tests/pages/vendor-details.js
- tests/vendor-details-test.js
> Create vendor details page

- src/components/vendor-show/vendor-show.js
> Link Vendor Details package list items to Package Details

- mirage/config.js
- mirage/factories/customer-resource.js
- src/components/customer-resource-show/customer-resource-show.js
- src/components/customer-resource-show/index.js
- src/components/package-show/package-show.js
- src/index.js
- src/routes/customer-resource/customer-resource-show.js
- tests/customer-resource-show-test.js
- tests/pages/customer-resource-show.js
Titles in the list link to a package title details page.
> Create package title details page

- mirage/config.js
- mirage/factories/customer-resource.js
- mirage/factories/package.js
- mirage/factories/title.js
- src/components/customer-resource-show.js
- src/components/title-show/index.js
- src/components/title-show/title-show.css
- src/components/title-show/title-show.js
- src/index.js
- src/routes/title/title-show.js
- tests/pages/title-show.js
- tests/title-show-test.js
Added "View other packages that include this title" link back to title detail view.
> Create title detail view

- demo/front.js
Now has links to real data from RM API and notes on the current state of the demo application.
> Update demo front page

- mirage/factories/customer-resource.js
- mirage/factories/subject.js
- mirage/factories/title.js
- mirage/models/subject.js
- mirage/models/title.js
- mirage/serializers/application.js
- mirage/serializers/customer-resource.js
- mirage/serializers/title.js
- src/components/customer-resource-show.js
- src/components/title-show/title-show.js
- tests/customer-resource-show-test.js
- tests/pages/customer-resource-show.js
- tests/pages/title-show.js
- tests/title-show-test.js
> Show subject list for titles and package-titles

- src/components/customer-resource-show.js
- src/components/title-show/title-show.js
- tests/customer-resource-show-test.js
- tests/pages/customer-resource-show.js
- tests/pages/title-show.js
- tests/title-show-test.js
`pubType` actually means "Publication Type", not "Publisher Type"
> Correct publisher type to publication type

- mirage/factories/customer-resource.js
- mirage/models/customer-resource.js
- mirage/serializers/customer-resource.js
- src/components/customer-resource-show.js
- tests/customer-resource-show-visibility-test.js
- tests/pages/customer-resource-show.js
> Show isHidden state for customer resources

- mirage/factories/contributor.js
- mirage/factories/customer-resource.js
- mirage/factories/title.js
- mirage/models/contributor.js
- mirage/models/title.js
- mirage/serializers/application.js
- mirage/serializers/title.js
- src/components/contributors-list.js
- src/components/customer-resource-show.js
- src/components/title-show.js
- tests/pages/title-show.js
- tests/title-show-test.js
If available, author(s), illustrator(s), and editor(s) will show on title and package-title details:
> Show contributors for titles

- src/components/package-list-item.js
- src/redux/customer-resource.js
- src/routes/search.js
Fixes the title search route by correcting the capitalization of `searchfield`.
Fixes the customer-resource route by providing a default `method` of `"GET"` to `fetch`.
Fixes unicode characters rendering incorrectly by using their HTML equivalents.
> Fix production issues

- src/components/customer-resource-show.js
- src/components/package-show.js
- src/components/title-show.js
- src/components/vendor-show.js
- src/index.js
- src/redux/customer-resource.js
- src/redux/index.js
- src/redux/package.js
- src/redux/request.js
- src/redux/search.js
- src/redux/title.js
- src/redux/vendor.js
- src/routes/customer-resource/customer-resource-show.js
- src/routes/package/package-search-results.js
- src/routes/package/package-show.js
- src/routes/search.js
- src/routes/title/title-search-results.js
- src/routes/title/title-show.js
- src/routes/vendor/vendor-search-results.js
- src/routes/vendor/vendor-show.js
- tests/customer-resource-show-test.js
- tests/package-search-test.js
- tests/package-show-test.js
- tests/title-search-test.js
- tests/title-show-test.js
- tests/vendor-search-test.js
- tests/vendor-show-test.js
After removing stripes connect and using a reducer/epic combo from one of the routes, it became evident that most of our redux code will be centered around making and handling requests.
All pieces of our state had a similar structure to each other:
```js
{
isPending: false,
isResolved: false,
isRejected: false,
content: null,
error: null
}
```
And all of the epics also had a similar structure to each other:
```js
function epic(action$, { getState }) {
return action$.ofType(SOME_REQUEST_TYPE)
.switchMap((action) => {
let { okapi } = getState();
let url = buildOkapiEndpoint(okapi, action);
let headers = { 'X-Okapi-Tenant': okapi.tenant };
let request = fetch(url, { headers, /* ... */ });
return Observable.from(request.then((res) => res.json())
.map((payload) => ({ type: RESOLVE_REQUEST, …
```
> Remove stripes connect

- .travis.yml
- yarn.lock
> Upgrade stripes-core to get .babelrc detangling

- demo/stripes.config.js
- demo/stripes.js
- karma.conf.js
- mirage/config.js
- tests/harness.js
- yarn.lock
Will fix the builds on master.
UPDATE: Front component appropriately still loads too.
> Switch to stripes-config webpack plugin

- src/components/customer-resource-show.js
- src/components/package-show.js
- src/components/title-show.js
- src/components/vendor-show.js
- src/routes/package/package-search-results.js
- src/routes/title/title-search-results.js
- src/routes/vendor/vendor-search-results.js
Will need further styling, but it's a little bit better than the "Loading..." text we've been using.
> Use stripes-components activity indicator icon

- src/components/package-show.js
- src/components/vendor-show.js
Looks like a couple were missed in #80
> Change remaining loading indicators

- .eslintrc.js
- package.json
- yarn.lock
> Upgrade eslint-config-stripes to 1.0.0

- demo/stripes.js
- yarn.lock
Brings our stripes-core fork up to the same point as upstream/master.
> Upgrade to latest stripes-core master

- src/redux/package.js
- src/redux/vendor.js
Changes due to updates to rmapi orderby filter settings
> Updates due to rmapi changes to orderby filter

- yarn.lock
Upgrades `stripes-core` to pull latest changes from master
> Upgrade stripes-core

- mirage/config.js
- mirage/scenarios/unconfigured-backend.js
- src/components/settings/settings.js
- src/redux/application.js
- src/routes/application.js
CamelCases keys so that we don't have to do any special handling of said keys from the back end.
Needed in conjunction with https://github.com/thefrontside/mod-kb-ebsco/pull/18
> Use camelCase keys from mod-kb-ebsco

- demo/stripes.js
- yarn.lock
Updates to `stripes-core` streamlining done here: https://github.com/folio-org/stripes-core/pull/85
> Switch to simpler stripes setup with webpackOverrides

- src/components/package-list-item.js
- src/components/package-search-results.js
- src/components/title-list-item.js
- src/components/title-search-results.js
- src/components/vendor-list-item.js
- tests/package-search-test.js
- tests/pages/package-search.js
- tests/pages/title-search.js
- tests/pages/vendor-search.js
- tests/pages/vendor-show.js
- tests/title-search-test.js
- tests/vendor-search-test.js
- tests/vendor-show-test.js
Adds more info to search results listings.
Package counts
Vendor name
Publisher name
Publication type
Related to https://issues.folio.org/browse/UIEH-2
> Add additional info to search results

- src/components/customer-resource-show/customer-resource-show.js
- src/components/title-show/title-show.js
- src/components/utilities.js
- tests/customer-resource-show-embargo-test.js
- tests/customer-resource-show-test.js
- tests/customer-resource-show-visibility-test.js
- tests/pages/customer-resource-show.js
Minor updates related to title package display and tests
- added check of null embargo value and associated tests
- updated order of fields on title display to be consistent with title package
- added tests for contributors and identifiers  on title package display
- added update for title package hidden messaging (Set by System) 
related Jira tickets
https://issues.folio.org/browse/UIEH-44
https://issues.folio.org/browse/UIEH-36
Per rmapi docs on embargo period https://developer.ebsco.com/rmapireference#embargoperiod and check for null embargo value
> Added tests/cleanup for title package display

- .travis.yml
Switches from sandbox cluster to production cluster.
> Fix Okapi destination on production

- src/components/preview-pane/preview-pane.css
- src/components/search-pane-vignette/search-pane-vignette.css
- src/components/search-pane/search-pane.css
- src/components/search-paneset/search-paneset.css
- src/components/settings/settings.css
Instead of defining our own breakpoints, we should stick to the ones defined in `stripes-components`.
> Only use breakpoints defined in stripes-components

- Jenkinsfile
> Add FOLIO Jenkins Jenkinsfile

- demo/front.css
- src/components/key-value-label/key-value-label.css
- src/components/list/list.css
- src/components/modal/modal.css
- src/components/package-list-item/package-list-item.css
- src/components/package-search-list.js
- src/components/search-form/search-form.css
- src/components/title-list-item/title-list-item.css
- src/components/title-search-list.js
- src/components/vendor-list-item/vendor-list-item.css
- src/components/vendor-search-list.js
Subtle changes to scroll item heights and line-heights within them make for more polish.
Closes https://issues.folio.org/browse/UIEH-110
> Fix infinite scroll line-heights and spacing

- yarn.lock
Regular update of the Frontside forks of `stripes-core` and `stripes-components` to match upstream.
- Better auth form behavior when errors occur
- Lots of form element style tweaks
- Datepicker display bug fix
> Upgrade stripes-core and stripes-components

- demo/front.js
Now that we have pagination, the content in the front page was a little stale.
> Update front page content

- src/components/customer-resource-show.js
- src/components/package-show.js
- yarn.lock
Brings in new button styles and ids for datepicker elements.
> Upgrade stripes-components

- mirage/config.js
- package.json
- src/components/search-form/search-form.css
- src/components/search-form/search-form.js
- src/components/title-search-filters.js
- src/components/utilities.js
- src/redux/data.js
- src/redux/model.js
- src/redux/request.js
- src/redux/resolver.js
- src/routes/search.js
- tests/pages/title-search.js
- tests/title-search-test.js
- yarn.lock
Adds a filter component to the title search form and allows filtering search results via a `filter` query param.
- The search route will provide a filter component based on the current search type
- The filter component will receive a filter property and an `onUpdate` hook to update the form component's state
- The form component simply supplies the filter param on submit, and the search route adds it to the URL and makes the request
> Add ability to filter title searches

- .travis.yml
https://github.com/folio-org/ui-eholdings/pull/210 commented out the one test flaking out on Firefox Mac.
> Disallow Firefox Mac failures

- package.json
- yarn.lock
Thanks @ttamj  👏 
`yarn.lock` regenerated from scratch, to remove some duplicate package warnings.
> Use stripes-cli 1.0

- mirage/config.js
- mirage/factories/contributor.js
- mirage/factories/custom-coverage.js
- mirage/factories/customer-resource.js
- mirage/factories/embargo-period.js
- mirage/factories/identifier.js
- mirage/factories/managed-coverage.js
- mirage/factories/package.js
- mirage/factories/provider.js
- mirage/factories/subject.js
- mirage/factories/title.js
- mirage/factories/visibility-data.js
- mirage/models/contributor.js
- mirage/models/custom-coverage.js
- mirage/models/customer-resource.js
- mirage/models/embargo-period.js
- mirage/models/identifier.js
- mirage/models/managed-coverage.js
- mirage/models/package.js
- mirage/models/provider.js
- mirage/models/subject.js
- mirage/models/title.js
- mirage/models/visibility-data.js
- mirage/serializers/application.js
- mirage/start.js
- package.json
- tests/backend-configuration-test.js
- yarn.lock
Now that Mirage is under the BigTest umbrella, there's no reason to point to @cowboyd's fork anymore.
> Use @bigtest/mirage instead of the mirage-server fork

- package.json
Oops, pushed to the wrong place. Replaces https://github.com/folio-org/ui-eholdings/pull/249
> Remove NODE_ENV from server command

- src/components/search-form/search-form.css
- src/components/search-form/search-form.js
- src/routes/search.js
- tests/pages/package-search.js
- tests/pages/provider-search.js
Aligns eHoldings UX closer to that of other FOLIO apps.
We get a clear icon and a loading state for the search box. With the next upgrade of the version of `stripes-components` eHoldings uses, we'll get some style updates too.
Related to https://issues.folio.org/browse/UIEH-143
> Use stripes-components SearchField

- src/components/title-show.js
- tests/pages/bigtest/title-show.js
- tests/title-show-test.js
Ref [UIEH-196](https://issues.folio.org/browse/UIEH-196)
Convert `title-show` to `BigTest` to continue ongoing migration efforts.
Skipped test using `scrollToPackageOffset` as I have not seen a way that works yet for how to get this working.
> UIEH-196 Implement BigTest in title-show.

- tests/package-show-test.js
- tests/pages/bigtest/package-show.js
- tests/pages/package-show.js
Detail view scroll test skipped for now until we settle on an effective way to do that with BigTest.
> UIEH-196 Refactor package-show-test to use BigTest page objects

- tests/customer-resource-custom-coverage-test.js
- tests/pages/bigtest/customer-resource-custom-coverage.js
- tests/pages/bigtest/datepicker.js
- tests/pages/bigtest/package-show.js
Continuation of https://github.com/folio-org/ui-eholdings/pull/291.
Skipped section with collection that appears to have a bug in collection/appending. Need to investigate more, but for now, it's just skipped.
> DRY up datepicker page objects

- README.md
Switches out SVG and link on README.
> Replace Travis status badge with Circle status badge

- tests/customer-resource-selection-test.js
Ref [UIEH-196](https://issues.folio.org/browse/UIEH-196)
Convert `customer-resource-selection` to BigTest to continue ongoing migration efforts.
> UIEH-196: Refactor customer-resource-selection to use BigTest

- tests/pages/bigtest/settings.js
Dry up file as there was the same function define in the helpers file.
Import and use the `hasClassBeginningWith` function from helpers.
> Use hasClassBeginningWith helper in settings PO

- src/components/coverage-statement-fields/coverage-statement-fields.js
- src/components/coverage-statement-form/coverage-statement-form.js
- src/components/custom-embargo-fields/custom-embargo-fields.js
- src/components/custom-embargo-form/custom-embargo-form.js
- src/components/customer-resource-coverage-fields/customer-resource-coverage-fields.js
- src/components/customer-resource-coverage/customer-resource-coverage.js
- src/components/customer-resource-edit/customer-resource-edit.js
- src/components/customer-resource-show.js
- src/components/details-view/details-view.js
- src/components/modal/modal.js
- src/components/navigation-modal/navigation-modal.js
- src/components/package-custom-coverage/package-custom-coverage.js
- src/components/package-show.js
- src/components/search-form/search-filters.js
- src/components/search-form/search-form.js
- src/components/search-paneset/search-paneset.js
- src/components/settings/settings.js
- src/routes/application/application.js
- src/routes/settings.js
- tests/customer-resource-custom-coverage-test.js
- tests/pages/datepicker.js
- tests/pages/package-search.js
- tests/pages/title-search.js
- yarn.lock
Updates to the latest Stripes CLI/Core/Components.
Biggest changes:
- search field no longer has rounded corners
- profile icon is a circle
- inputs now have a "changed" state (a blue background), so inputs have a state between explicitly validated (green) and explicitly invalidated (red)
> Upgrade Stripes

- PULL_REQUEST_TEMPLATE.md
Discussed in eHoldings team Sprint 34 retrospective.
> Add JIRA issue notes to pull request template

- src/components/search-pane/search-pane.css
- src/components/search-paneset/search-paneset.js
Makes the eHoldings search UI more consistent with other FOLIO apps.
> Add title to search filters pane

- src/components/customer-resource-show.js
- src/components/details-view/details-view.js
- src/components/list/list.css
- src/components/package-list-item/package-list-item.css
- src/components/package-show.js
- src/components/provider-list-item/provider-list-item.css
- src/components/search-form/search-form.css
- src/components/settings-detail-pane/settings-detail-pane.js
- src/components/title-list-item/title-list-item.css
Fixes the easiest wins:
- Color contrast of text in results lists
- Add readable test to icon buttons
Bonus: fixes search filters pane sizing behavior.
> Clean up a11y issues

- src/components/navigation-modal/navigation-modal.js
- yarn.lock
Modals and dropdowns were getting improperly layered.
Resolves https://issues.folio.org/browse/UIEH-130
Dropdown issue was fixed in `stripes-components`. Use the locally defined `Modal` instead of the one from `stripes-components`.
> UIEH-130 Resolve z-index issues

- mirage/config.js
- src/components/resource/_fields/publisher-name/index.js
- src/components/resource/_fields/publisher-name/publisher-name.css
- src/components/resource/_fields/publisher-name/publisher-name.js
- src/components/resource/edit-custom/custom-resource-edit.js
- src/routes/resource-edit.js
- tests/custom-resource-edit-test.js
- tests/pages/resource-edit.js
Enables editing of the publisher on a custom title.
Resolves [UIEH-252](https://issues.folio.org/browse/UIEH-252)
> UIEH-252: Add a publisher field to custom resource edit page.

- package.json
- yarn.lock
Fixes bug where search filters accordions were closed by default.
> Upgrade stripes-cli / core / components

- src/redux/data.js
When sending a DELETE request there doesn't need to be a request body sent with the request. 
Remove the payload from the request epic.
>  Remove delete request payload

- src/components/search-paneset/search-paneset.js
Be able to create a new custom title from search results.
> UIEH-309 Add link to new title creation

- src/components/search-paneset/search-paneset.js
Reverts folio-org/ui-eholdings#387
Really want that dependency bot!
> Revert "UIEH-309 Add link to new title creation"

- src/components/search-paneset/search-paneset.js
Resolves https://issues.folio.org/browse/UIEH-309
Users need a way to get to the form to create a new custom title.
> UIEH-309 Show new title button on search results

- src/routes/package-show.js
- src/routes/resource-edit.js
- src/routes/title-create.js
- tests/pages/resource-edit.js
- tests/resource-edit-deselection-test.js
- tests/resource-edit-selection-test.js
Right now the test coverage threshold is a little low due to some changes that have been made that has left a lot of code unused. This change will remove a lot of outdated code and boost up the coverage.
> Remove outdated code to boost test coverage [WIP]

- package.json
- yarn.lock
Fixes clear button behavior on `TextField`s. Related to https://issues.folio.org/browse/STCOM-290.
> Upgrade stripes-components to 2.1.1

- package.json
- yarn.lock
Changelog: https://github.com/karma-runner/karma/releases/tag/v2.0.4
> Upgrade karma to 2.0.4

- src/components/package/show/package-show.js
Buttons and actions are sentence-cased in FOLIO.
> Sentence case holdings actions

- src/components/package/edit-custom/custom-package-edit.js
- src/components/package/edit-managed/managed-package-edit.js
- src/components/package/show/package-show.js
- tests/custom-resource-edit-selection-test.js
- tests/resource-edit-managed-title-in-custom-package-test.js
- translations/ui-eholdings/en.json
Internalization is process of making sure that the application is usable for people across several regions, countries, and languages. We want to make sure that any data that is visible to a user such as dates, number, strings are then translated and transformed into a format or language specific for a user of the application.
- Make sure that all data (ie. strings, dates, numbers) that will visible to a user is passed through a component that will pull from a translations file. That translations file will consists of the translation for a particular language etc. It will make sure that what data such as a string or date is formatted and translated appropriately.
- i8ln or Internalization is challenging reading through the react-intl readme and documentation along with following all the …
> UIEH-465 Localize package show / edit / create

- src/components/package/edit-custom/custom-package-edit.js
- src/components/package/edit-managed/managed-package-edit.js
- src/components/package/show/package-show.js
- src/components/provider-show/provider-show.js
- translations/ui-eholdings/en.json
Per https://issues.folio.org/browse/UIEH-478, we are supposed to support localization in providers show page.
- Navigate through code to find strings
- Add them to en.json, rename common ones to packages and providers like action menu items which will be shared
- Ensure that all tests pass
> UIEH-478: Localize providers show page

- package.json
- yarn.lock
Fixes nested scoping issue: https://github.com/bigtestjs/interactor/pull/39
> Upgrade BigTest packages

- tests/package-selection-test.js
The `indicates it is working to get to desired state` assertion was still being flaky after https://github.com/folio-org/ui-eholdings/pull/488.
My best guess is that the shorthand for the mirage endpoint was going ahead and resolving its error code (500), and not being blocked.
To get around that, I used mirage's `Response` to manually build the full response, with error code and no headers.
There are few more tests relying on Promises that, although they're thankfully not flaky, would benefit from `server.block()` and `server.unblock()`.
> Use Mirage Response to block endpoint with response code

- bigtest/tests/package-search-test.js
- bigtest/tests/provider-search-test.js
- bigtest/tests/title-search-test.js
- src/components/coverage-date-list/coverage-date-list.js
- src/components/error-screen/failed-backend.js
- src/components/error-screen/invalid-backend.js
- src/components/error-screen/no-backend.js
- src/components/inline-form/inline-form.js
- src/components/navigation-modal/navigation-modal.js
- src/components/package-search-list.js
- src/components/package/create/package-create.js
- src/components/package/edit-custom/custom-package-edit.js
- src/components/package/edit-managed/managed-package-edit.js
- src/components/package/show/package-show.js
- src/components/provider-search-list.js
- src/components/provider-show/provider-show.js
- src/components/query-list/query-list.js
- src/components/resource/edit-custom-title/resource-edit-custom-title.js
- src/components/resource/edit-managed-title/resource-edit-managed-title.js
- src/components/search-modal.js
- src/components/search-paneset/search-paneset.js
- src/components/title-search-list.js
- src/components/title/create/title-create.js
- src/components/title/edit/title-edit.js
- translations/ui-eholdings/en.json
Related to [UIEH-479](https://issues.folio.org/browse/UIEH-479)
This PR contains my ongoing work towards localizing the rest of eHoldings.
I've mostly just been walking down the directory tree and hitting files that haven't been localized yet.
> UIEH-479: Localize catch all

- src/components/details-view/accordion-list-header.js
- src/components/details-view/details-view.js
- translations/ui-eholdings/en.json
Continue work on [UIEH-479](https://issues.folio.org/browse/UIEH-479)
This is a small one because I am pushing a potential fix to the `Search \u0026 Filters` bug to hopefully render an ampersand after building.
> UIEH-479: Localize Catch All - Details View and Accordion List

- src/components/error-screen/failed-backend.js
- src/components/error-screen/invalid-backend.js
- src/components/error-screen/no-backend.js
- src/components/package-list-item/package-list-item.js
- src/components/package/_fields/content-type/package-content-type-field.js
- src/components/package/_fields/custom-coverage/package-coverage-fields.js
- src/components/package/show/package-show.js
- src/components/provider-list-item/provider-list-item.js
- translations/ui-eholdings/en.json
Continuation of work done for [UIEH-479](https://issues.folio.org/browse/UIEH-479)
I focused mainly on the error screens and package content/details in this iteration. I am moving down the directory tree and checking all files to make sure nothing is missed.
> UIEH-479: Localize errors and packages

- src/components/provider/_fields/proxy-select/proxy-select-field.js
Adjust translations for inherited and proxy on Provider Edit page to match adjustments that were made as part of the following pull request 
https://github.com/folio-org/ui-eholdings/pull/535
Use more common new names that were established in noted PR. PR removed older names however they were still referenced by Provider Edit page
Before
After
> Translations  adjustments for Provide Proxy

- package.json
- yarn.lock
Just some more housekeeping before cutting 1.0 release next week :)
> Upgrade funcadelic

- package.json
- src/components/details-view/details-view.css
- src/components/package-list-item/package-list-item.css
- src/components/provider-list-item/provider-list-item.css
- src/components/search-form/search-form.css
- src/components/title-list-item/title-list-item.css
- src/components/toggle-switch/toggle-switch.css
- yarn.lock
90% of the changes are to follow this rule, which I'm quite impressed by: https://stylelint.io/user-guide/rules/no-descending-specificity/
> Upgrade stylelint

- docs/routing-architecture/routing-architecture.md
- package.json
Per https://issues.folio.org/browse/UIEH-553, update version to 1.0.0 for Q3 release.
Update package.json
> UIEH-553: Update version to 1.0.0

- .circleci/config.yml
- package.json
- src/routes/settings.js
- yarn.lock
Part of https://issues.folio.org/browse/STCOM-330
> STCOM-330 Get Settings from stripes-smart-components

- yarn.lock
Fixes some mobile layout bugs.
> Update yarn.lock to stripes-core v2.15.4

- package.json
- src/components/pane-header-button/pane-header-button.css
- src/components/search-paneset/search-paneset.js
- src/components/settings-detail-pane/settings-detail-pane.js
- src/components/settings-knowledge-base/settings-knowledge-base.js
- src/components/settings-root-proxy/_fields/root-proxy-select/root-proxy-select-field.js
- src/components/settings-root-proxy/settings-root-proxy.js
- src/routes/settings-knowledge-base.js
- src/routes/settings-root-proxy.js
- yarn.lock
[`react-final-form`](https://github.com/final-form/react-final-form) fits our form-handling needs better than `redux-form` - we don't really need the global state benefits of `redux-form`, and it's much nicer just working with components.
Replace `redux-form` with `react-final-form` for the two settings forms.
> Replace redux-form with react-final-form in settings

- src/components/details-view/details-view.js
- src/components/package/create/package-create.js
- src/components/package/show/package-show.js
- src/components/resource/_fields/custom-embargo/custom-embargo-fields.js
- src/components/search-form/search-form.js
- src/components/settings-detail-pane/settings-detail-pane.js
- src/components/title/create/title-create.js
- src/components/title/show/title-show.js
Uses `<FormattedMessage>` instead of `intl.formatMessage().`
> Use FormattedMessage for aria-label i18n

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/pt_BR.json
> Update translation strings as of 20181110T181812

- src/components/resource/_fields/custom-url/custom-url-fields.js
- src/components/resource/_fields/custom-url/index.js
- src/components/resource/edit-custom-title/resource-edit-custom-title.js
Continues work started in https://github.com/folio-org/ui-eholdings/pull/613 and https://github.com/folio-org/ui-eholdings/pull/614
Will make moving to `react-final-form` easier.
> Switch resource custom URL to field-level validation

- src/components/settings-knowledge-base/settings-knowledge-base.css
- src/components/settings-knowledge-base/settings-knowledge-base.js
- src/components/settings-root-proxy/settings-root-proxy.css
- src/components/settings-root-proxy/settings-root-proxy.js
- src/routes/application.js
- src/routes/application/application.css
- src/routes/application/index.js
- test/bigtest/interactors/application.js
- yarn.lock
Removing the extra `<Paneset>` from the `<Settings>` smart component worked fine everywhere except in eHoldings, where there was quite a bit of extra DOM to compensate for earlier `Paneset` bugs.
Make the `<form>` elements in settings pages `<Pane>`s. Remove any extra DOM so their width gets properly calculated.
Decouple completely from the `<Settings>` smart component.
> Fix settings layout bug

- src/components/search-form/search-form.css
- src/components/search-form/search-form.js
- test/bigtest/interactors/package-search.js
- test/bigtest/interactors/search-modal.js
- test/bigtest/interactors/title-search.js
Duplicates style changes from https://github.com/folio-org/stripes-smart-components/pull/326
> Adjust search form styles

- package.json
https://issues.folio.org/browse/UIEH-578
> UIEH-578 Release v1.2.0

- src/components/details-view-section/details-view-section.css
- src/components/search-paneset/search-paneset.css
Some hardcoded font size values were replaced with variables.
[Related story](https://issues.folio.org/browse/UIEH-583)
> UIEH-583: remove hardcoded font sizes

- package.json
- yarn.lock
> Upgrade to eslint-config-stripes 4.0.1

- src/components/package-search-list.js
- src/components/package/show/package-show.js
- src/components/provider-search-list.js
- src/components/provider/show/provider-show.js
- src/components/title-search-list.js
- src/components/title/show/title-show.js
> Adjust search results heights for smaller base font size

- translations/ui-eholdings/ar.json
> Update translation strings as of 20190227T140407

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/zh_CN.json
> Update translation strings as of 20190228T144944

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/pt_BR.json
> Update translation strings as of 20190306T161944

- package-lock.json
- package.json
Create a task for running "lint" task before git push
Add Husky package for easy managing git hooks
> Add husky and pre-push hook for linting code

- translations/ui-eholdings/ar.json
> Update translation strings as of 20190314T195719

- package.json
- src/components/package/show/package-show.js
In this small PR, I added an additional check to decide if an action menu should be render on package-show full view.
> UIEH-669: fix empty dropdown on custom package show full view

- src/components/agreements-list/agreements-list.js
- src/components/resource/resource-show.js
- src/routes/resource-show.js
- test/bigtest/interactors/package-show.js
- test/bigtest/interactors/resource-show.js
- test/bigtest/tests/resource-show-test.js
https://issues.folio.org/browse/UIEH-630
Create a section with agreements to add a possibility for attaching agreements.
- Add according with agreements list
- Add UI tests
> Agreements for resource details page

- src/components/package/show/package-show.js
- src/routes/package-show.js
The purpouse of this PR is to properly handle piltering for the resources(titles) for the package show page.
> UIEH-663: Fixed package resources(titles) filtering

- src/components/package/show/package-show.js
enable the ability to assign/unassign tags on packages regardless of isSelected value
> UIEH-670: Show tags for the not selected packages

- CHANGELOG.md
- src/features/agreements-accordion/agreements-accordion.css
- src/features/agreements-accordion/agreements-accordion.js
- test/bigtest/tests/resource-show-test.js
Add a margin to agreements "New" button and update change log
> UIEH-629, UIEH-631: Add margin to New button and update changelog

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/zh_CN.json
> Update translation strings as of 20190403T132033

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/zh_CN.json
> Update translation strings as of 20190415T231934

- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/it_IT.json
> Update translation strings as of 20190422T163602

- src/components/package/show/package-show.js
https://issues.folio.org/browse/UIEH-691
Integrate NotesSmartAccordion into Package show page
> Notes accordion for package show page

- src/constants/entityTypePluralizedTranslationKeys.js
- src/constants/entityTypeTranslationKeys.js
- src/constants/index.js
- src/index.js
- src/routes/note-create.js
- src/routes/note-edit.js
- test/bigtest/network/config.js
- translations/ui-eholdings/en.json
This PR adds an edit note page. It makes use of `NoteEditPage` component introduced recently in stripes-smart-components.
> Add edit note route

- src/components/package/show/package-show.js
- src/components/provider/show/provider-show.js
- src/components/resource/resource-show.js
- src/constants/index.js
- src/constants/paths.js
https://issues.folio.org/browse/UIEH-690
Integrate NotesSmartAccordion into Provider and Resource show pages
> UIEH-690: Add Notes accordion to Provider and Resource view pages

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/zh_CN.json
> Update translation strings as of 20190624T123511

- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/pt_BR.json
> Update translation strings as of 20190625T144718

- test/bigtest/interactors/package-show.js
- test/bigtest/interactors/provider-show.js
- test/bigtest/interactors/search-modal.js
- test/bigtest/interactors/tags-accordion.js
- test/bigtest/network/config.js
- test/bigtest/tests/package-show-titles-search-test.js
- test/bigtest/tests/provider-show-package-search-test.js
https://issues.folio.org/browse/UIEH-730
Test filtering by tags resources inside a package and packages inside a provider.
> Test filtering by tags

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/zh_CN.json
> Update translation strings as of 20190627T152539

- src/components/search-form/search-filters.js
- src/components/search-form/search-form.js
- src/components/search-modal/search-modal.js
- src/routes/search.js
- test/bigtest/interactors/package-search.js
- test/bigtest/interactors/provider-search.js
- test/bigtest/interactors/search-modal.js
- test/bigtest/interactors/tags-accordion.js
- test/bigtest/interactors/title-search.js
- test/bigtest/network/config.js
- test/bigtest/tests/package-search-test.js
- test/bigtest/tests/package-show-titles-search-test.js
- test/bigtest/tests/provider-search-test.js
- test/bigtest/tests/provider-show-package-search-test.js
- test/bigtest/tests/title-search-test.js
- translations/ui-eholdings/en.json
In this PR, I implemented toggling between searching by search term and searching by tags so that it's impossible to combine these types of search.
> UIEH-712, UIEH-713: Disable filtering by tags if user enters a search term or selects a filter

- CHANGELOG.md
- package.json
- yarn.lock
> Release v1.9.0

- src/api/agreements.js
- src/api/common/get-headers.js
- src/api/common/index.js
- src/api/common/parse-response-body.js
- src/api/index.js
- src/redux/actions/get-agreements-failure.js
- src/redux/actions/get-agreements-success.js
- src/redux/actions/get-agreements.js
- src/redux/data.js
- src/redux/epics/attach-agreement.js
- src/redux/epics/common/index.js
- src/redux/epics/common/parse-response-body.js
- src/redux/epics/get-agreements.js
- src/redux/epics/index.js
- src/redux/epics/update-entity-tags.js
- src/redux/index.js
- src/redux/reducers/agreements.js
- test/bigtest/tests/unit/actions/get-agreements-success-test.js
- test/bigtest/tests/unit/actions/get-agreements-test.js
- test/bigtest/tests/unit/epics/attach-agreement-test.js
- test/bigtest/tests/unit/epics/get-agreements-test.js
- test/bigtest/tests/unit/reducers/agreements-test.js
https://issues.folio.org/browse/UIEH-754
Cover epics tied to agreements with unit tests.
- Extract API calls from epics tied to agreements.
- Cover agreements epics with unit tests with a help of marble diagrams
https://chrisnoring.gitbooks.io/rxjs-5-ultimate/content/testing.html
> UIEH-754: Add unit tests to agreement epics.

- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/it_IT.json
> Update translation strings as of 20190812T142216

- src/redux/package.js
- src/redux/provider.js
- test/bigtest/tests/package-selection-test.js
The goal of this PR is to exclude non-used attributes from the PUT payloads for packages and providers
> UIEH-777, UIEH-778: Updated serializes to exclude not used attrs from PUT package and provider payloads

- src/api/agreements.js
- src/features/agreements-accordion/agreements-accordion.js
- src/redux/actions/attach-agreement-success.js
- src/redux/epics/attach-agreement.js
- src/redux/epics/get-agreements.js
- src/redux/reducers/agreements.js
- test/bigtest/tests/unit/epics/attach-agreement-test.js
- test/bigtest/tests/unit/epics/get-agreements-test.js
- test/bigtest/tests/unit/reducers/agreements-test.js
https://issues.folio.org/browse/UIEH-766
> UIEH-766: Add agreements errors handling

- CHANGELOG.md
- package.json
- test/bigtest/interactors/note-view.js
- test/bigtest/interactors/notes-accordion.js
- test/bigtest/tests/managed-package-edit-test.js
- test/bigtest/tests/package-notes-flow-test.js
- test/bigtest/tests/provider-notes-flow-test.js
- test/bigtest/tests/resource-edit-managed-title-test.js
- test/bigtest/tests/resource-notes-flow-test.js
- test/bigtest/tests/settings-root-proxy-test.js
- test/bigtest/tests/title-show-test.js
- yarn.lock
Regenerate yarn.lock with pointing the packages to npm-folio registry
> Release v2.0.1

- src/components/resource/_fields/custom-embargo/custom-embargo-fields.css
- src/components/resource/_fields/custom-embargo/custom-embargo-fields.js
https://issues.folio.org/browse/UIEH-784
> UIEH-784: Align size of the trash icon in embargo period row

- test/bigtest/helpers/turn-off-warnings.js
- test/bigtest/index.js
- test/bigtest/interactors/package-search.js
- test/bigtest/interactors/provider-search.js
- test/bigtest/interactors/title-search.js
- test/bigtest/network/config.js
- test/bigtest/tests/package-search-test.js
- test/bigtest/tests/provider-search-test.js
- test/bigtest/tests/title-search-test.js
The purpose of this PR is the tests refactoring.
The problem with failing tests in ChromeHeadless browser for the tests that pass in Crome was investigated, but no objective reasons was found.
Also, within this PR the following refactoring was made:
1) Suppressed react warnings for the deprecated methods usage
2) Small refactor in the tests flow
3) Added mirage endpoints for the tags update
4) Bug created in FOLIO https://issues.folio.org/browse/FOLIO-2297 and assigned to Anton Emelianov for the further processing
> UIEH-786: Tests refuctoring

- src/components/package/create/package-create.js
- src/components/title/create/title-create.js
This PR is for change the panels from the custom eholdings to the stripes ones for:
Titles new and  Packages new routes.
> UIEH-795: substitute custom eholdings panels for Titles new and Packages new routes with the one from stripes

- src/components/details-view/details-view.js
- src/components/search-form/search-form.css
- src/components/search-form/search-form.js
- src/components/search-paneset/search-paneset.js
- translations/ui-eholdings/en.json
https://issues.folio.org/browse/UIEH-780
- Fix tags multi-select left margin
- Provide MultiSelectionFilter component with aria-label
- Add ids for search results pane and details view pane header
> UIEH-780: Fix pane header ids for details view and search paneset. Provide aria label for tags multiselect.

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/he.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/ja.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/ru.json
- translations/ui-eholdings/zh_CN.json
- translations/ui-eholdings/zh_TW.json
> Update translation strings as of 20200103T213225

- translations/ui-eholdings/pt_BR.json
> Update translation strings as of 20200106T223901

- translations/ui-eholdings/zh_CN.json
> Update translation strings as of 20200109T152437

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/he.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/ja.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/ru.json
- translations/ui-eholdings/zh_CN.json
- translations/ui-eholdings/zh_TW.json
> Update translation strings as of 20200110T211826

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/pt_BR.json
> Update translation strings as of 20200117T173544

- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/it_IT.json
> Update translation strings as of 20200127T144839

- CHANGELOG.md
- src/components/title/show/title-show.js
- test/bigtest/tests/custom-title-edit-test.js
- test/bigtest/tests/provider-show-test.js
- Update pane header after PR, since buttons with the same functions are duplicated
- Change IconButton to Button with the latest requirements
-->
> UIEH-824: View Custom Title: Remove the Actions dropdown

- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/he.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/ja.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/ru.json
- translations/ui-eholdings/ur.json
- translations/ui-eholdings/zh_CN.json
- translations/ui-eholdings/zh_TW.json
> Update translation strings as of 20200217T172736

- CHANGELOG.md
- package.json
> Bump to version 3 with stripes v3

- src/routes/package-edit.js
Fixed routing back for the Packages. From the package edit to the search list.
> UIEH-845: Packages: Clicking "X" starts a nasty loop

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/he.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/ja.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/ru.json
- translations/ui-eholdings/ur.json
- translations/ui-eholdings/zh_CN.json
- translations/ui-eholdings/zh_TW.json
> Update translation strings as of 20200312T133304

- CHANGELOG.md
- src/components/provider-list-item/provider-list-item.css
- src/components/provider-list-item/provider-list-item.js
- src/components/provider-search-list.js
- translations/ui-eholdings/en.json
UI updates for provider search list
[UIEH-846](https://issues.folio.org/browse/UIEH-846)
> UIEH-846: Package Results UI updates

- src/routes/package-show.js
- src/routes/provider-show.js
Fix bug with updating query string after click reset button
> UIEH-853-fix: fix bug with query string

- src/components/resource/edit-custom-title/resource-edit-custom-title.js
- src/components/resource/edit-managed-title/resource-edit-managed-title.js
- src/routes/resource-show.js
Fix inconsistent proxy selection on title+package records
> UIEH-875: Edit Provider and Edit Title + Package records | inconsistent proxy selection

- src/components/search-form/search-form.js
- src/components/search-modal/search-modal.js
- src/routes/provider-show.js
- src/routes/search.js
- test/bigtest/interactors/accessTypesFilterAccordion.js
- test/bigtest/interactors/package-search.js
- test/bigtest/network/config.js
- test/bigtest/tests/package-search-test.js
- translations/ui-eholdings/en.json
This PR adds the possibility to filter packages by access status types
> UIEH-835: implement filtering packaes by access status types

- src/components/resource/edit-custom-title/resource-edit-custom-title.js
- src/components/resource/edit-managed-title/resource-edit-managed-title.js
Made `getInitialValuesFromModel` static to be able to use from `getDerivedStateFromProps`
> UIEH-875: Changed getInitialValuesFromModel to a static method

- src/routes/package-show.js
- src/routes/provider-show.js
add possibility to save sorting for providers and packages
> UIEH-853-bugfix: fix sorting on all possible items

- src/components/search-modal/search-modal.js
- src/routes/resource-show.js
- test/bigtest/interactors/package-edit.js
- test/bigtest/tests/backend-configuration-test.js
- test/bigtest/tests/custom-package-edit-proxy-test.js
- test/bigtest/tests/custom-package-edit-selection-test.js
Fixed Tags filter is selected by default on Search Modal in Provider and Package pages
> UIEH-822: Provider, Package Search Modal: Tags filter is selected by default

- src/api/kb-credentials.js
- src/components/settings/settings-knowledge-base/settings-knowledge-base.js
- src/components/settings/settings.css
- src/components/settings/settings.js
- src/components/utilities.js
- src/constants/index.js
- src/constants/kbCredentialsReduxStateShape.js
- src/index.js
- src/redux/actions/confirm-put-kb-credentials.js
- src/redux/actions/index.js
- src/redux/reducers/kb-credentials.js
- src/routes/settings-knowledge-base.js
- src/routes/settings-route.js
- test/bigtest/interactors/settings-configuration.js
- test/bigtest/interactors/settings.js
- test/bigtest/network/config.js
- test/bigtest/tests/backend-configuration-test.js
- test/bigtest/tests/settings-access-status-types-test.js
- test/bigtest/tests/settings-test.js
- test/bigtest/tests/unit/reducers/kb-credentials-test.js
- translations/ui-eholdings/en.json
- Update Settings > eholdings to show a list of KB configurations
> UIEH 869: Display list of KB credentials

- src/api/kb-credentials.js
- src/components/settings/settings-knowledge-base/settings-knowledge-base.js
- src/redux/actions/put-kb-credentials.js
- src/redux/epics/put-kb-credentials.js
- src/routes/settings-knowledge-base.js
- Fix POST and PUT kb credentials
- Fix Create KB credentials form visible on page load
> Fixed creation and edit of Kb credentials

- src/api/access-types.js
- src/api/custom-labels.js
- src/redux/actions/attach-access-type.js
- src/redux/actions/delete-access-type.js
- src/redux/actions/get-access-types.js
- src/redux/actions/update-access-type.js
- src/redux/epics/attach-access-type.js
- src/redux/epics/delete-access-type.js
- src/redux/epics/get-access-types.js
- src/redux/epics/update-access-type.js
- src/routes/settings-access-status-types.js
- test/bigtest/tests/unit/actions/attach-access-type-test.js
- test/bigtest/tests/unit/actions/delete-access-type-test.js
- test/bigtest/tests/unit/actions/get-access-types-test.js
- test/bigtest/tests/unit/actions/update-access-type-test.js
- Use KB Id to fetch, update, delete access types in Settings
> UIEH-869: Update access types to use KB Credential Id

- src/components/settings/settings-knowledge-base/settings-knowledge-base.js
- Show asterisk next to customerId and apiKey fields
> UIEH-885: KB Credentials mark required fields

- src/components/package-search-filters.js
- src/components/provider-search-filters.js
- src/components/resource/edit-custom-title/resource-edit-custom-title.js
- src/components/resource/edit-managed-title/resource-edit-managed-title.js
- src/components/resource/recource-edit-proptypes.js
- src/components/resource/resource-edit.js
- src/components/settings/settings-access-status-types/settings-access-status-types.js
- src/components/title-search-filters.js
- src/constants/accessTypesReduxStateShape.js
- src/constants/filterConfigs.js
- src/constants/index.js
* Move reusable filters to variables and reuse them
* Refactor ResourceEdit, ResourceEditManagedTitle, ResourceEditCustomTitle as much as possible to get rid of duplicated code
> Remove code duplications 

- CHANGELOG.md
- src/components/package-search-list.js
- src/components/provider/show/provider-show.js
- src/components/search-package-list-item/search-package-list-item.js
- test/bigtest/interactors/provider-show.js
- test/bigtest/tests/provider-show-test.js
UI updates for Provider record list of Packages
[UIEH-861](https://issues.folio.org/browse/UIEH-861)
> UIEH-861: Provider Record Packages UI update

- src/api/access-types.js
- src/components/settings/settings-access-status-types/settings-access-status-types.js
- src/components/settings/settings-form/settings-form.css
- src/components/settings/settings-form/settings-form.js
- src/components/utilities.js
- src/redux/actions/delete-access-type-success.js
- src/redux/actions/delete-access-type.js
- src/redux/epics/attach-access-type.js
- src/redux/epics/delete-access-type.js
- src/redux/reducers/accessTypes.js
- src/routes/settings-access-status-types.js
- src/routes/settings-root-proxy.js
- test/bigtest/network/config.js
- test/bigtest/tests/settings-access-status-types-test.js
- test/bigtest/tests/unit/actions/delete-access-type-success-test.js
- test/bigtest/tests/unit/actions/delete-access-type-test.js
- Fix failing requests to access types and custom labels endpoints
- Fix failing tests
- Fix minor visual issues
> Single Tenant: Fix issues with access types and custom labels requests

- src/components/settings/settings-form/settings-form.js
Change save KB form button text
Related PR in `stripes-components`: https://github.com/folio-org/stripes-components/pull/1281
> UIEH-899: Settings > eholdings > KB credentials page | UI updates

- package.json
- translations/ui-eholdings/en.json
Add definitions of access type permissions
> UIEH-864 Add access types permissions

- src/components/settings/settings-access-status-types/settings-access-status-types.js
- src/components/settings/settings.js
- src/components/utilities.js
- src/routes/settings-access-status-types.js
- Add ability to assign different sets of permissions to access types to users
- Remove ability to perform actions that a user doesn't have permissions to
> UIEH-864: Access status types settings permissions

- src/components/settings/settings-access-status-types/settings-access-status-types.js
- src/components/settings/settings-custom-labels/custom-label-field/custom-label-field.js
- src/components/settings/settings-knowledge-base/settings-knowledge-base.js
- src/components/settings/settings.js
* added provided all of the settings form elements with labels (UIEH-894)
* removed unnecessary 'h3' placed inside 'h2' in the settings pane header (UIEH-895)
> UIEH-894, UIEH-895: Fix accessibility and semantics issues on the settings page

- src/components/details-view-section/details-view-section.css
- src/components/details-view/accordion-list-header.css
- src/components/details-view/details-view.css
- src/components/key-value-columns/key-value-columns.css
- src/components/list/list.css
- src/components/settings/settings-knowledge-base/settings-knowledge-base.js
- test/bigtest/helpers/monkey-patch-run.js
> UIEH-896: apply the default container width to create, edit, view pages

- src/components/details-view/details-view.js
It's not necessary to enable the list scrollbar when it has only few items.
> UIEH-897: disable switching scrollbars when it's unnecessary

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/he.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/ja.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/ru.json
- translations/ui-eholdings/ur.json
- translations/ui-eholdings/zh_CN.json
- translations/ui-eholdings/zh_TW.json
> Update translation strings as of 20200716T140311

- CHANGELOG.md
- src/components/search-form/search-form.js
- test/bigtest/network/config.js
- test/bigtest/network/helpers.js
- Update filter by Tags query string format
> UIEH-922: eHoldings > Search > Filter by Tags sends query parameters in incorrect format

- translations/ui-eholdings/ru.json
> Update translation strings as of 20200727T130814

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/he.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/ja.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/ru.json
- translations/ui-eholdings/ur.json
- translations/ui-eholdings/zh_CN.json
- translations/ui-eholdings/zh_TW.json
> Update translation strings as of 20200804T150835

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/pt_BR.json
> Update translation strings as of 20200806T130626

- CHANGELOG.md
- package.json
> Update stripes to v5

- .circleci/config.yml
- CHANGELOG.md
- Jenkinsfile
- package.json
- src/components/settings/settings-knowledge-base/settings-knowledge-base.js
- src/routes/application.js
- test/bigtest/helpers/setup-application.js
- test/bigtest/interactors/application.js
- test/bigtest/tests/backend-configuration-test.js
- translations/ui-eholdings/en.json
- Add a "delete KB credentials" permission to prevent some users from deleting KB credentials
- Rename existing KB credentials permission to better describe it's purpose
> UIEH-910: Settings > eholdings permission updates 

- CHANGELOG.md
- src/components/no-results-message/index.js
- src/components/no-results-message/noResultsMessage.css
- src/components/no-results-message/noResultsMessage.js
- src/components/query-list/query-list.js
- translations/ui-eholdings/en.json
[UIEH-905](https://issues.folio.org/browse/UIEH-905)  No providers/packages/titles found does not show the search term entered.
No Provider/Package/Title results should display the following message: [ No providers/packages/titles found for "<<show the search term entered in search box>>." Please check your spelling and filters. ]
> UIEH-905 No providers/packages/titles found does not show the search term entered.

- src/routes/application.js
Check that status is loaded before showing error message on every page load
> UIEH-816: Fix error shows on every page refresh before status loads

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/he.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/ja.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/ru.json
- translations/ui-eholdings/ur.json
- translations/ui-eholdings/zh_CN.json
- translations/ui-eholdings/zh_TW.json
> Update translation strings as of 20200901T173106

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/he.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/ja.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/ru.json
- translations/ui-eholdings/ur.json
- translations/ui-eholdings/zh_CN.json
- translations/ui-eholdings/zh_TW.json
> Update translation strings as of 20200904T163521

- src/components/title/_fields/package-select/package-select-field.js
- src/components/title/show/title-show.js
- test/bigtest/interactors/add-to-custom-package-modal.js
- test/bigtest/interactors/title-create.js
- test/bigtest/tests/title-add-to-custom-package-test.js
- test/bigtest/tests/title-create-test.js
[UIEH-908](https://issues.folio.org/browse/UIEH-908) Replace Choose custom package component
Requirement: On Create/Edit Custom Resource page AND the Title record on the Choose custom package modal replace the 
`Select` component with `Selection` component
> UIEH-908 Replace Choose custom package component

- CHANGELOG.md
- package.json
Support new `erm` interface version `3.0`
> Bumped erm interface version to 3.0

- .eslintrc.js
- .github/axe-linter.yml
- CHANGELOG.md
- src/components/title/show/package-filter-modal/package-filter-modal.js
- Multi-select component in Title Record Filter packages is autofocusable
- Fix issue with dropdown menu
[UIEH-959](https://issues.folio.org/browse/UIEH-959)
> UIEH-959: Fix issues in Title Record Filter packages Multi-select component

- CHANGELOG.md
- package.json
> Updated react-intl to 5.8.0

- src/components/agreements-list/agreements-list.js
- src/features/agreements-accordion/agreements-accordion.js
[Fix comment](https://jenkins-aws.indexdata.com/blue/organizations/jenkins/folio-org%2Fui-eholdings/detail/UIEH-956-fix/1/pipeline) - Add tooltip to unassign agreement button
> UIEH-956: Add tooltip for unassign agreement button

- translations/ui-eholdings/ar.json
- translations/ui-eholdings/ca.json
- translations/ui-eholdings/da.json
- translations/ui-eholdings/de.json
- translations/ui-eholdings/en_GB.json
- translations/ui-eholdings/en_SE.json
- translations/ui-eholdings/en_US.json
- translations/ui-eholdings/es.json
- translations/ui-eholdings/es_419.json
- translations/ui-eholdings/es_ES.json
- translations/ui-eholdings/fr.json
- translations/ui-eholdings/fr_FR.json
- translations/ui-eholdings/he.json
- translations/ui-eholdings/hi_IN.json
- translations/ui-eholdings/hu.json
- translations/ui-eholdings/it_IT.json
- translations/ui-eholdings/ja.json
- translations/ui-eholdings/ko.json
- translations/ui-eholdings/pl.json
- translations/ui-eholdings/pt_BR.json
- translations/ui-eholdings/pt_PT.json
- translations/ui-eholdings/ru.json
- translations/ui-eholdings/ur.json
- translations/ui-eholdings/zh_CN.json
- translations/ui-eholdings/zh_TW.json
> Update translation strings as of 20201020T221939

- src/components/settings/settings-usage-consolidation/settings-usage-consolidation.js
- Fix Usage Consolidation settings field order
- Fix missing label for Platform Type field
> Fix Usage Consolidations settings field order

- src/components/custom-labels-section/custom-labels-edit-section.js
- translations/ui-eholdings/en.json
- Use parametrized translation string for Custom Labels value validation error
> Updated Custom Labels value length validation error message

- CHANGELOG.md
- src/components/title/show/title-show.js
- test/bigtest/interactors/title-show.js
- test/bigtest/interactors/title-usage-consolidation.js
- test/bigtest/tests/resource-show-test.js
- test/bigtest/tests/title-show-test.js
- Added Usage Consolidation accordion to Title Record
- Added tests
[UIEH-950](https://issues.folio.org/browse/UIEH-950)
> UIEH-950: Title Record: Display Usage & Analysis Accordion, Year and Platform Filters 

- .gitignore
- CHANGELOG.md
- package.json
- src/components/settings/settings-usage-consolidation/settings-usage-consolidation.js
- src/components/settings/settings.js
- src/routes/settings-usage-consolidation-route.js
- translations/ui-eholdings/en.json
- Add permissions for Usage Consolidation in settings
- Add idea folder to git ignore
[UIEH-938](https://issues.folio.org/browse/UIEH-938)
> UIEH-938: Add permissions for Usage Consolidation in settings

- CHANGELOG.md
- src/components/search-form/search-filters.js
- src/components/title/show/package-filter-modal/package-filter-modal.js
- src/components/title/show/package-filter-modal/use-package-filter-select-options.js
- src/components/title/show/title-show.js
- src/constants/filterConfigs.js
- test/bigtest/interactors/package-filter-modal.js
- test/bigtest/tests/title-show-package-filter-test.js
-  Add a Selection Status filter to Search within Packages modal for Title Record
[UIEH-978](https://issues.folio.org/browse/UIEH-978)
> UIEH-978: Add a Selection Status filter to Search within Packages modal for Title Record

- CHANGELOG.md
- src/routes/application.js
- test/bigtest/tests/backend-configuration-test.js
- Removed `/status` request from Settings
[UIEH-1012](https://issues.folio.org/browse/UIEH-1012)
> UIEH-1012: Settings > eHoldings - Do not send /status request

- CHANGELOG.md
- src/redux/actions/costperuse/clear-cost-per-use-data.js
- src/redux/actions/costperuse/index.js
- src/redux/reducers/costPerUse.js
- src/routes/package-show.js
- src/routes/resource-show.js
- src/routes/title-show.js
Clear out Cost per Use data when leaving Resource/Package/Title View page
[UIEH-1013](https://issues.folio.org/browse/UIEH-1013)
> UIEH-1013: UC | Selecting Year/Platform selections persists when accessing another package/resource

- CHANGELOG.md
- src/components/custom-labels-section/custom-labels-show-section.css
- src/components/custom-labels-section/custom-labels-show-section.js
- Fixed text wrapping for Custom Labels
[UIEH-985](https://issues.folio.org/browse/UIEH-985)
> UIEH-985: Fixed text wrapping for Custom Labels

- CHANGELOG.md
- src/components/package/show/package-show.js
- src/components/resource/resource-show.js
- src/components/title/show/title-show.js
- src/redux/resource.js
- src/redux/title.js
- test/bigtest/network/factories/resource.js
- test/bigtest/network/factories/title.js
- test/bigtest/tests/package-usage-consolidation-test.js
- test/bigtest/tests/resource-show-test.js
- test/bigtest/tests/title-show-test.js
- test/bigtest/tests/title-usage-consolidation-test.js
- test/bigtest/tests/usage-consolidation-filters-test.js
Hide Usage Consolidation accordion:
- If a package is not selected then do not show the Usage & Analysis accordion
- If a title is not selected in any package then do not show the Usage & Analysis accordion
- If a resource is not selected and the title is not selected in any other package then do not show the Usage & Analysis accordion
- If a resource is not selected BUT the title is selected in another package then show the Usage & Analysis accordion
[UIEH-1000](https://issues.folio.org/browse/UIEH-1000)
> UIEH-1000: Package/Title/Resource: Not selected --- Usage and Analysis accordion should not display

- src/features/usage-consolidation-accordion/loading-message/loading-message.js
- src/features/usage-consolidation-accordion/summary-table/column-properties.js
- src/features/usage-consolidation-accordion/summary-table/summary-table.js
- src/features/usage-consolidation-accordion/summary-table/usage-column-header.js
- src/features/usage-consolidation-accordion/titles-table/titles-table.js
- src/features/usage-consolidation-accordion/usage-consolidation-content-title.js
- translations/ui-eholdings/en.json
Added missing Info icon in Usage Consolidation Title Cost
[UIEH-994](https://issues.folio.org/browse/UIEH-994)
> UIEH-994: Fix missing info icon on Usage Consolidation Title Cost

- CHANGELOG.md
- PERSONAL_DATA_DISCLOSURE.md
- Add personal data disclosure form
> UIEH-1031: Add personal data disclosure form

- src/constants/kbCredentialsReduxStateShape.js
- src/redux/reducers/kb-credentials.js
- src/routes/settings-knowledge-base.js
- test/bigtest/tests/unit/reducers/kb-credentials-test.js
Fix `<ShowHidePasswordField>` component not visible when visiting KB settings page and not reloading
Changed `<SettingsKnowledgeBaseRoute>` component to a functional component to use `useEffect` to detect props changes easier
> UIEH-1023: Fixed KB credentials show/hide key not shown unless page is reloaded

- CHANGELOG.md
- translations/ui-eholdings/en.json
Fix typos in Full text requests table title
[UIEH-1039](https://issues.folio.org/browse/UIEH-1039)
> UIEH-1039: Title and Resource record | Update header to read Full text requests by platform usage

- CHANGELOG.md
- src/features/usage-consolidation-accordion/usage-consolidation-content-title.js
- src/features/usage-consolidation-accordion/usage-consolidation-content.css
- test/bigtest/tests/title-usage-consolidation-test.js
Remove Usage and CostPerUse columns in Title Usage Consolidation Summary table
[UIEH-1040](https://issues.folio.org/browse/UIEH-1040)
> UIEH-1040: Title record: Updates to Usage & analysis accordion 

- CHANGELOG.md
- src/components/details-view/details-view.js
Fix scroll disappearing when an accordion is collapsed
[UIEH-1026](https://issues.folio.org/browse/UIEH-1026)
> UIEH-1026: Providers/Packages/Titles Record - Scroll disappears when an accordion is collapsed

- src/components/eholdings-app-context/eholdings-app-context.css
- src/components/eholdings-app-context/eholdings-app-context.js
- src/components/eholdings-app-context/eholdings-app-context.test.js
- translations/ui-eholdings/en.json
Fix issues described in [comment](https://issues.folio.org/browse/UIEH-1108?focusedCommentId=100851&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-100851)
Issue: [UIEH-1108](https://issues.folio.org/browse/UIEH-1108)
> UIEH-1108: Make links external

- CHANGELOG.md
- src/components/details-view/details-view.js
- src/components/provider/show/components/provider-settings/provider-settings.test.js
- src/components/provider/show/provider-show.js
- src/components/provider/show/provider-show.test.js
- test/jest/__mock__/stripesCore.mock.js
- test/jest/__mock__/stripesSmartComponent.mock.js
Add tests for ProviderShowPage
Issue: [UIEH-1093](https://issues.folio.org/browse/UIEH-1093)
> UIEH-1093: Add tests for Provider Show Page

- CHANGELOG.md
- src/index.js
Search shortcut should redirect to eHoldings search page
[UIEH-1111](https://issues.folio.org/browse/UIEH-1111)
> UIEH-1111: Search shortcut should redirect to eHoldings search page

- CHANGELOG.md
- src/index.js
Keep search parameters when redirecting to search page
[UIEH-1111](https://issues.folio.org/browse/UIEH-1111)
> UIEH-1111: eHoldings - Use the Go to Search & Filter pane shortcut on any page

- CHANGELOG.md
- translations/ui-eholdings/en.json
Update message for successful package edit to show warning about proxy and token edit delay.
[UIEH-1116](https://issues.folio.org/browse/UIEH-1116)
> UIEH-1116: Package record: Latency when updating a token value 

- CHANGELOG.md
- src/components/provider/edit/provider-edit.js
- src/components/provider/edit/provider-edit.test.js
Add tests
Issue: [UIEH-1083](https://issues.folio.org/browse/UIEH-1083)
> UIEH-1083: Add tests on RTL/Jest for ProviderEdit component

- CHANGELOG.md
- Jenkinsfile
- package.json
Issue: [UIEH-1124](https://issues.folio.org/browse/UIEH-1124)
> UIEH-1124: Compile translation files into AST format

- CHANGELOG.md
- package.json
- src/components/resource/resource-show.js
- src/components/resource/resource-show.test.js
- src/components/tags/tags-accordion.js
- src/components/tags/tags-accordion.test.js
- src/features/custom-labels-accordion/custom-labels-accordion.test.js
- src/hooks/index.js
- src/hooks/use-section-toggle/useSectionToggle.js
- src/hooks/use-section-toggle/useSectionToggle.test.js
- src/hooks/useSectionToggle.js
- test/bigtest/helpers/setup-application.js
- test/bigtest/interactors/resource-drop-down-menu.js
- test/bigtest/tests/resource-show-test.js
- test/jest/__mock__/index.js
- test/jest/__mock__/matchMedia.mock.js
- test/jest/helpers/harness.js
- test/jest/helpers/wait.js
- Change `<ResourceShow>` from class to functional component
- Add `useSectionToggle` hook and tests to remove section toggle functionality code duplication between record pages
- Fix BigTest errors
- Add Jest tests for `<ResourceShow>`, `<TagsAccordion>`, `<CustomLabelsAccordion>`components
- Add `@testing-library/react-hooks` library to be able to test hooks
[UIEH-1097](https://issues.folio.org/browse/UIEH-1097)
> UIEH-1097: Jest+RTL > Test ResourceShow

- Jenkinsfile
Per Zak Burke's message, we need to run tests via `runScripts` option in Jenkinsfile
> Updated Jesnkins file to run tests with new approach

- CHANGELOG.md
- package.json
Reverts folio-org/ui-eholdings#1353
> Revert "Release v6.1.0"

- CHANGELOG.md
- package.json
- src/components/eholdings-app-context/eholdings-app-context.test.js
> Release v6.1.0

- src/components/search-package-list-item/search-package-list-item.js
- src/components/search-package-list-item/search-package-list-item.test.js
- src/components/settings/settings-root-proxy/_fields/root-proxy-select/root-proxy-select-field.js
- src/components/settings/settings-root-proxy/_fields/root-proxy-select/root-proxy-select-field.test.js
- src/components/tags-label/tags-label.test.js
- src/components/title/_field-groups/add-title-to-package.js
- src/components/title/_field-groups/add-title-to-package.test.js
Added tests for SearchPackageListItem, RootProxySelectField, TagsLabel, AddTitleToPackage
Issue: [UIEH-1050](https://issues.folio.org/browse/UIEH-1050)
> UIEH-1050: Jest+RTL > Test SearchPackageListItem, RootProxySelectField, TagsLabel, AddTitleToPackage

- src/components/contributors-list.js
- src/components/contributors-list.test.js
- src/components/identifiers-list.js
- src/components/identifiers-list.test.js
- src/components/toaster/toaster.js
- src/components/toaster/toaster.test.js
- src/components/toggle-switch/toggle-switch.js
- src/components/toggle-switch/toggle-switch.test.js
- src/components/token/token-field.js
- src/components/token/token-field.test.js
Add tests for Toaster, ToggleSwitch, TokenField, ContributorsList, IdentifiersList
Issue: [UIEH-1053](https://issues.folio.org/browse/UIEH-1053)
> UIEH-1053: Jest+RTL > Test Toaster, ToggleSwitch, TokenField, ContributorsList, IdentifiersList

- CHANGELOG.md
- src/components/coverage-date-list/coverage-date-list.js
- src/components/coverage-date-list/coverage-date-list.test.js
- Add tests for CoverageDateList component
- Refactoring
Issue: [UIEH-1056](https://issues.folio.org/browse/UIEH-1056)
> UIEH-1056: Jest+RTL > Test CoverageDateList

- CHANGELOG.md
- package.json
Fix of this [PR](https://github.com/folio-org/ui-eholdings/pull/1367)
> UIEH-1135: Add permissions

- package.json
> UIEH-1135: Fix permission

- CHANGELOG.md
- src/components/resource/edit-custom-title/resource-edit-custom-title.js
- src/components/resource/edit-custom-title/resource-edit-custom-title.test.js
Add tests for ResourceEditManagedTitle component
Issue: [UIEH-1095](https://issues.folio.org/browse/UIEH-1095)
> UIEH-1095: Jest+RTL > Test ResourceEditCustomTitle

- CHANGELOG.md
- src/components/title/show/title-show.test.js
Add tests for ResourceEditManagedTitle component
Issue: [UIEH-1098](https://issues.folio.org/browse/UIEH-1098)
> UIEH-1098: Jest+RTL > Test TitleShow

- CHANGELOG.md
- src/components/title/_field-groups/add-title-to-package.js
- src/components/title/_fields/package-select/package-select-field.js
- src/components/title/_fields/package-select/package-select-field.test.js
- src/components/title/create/title-create.js
- src/components/title/show/title-show.js
- src/routes/title-create.js
- src/routes/title-show.js
Load packages for package select field when user searches by package name.
https://github.com/folio-org/stripes-components/pull/1586
[UIEH-962](https://issues.folio.org/browse/UIEH-962)
> UIEH-962 Choose custom package - batch load packages

- CHANGELOG.md
- src/components/package/edit-custom/custom-package-edit.js
- src/components/package/edit-managed/managed-package-edit.js
- src/components/package/selection-status.js
- src/components/package/show/package-show.js
- src/components/package/show/package-show.test.js
- src/components/resource/edit-custom-title/resource-edit-custom-title.js
- src/components/resource/edit-custom-title/resource-edit-custom-title.test.js
- src/components/resource/edit-managed-title/resource-edit-managed-title.js
- src/components/resource/edit-managed-title/resource-edit-managed-title.test.js
- src/components/resource/recource-edit-proptypes.js
- src/components/resource/resource-edit.js
- src/components/selection-modal/selection-modal.js
- Add tests for `<PackageShow>` component
[UIEH-1094](https://issues.folio.org/browse/UIEH-1094)
> UIEH-1094: Jest+RTL > Test PackageShow

- CHANGELOG.md
- src/components/package/selection-status.js
- src/components/package/selection-status.test.js
- Add tests for SelectionStatus component
- Refactoring
Issue: [UIEH-1059](https://issues.folio.org/browse/UIEH-1059)
> UIEH-1059: Jest+RTL > Test SelectionStatus

- CHANGELOG.md
- src/components/provider-list-item/provider-list-item.js
- src/components/provider-list-item/provider-list-item.test.js
- Add tests for ProviderListItem component
- Refactoring
Issue: [UIEH-1060](https://issues.folio.org/browse/UIEH-1060)
> UIEH-1060: Jest+RTL > Test ProviderListItem

- CHANGELOG.md
- src/components/eholdings/eholdings.test.js
> UIEH-1153: Add tests for EHoldings component

- CHANGELOG.md
- src/components/provider/show/components/provider-information/provider-information.js
Change Provider information display on View Provider details record
[UIEH-1156](https://issues.folio.org/browse/UIEH-1156)
> UIEH-1156: View Provider Details | Change Provider Information Display

- CHANGELOG.md
- src/components/package/show/components/package-information/package-information.js
Change Package information display on View Package details record
[UIEH-1157](https://issues.folio.org/browse/UIEH-1157)
> UIEH-1157: View Package Detail Record | Change Package Information Display

- CHANGELOG.md
- src/components/resource/components/edit/resource-settings/edit-resource-settings.js
Change Resource Settings Display on Edit Resource details record
[UIEH-1161](https://issues.folio.org/browse/UIEH-1161)
> UIEH-1161: Edit Resource Detail Record: Change Resource Settings Display

- CHANGELOG.md
- package.json
Issue: [UIEH-1154](https://issues.folio.org/browse/UIEH-1154)
> UIEH-1154: Support erm 5.0 interface

- CHANGELOG.md
- src/features/agreements-accordion/agreements-accordion.js
- src/features/agreements-accordion/agreements-accordion.test.js
- Add tests for AgreementsAccordion
[UIEH-1071](https://issues.folio.org/browse/UIEH-1071)
> UIEH-1071: Jest+RTL > Test AgreementsAccordion

- CHANGELOG.md
- src/components/package-search-list.js
- src/components/package-search-list.test.js
- src/components/provider-search-list.js
- src/components/provider-search-list.test.js
- src/components/title-search-list.js
- src/components/title-search-list.test.js
Add tests for PackageSearchList, ProviderSearchList, TitleSearchList components
Issue: [UIEH-1070](https://issues.folio.org/browse/UIEH-1070)
> UIEH-1070: Jest+RTL > Test PackageSearchList, ProviderSearchList, TitleSearchList

- CHANGELOG.md
- src/components/search-form/search-filters.js
- src/components/search-form/search-filters.test.js
Jest+RTL > Test SearchFilters
[UIEH-1075](https://issues.folio.org/browse/UIEH-1075)
> UIEH-1075 Jest+RTL > Test SearchFilters

- CHANGELOG.md
- src/components/settings/settings-custom-labels/custom-label-field/custom-label-field.js
- src/components/settings/settings-custom-labels/custom-label-field/custom-label-field.test.js
Jest+RTL > Test CustomLabelField
[UIEH-1076](https://issues.folio.org/browse/UIEH-1076)
> UIEH-1076: Jest+RTL > Test CustomLabelField

- CHANGELOG.md
- src/components/proxy-display/proxy-display.css
- src/components/proxy-display/proxy-display.js
- src/components/proxy-display/proxy-display.test.js
- translations/ui-eholdings/en.json
Fix proxy display by applying id's comparison in lowercase
Issue: [UIEH-1143](https://issues.folio.org/browse/UIEH-1143)
> UIEH-1143: Root proxy selection is not saved

- CHANGELOG.md
- src/components/settings/settings-root-proxy/settings-root-proxy.js
- src/components/settings/settings-root-proxy/settings-root-proxy.test.js
- Add tests for SettingsRootProxy component
- Refactoring
Issue: [UIEH-1078](https://issues.folio.org/browse/UIEH-1078)
> UIEH-1078: Jest+RTL > Test SettingsRootProxy

- CHANGELOG.md
- src/components/tags/tags.js
- src/components/tags/tags.test.js
Add tests for Tags component
[UIEH-1080](https://issues.folio.org/browse/UIEH-1080)
> UIEH-1080: Jest+RTL > Test Tags

- CHANGELOG.md
- src/components/title/show/package-filter-modal/package-filter-modal.js
- src/components/title/show/package-filter-modal/package-filter-modal.test.js
Add tests for `<PackageFilterModal>` component
[UIEH-1081](https://issues.folio.org/browse/UIEH-1081)
> UIEH-1081: Jest+RTL > Test PackageFilterModal

- CHANGELOG.md
- src/components/settings/settings-custom-labels/custom-label-field/custom-label-field.js
- src/components/settings/settings-custom-labels/settings-custom-labels.js
- src/components/settings/settings-custom-labels/settings-custom-labels.test.js
- Add tests for SettingsCustomLabels component
- Refactoring
Issue: [UIEH-1077](https://issues.folio.org/browse/UIEH-1077)
> UIEH-1077: Jest+RTL > Test SettingsCustomLabels

- CHANGELOG.md
- package.json
- src/components/impagination.js
- src/components/package-search-list.js
- src/components/provider-search-list.js
- src/components/query-list/query-list.js
- src/components/scroll-view/scroll-view.js
- src/components/title-search-list.js
- src/redux/model.js
- src/routes/search.js
- Add PrevNext to providers/packages/titles list
Issues: [UIEH-1162](https://issues.folio.org/browse/UIEH-1162), [UIEH-1162](https://issues.folio.org/browse/UIEH-1165), [UIEH-1162](https://issues.folio.org/browse/UIEH-1164)
Unavailable to make it through epics. Make soft changes for correct work of application.
Remove `impagination`
> UIEH-1162: Apply Next/Previous component for Packages results

- CHANGELOG.md
- src/components/details-view/details-view.js
- src/components/details-view/details-view.test.js
- src/components/details-view/index.js
Add tests for `DetailsView` component
Coverage is 82.8%
[UIEH-1082](https://issues.folio.org/browse/UIEH-1082)
> UIEH-1082: Jest+RTL > Test DetailsView

- CHANGELOG.md
- src/components/settings/settings-knowledge-base/settings-knowledge-base.js
- src/components/settings/settings-knowledge-base/settings-knowledge-base.test.js
- src/constants/apiEndpointsOptions.js
- src/constants/index.js
- src/constants/kbNameValueMaxLength.js
- src/routes/settings-knowledge-base.js
- translations/ui-eholdings/en.json
- Refactoring of `SettingsKnowledgeBase` component
- Add tests
Issue: [UIEH-1089](https://issues.folio.org/browse/UIEH-1089)
> UIEH-1089: Add tests for SettingsKnowledgeBase component

- CHANGELOG.md
- src/components/package/edit-managed/managed-package-edit.js
- src/components/package/edit-managed/managed-package-edit.test.js
- src/components/selection-modal/selection-modal.js
Add tests for `ManagedPackageEdit` component.
Coverage percentage is 96.5%
[UIEH-1091](https://issues.folio.org/browse/UIEH-1091)
> UIEH-1091: Jest+RTL > Test ManagedPackageEdit

- CHANGELOG.md
- src/components/prev-next-buttons/prev-next-buttons.js
- src/components/prev-next-buttons/prev-next-buttons.test.js
- src/components/query-list/query-list.js
- src/components/query-search-list/query-search-list.js
Shift focus to the first result on the list once user hits Previous or Next pagination link.
[UIEH-1206](https://issues.folio.org/browse/UIEH-1206)
> UIEH-1206: Previous/Next pagination : Shift focus once user hits Previous or Next pagination link

- CHANGELOG.md
- src/features/usage-consolidation-accordion/full-text-request-usage-table/full-text-request-usage-table.test.js
Add tests for `FullTextRequestUsageTable` component.
Issue: [UIEH-1179](https://issues.folio.org/browse/UIEH-1179)
> UIEH-1179: Jest+RTL > Test FullTextRequestUsageTable

- CHANGELOG.md
- src/features/usage-consolidation-accordion/summary-table/summary-table.js
- src/features/usage-consolidation-accordion/summary-table/summary-table.test.js
Add tests for `SummaryTable` component.
Issue: [UIEH-1180](https://issues.folio.org/browse/UIEH-1180)
> UIEH-1180: Jest+RTL > Test SummaryTable

- .eslintrc.js
- CHANGELOG.md
- src/routes/note-create.test.js
- src/routes/note-edit.test.js
- src/routes/note-view.test.js
https://issues.folio.org/browse/UIEH-1185
> UIEH-1185: Add tests for NoteCreate, NoteEdit, NoteView Routes

- .eslintrc.js
- CHANGELOG.md
- src/components/eholdings/eholdings.js
- src/components/eholdings/eholdings.test.js
- src/routes/package-edit-route/index.js
- src/routes/package-edit-route/package-edit-route.js
- src/routes/package-edit-route/package-edit-route.test.js
Added tests for PackageEditRoute
[UIEH-1187](https://issues.folio.org/browse/UIEH-1187)
> UIEH-1187 Jest+RTL > Test PackageEditRoute

- .github/workflows/build-npm.yml
- package.json
Configured GitHub actions
[UIEH-1239](https://issues.folio.org/browse/UIEH-1239)
> Configured GitHub actions

- CHANGELOG.md
- src/components/eholdings/eholdings.js
- src/components/eholdings/eholdings.test.js
- src/routes/resource-show-route/index.js
- src/routes/resource-show-route/resource-show-route.js
- src/routes/resource-show-route/resource-show-route.test.js
Add tests for `ResourceShowRoute` component.
[UIEH-1191](https://issues.folio.org/browse/UIEH-1191)
> UIEH-1191: Jest+RTL > Test ResourceShowRoute

- CHANGELOG.md
- package.json
Issue: 
[UIEH-1264](https://issues.folio.org/browse/UIEH-1264)
> Release v7.1.2

- CHANGELOG.md
- src/hooks/index.js
- src/hooks/use-fetch-export-titles-from-package/useFetchExportTitlesFromPackage.js
- src/hooks/use-fetch-export-titles-from-package/useFetchExportTitlesFromPackage.test.js
Add tests for `useFetchExportTitlesFromPackage` hook.
Issue: [UIEH-1182](https://issues.folio.org/browse/UIEH-1182)
> UIEH-1182: Jest+RTL > Test useFetchExportTitlesFromPackage

- CHANGELOG.md
- package.json
Issue: [UIEH-1267](https://issues.folio.org/browse/UIEH-1267)
> Release v7.1.3

- CHANGELOG.md
- src/components/package/show/package-show.js
- src/components/package/show/package-show.test.js
- src/components/settings/settings-access-status-types/settings-access-status-types.test.js
- translations/ui-eholdings/en.json
Added "Export package (CSV)" option to View Package page action menu
[UIEH-1279](https://issues.folio.org/browse/UIEH-1279)
> UIEH-1279: View Package Details record > Actions menu > Add a Export record option

- CHANGELOG.md
- src/components/settings/settings-access-status-types/settings-access-status-types.test.js
- src/redux/actions/kb-credentials-users/post-kb-credentials-user-success.js
- src/redux/epics/post-kb-credentials-user.js
- src/redux/epics/tests/post-kb-credentials-user.test.js
- src/redux/reducers/kb-credentials-users.js
- src/redux/reducers/tests/kbCredentialsUsers.test.js
- src/routes/settings-assigned-users-route/settings-assigned-users-route.js
Remove unnecessary attributes from assign user request
[UIEH-1286](https://issues.folio.org/browse/UIEH-1286)
> UIEH-1286 Rework-kb-credentials: Remove attributes from user schema

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
- src/features/usage-consolidation-accordion/usage-consolidation-content-package.js
- src/hooks/use-fetch-export-titles-from-package/useFetchExportTitlesFromPackage.js
- src/hooks/use-fetch-export-titles-from-package/useFetchExportTitlesFromPackage.test.js
update NodeJS to v16 in GitHub Actions
[UIEH-1283](https://issues.folio.org/browse/UIEH-1283)
> UIEH-1283 update NodeJS to v16 in GitHub Actions

- CHANGELOG.md
- src/components/package/show/package-show.js
- src/components/package/show/package-show.test.js
Make Export package (CSV)  option available for non-selected resources
[UIEH-1287](https://issues.folio.org/browse/UIEH-1287)
> UIEH-1287: Requirement Change - View Package Details record > Actions menu > Add a Export record option

- CHANGELOG.md
- src/features/usage-consolidation-accordion/usage-consolidation-content-title/index.js
- src/features/usage-consolidation-accordion/usage-consolidation-content-title/usage-consolidation-content-title.js
- src/features/usage-consolidation-accordion/usage-consolidation-content-title/usage-consolidation-content-title.test.js
Jest+RTL > Test UsageConsolidationContentTitle
> UIEH-1278: Jest+RTL > Test UsageConsolidationContentTitle

- CHANGELOG.md
- src/components/settings/settings-access-status-types/settings-access-status-types.test.js
- src/features/export-package-resources-modal/constants.js
- src/features/export-package-resources-modal/utils.test.js
Issue: Enable Agreements, Notes and Package Holdings Status export fields
https://issues.folio.org/browse/UIEH-1298
> UIEH-1298 - Enable Agreements, Notes and Package Holdings Status export fields

- CHANGELOG.md
- src/components/settings/settings-access-status-types/settings-access-status-types.js
- src/components/settings/settings-assigned-users/settings-assigned-users.js
- src/components/settings/settings-form/settings-form.js
- src/components/settings/settings-form/settings-form.test.js
- src/components/settings/settings.js
Fix paneset widths and resizing issues in Settings
https://user-images.githubusercontent.com/19309423/174303522-629716b6-4d3c-40d0-b078-48417f11b790.mp4
[UIEH-1296](https://issues.folio.org/browse/UIEH-1296)
> UIEH-1296: Settings > eholdings > Assigned users page does not look right

- src/components/settings/settings.js
Fix settings panes
[UIEH-1296](https://issues.folio.org/browse/UIEH-1296)
> UIEH-1296 Fix settings panes

- CHANGELOG.md
- src/components/package/show/package-show.js
- src/components/package/show/package-show.test.js
- src/components/resource/resource-show.js
- src/components/resource/resource-show.test.js
Hide export eholdings buttons
[UIEH-1324](https://issues.folio.org/browse/UIEH-1324)
> UIEH-1324 Disable eholdings export

- src/components/package/show/package-show.js
- src/components/package/show/package-show.test.js
- src/components/resource/resource-show.js
- src/components/resource/resource-show.test.js
This reverts commit 984e227f0fed84d3c4f1a19ecf81b240ec3fa690.
> Revert "UIEH-1324 Disable eholdings export (#1590)"

- src/components/resource/components/resource-information/resource-information.js
- src/components/resource/components/resource-information/resource-information.test.js
- src/components/resource/resource-show.test.js
- src/routes/resource-show-route/resource-show-route.test.js
- translations/ui-eholdings/en.json
- add `Alternative titles(s)` field to resource information right after `Title` field;
- move `Title type` field after `Package content type`
- move `Peer Reviewed` after `Title type`
[UIEH-1328](https://issues.folio.org/browse/UIEH-1328)
> UIEH-1328: Resource (aka title+package) Detail Record: Add Alternate title(s) field

- src/components/package-search-list.test.js
- src/components/package/create/package-create.test.js
- src/components/provider-search-list.test.js
- src/components/resource/_fields/coverage-statement/coverage-statement-fields.test.js
- src/components/resource/_fields/visibility/visibility-field.test.js
- src/components/settings/settings-access-status-types/settings-access-status-types.test.js
- src/components/settings/settings-custom-labels/settings-custom-labels.test.js
- src/components/title-search-list.test.js
- src/components/title/_fields/contributor/contributor-field.test.js
- src/components/title/_fields/identifiers/identifiers-fields.test.js
- src/components/title/create/title-create.test.js
Fix tests caused by third party library updates
> UIEH-1332: Fix tests caused by third party library updates

- CHANGELOG.md
- src/features/export-package-resources-modal/constants.js
- src/features/export-package-resources-modal/export-package-resources-modal.test.js
- translations/ui-eholdings/en.json
Add the ability to export the `Provider level token` field.
[UIEH-1317](https://issues.folio.org/browse/UIEH-1317)
https://user-images.githubusercontent.com/77053927/195317400-0299e4a9-c82b-4fc9-b75d-5ff5360d9cb4.mp4
> UIEH-1317: Export package/title modal: Include Provider level token in list of fields to select

- CHANGELOG.md
- src/features/export-package-resources-modal/constants.js
- src/features/export-package-resources-modal/export-package-resources-modal.test.js
- translations/ui-eholdings/en.json
Add the ability to export the `Package level token` field.
[UIEH-1316](https://issues.folio.org/browse/UIEH-1316)
https://user-images.githubusercontent.com/77053927/195342764-df4a1a38-e238-4558-9af3-90635bac70d9.mp4
> UIEH-1316: Export package/title modal: Include Package level token in list of fields to select

- CHANGELOG.md
- src/features/export-package-resources-modal/constants.js
- src/features/export-package-resources-modal/export-package-resources-modal.test.js
- translations/ui-eholdings/en.json
Remove 'Provider Level Token' from Title fields
[UIEH-1317](https://issues.folio.org/browse/UIEH-1317)
https://user-images.githubusercontent.com/77053927/195578018-2cdb43b2-faa7-4b61-9bf6-7ce32083f63e.mp4
> UIEH-1317: remove 'Provider Level Token' from Title fields

- translations/ui-eholdings/en.json
Added missing translation for Package Level Token field
> UIEH-1317 Added missing translation

- CHANGELOG.md
- src/components/accordion-list-header/accordion-list-header.js
- src/components/details-view/details-view.js
- src/components/package/show/package-show.js
- src/components/package/show/package-show.test.js
- src/components/provider/show/provider-show.js
- src/components/query-search-list/query-search-list.js
- src/routes/package-show-route/package-show-route.js
- retrieve the titles data after opening the accordion of the titles
- don't display the number of titles during loading
[UIEH-1335](https://issues.folio.org/browse/UIEH-1335)
https://user-images.githubusercontent.com/77053927/203078923-27305b7a-dd33-4633-a243-5152b566edec.mp4
> UIEH-1335: Provider and Package detail records: Close Package and Titles accordion returns 0 titles

- CHANGELOG.md
- src/components/details-view/details-view.js
- src/components/details-view/details-view.test.js
Navigate to the holdings search page after clicking on the "X" icon.
[UIEH-1219](https://issues.folio.org/browse/UIEH-1219)
https://user-images.githubusercontent.com/77053927/208415077-6f4551ce-0352-43ac-8d7b-0694a1a6e4dd.mp4
> UIEH-1219: Difficulty returning to the eholdings page after adding a new Agreement

- .eslintrc.js
- CHANGELOG.md
- src/components/navigation-modal/navigation-modal.js
- src/components/query-search-list/query-search-list.js
- src/components/settings/settings-knowledge-base/settings-knowledge-base.js
- src/components/settings/settings-usage-consolidation/settings-usage-consolidation.js
- src/features/agreements-accordion/agreements-accordion.js
- src/hooks/use-fetch-export-titles-from-package/useFetchExportTitlesFromPackage.js
- src/hooks/useImpagination.js
- src/routes/custom-labels-route/custom-labels-route.js
- src/routes/settings-assigned-users-route/settings-assigned-users-route.js
- src/routes/settings-root-proxy-route/settings-root-proxy-route.js
- src/routes/settings-route/settings-route.js
- src/routes/settings-usage-consolidation-route.js
Enable react-hooks/exhaustive-deps ESLint rule
Issue: https://issues.folio.org/browse/UIEH-1339
Enabled react-hooks/exhaustive-deps ESLint rule as warning type. Fixed the associated errors in the entire module.
there are two instances in eholdings settings knowledge base where the history is being updated -
1. [https://github.com/folio-org/ui-eholdings/blob/866b11943f9c73ed362b6e639c598c96e7d[…]nts/settings/settings-knowledge-base/settings-knowledge-base.js](https://github.com/folio-org/ui-eholdings/blob/866b11943f9c73ed362b6e639c598c96e7daf300/src/components/settings/settings-knowledge-base/settings-knowledge-base.js#L67)
2. [https://github.com/folio-org/ui-eholdings/blob/866b11943f9c73ed362b6e639c598c96e7d[…]nts/settings/settings-knowledge-base/settings-knowledge-base.js](https://github. …
> UIEH-1339 - Enable react-hooks/exhaustive-deps ESLint rule

- src/components/route-history/route-history.js
- src/components/settings/settings-knowledge-base/settings-knowledge-base.js
- src/components/settings/settings.js
- src/components/settings/settings.test.js
- src/routes/settings-access-status-types-route/settings-access-status-types-route.js
- src/routes/settings-knowledge-base-route/settings-knowledge-base-route.js
- src/routes/settings-knowledge-base-route/settings-knowledge-base-route.test.js
- src/routes/settings-root-proxy-route/settings-root-proxy-route.js
- src/routes/settings-usage-consolidation-route.js
Fix navigation when returning from Settings > eHoldings
https://user-images.githubusercontent.com/19309423/211538193-0e296a9f-2596-4570-868b-3f098c8851c2.mp4
[UIEH-1219](https://issues.folio.org/browse/UIEH-1219)
> UIEH-1219: Fix history back when navigating Settings > eHoldings

- CHANGELOG.md
- package.json
- src/components/title/_fields/package-select/package-select-field.test.js
Bump stripes to 8.0.0
[UIEH-1352](https://issues.folio.org/browse/UIEH-1352)
> UIEH-1352: bump stripes to 8.0.0 for Orchid/2023-R1

- CHANGELOG.md
- package.json
- src/components/package/show/package-show.test.js
Upgrade react-redux to v8.
[UIEH-1353](https://issues.folio.org/browse/UIEH-1353)
> UIEH-1353 Upgrade react-redux to v8.

- CHANGELOG.md
- src/redux/helpers.js
Don't display custom labels after deletion.
[UIEH-1364](https://issues.folio.org/browse/UIEH-1364)
https://user-images.githubusercontent.com/77053927/224715706-659a0ce3-950f-4b65-bb29-61f7094d0cdd.mp4
> UIEH-1364: Don't display the deleted custom label

- CHANGELOG.md
- src/components/settings/settings-custom-labels/settings-custom-labels.js
Custom labels | Remove dashes below labels
[UIEH-1361](https://issues.folio.org/browse/UIEH-1361)
> UIEH-1361: Custom labels | Remove dashes below labels

- CHANGELOG.md
- package.json
> Release v8.0.2

- CHANGELOG.md
- package.json
> Release v8.0.3

- CHANGELOG.md
- src/features/export-package-resources-modal/export-package-resources-modal.test.js
- test/jest/__mock__/stripesCore.mock.js
- test/jest/helpers/harness.js
Avoid private paths in stripes-core imports:
https://issues.folio.org/browse/UIEH-1373
> UIEH-1373: Avoid private paths in stripes-core imports

- src/components/search-form/components/packages-filter-accordion/packages-filter-accordion.js
- src/components/search-form/components/packages-filter-accordion/packages-filter-accordion.test.js
Fix resetting other filters after selecting the Packages filter option.
[UIEH-1350](https://issues.folio.org/browse/UIEH-1350)
https://user-images.githubusercontent.com/77053927/233606158-2ba4e2c6-7f32-4a81-a0ba-e3dc35aa99d4.mp4
> UIEH-1350: Fix resetting other filters after selecting the Packages filter option.

- CHANGELOG.md
- src/components/accordion-list-header/accordion-list-header.js
- src/components/details-view/details-view.js
- src/components/title/show/package-filter-modal/package-filter-modal.js
- src/components/title/show/package-filter-modal/use-package-filter-select-options.js
- src/components/title/show/package-filter-modal/use-package-filter-select-options.test.js
- src/components/title/show/title-show.js
- src/components/title/show/title-show.test.js
Honor Packages facet selection in the result view.
[UIEH-1351](https://issues.folio.org/browse/UIEH-1351)
https://user-images.githubusercontent.com/77053927/233278597-e903bd7f-a949-4e92-a775-c6acda3f08cf.mp4
> UIEH-1351: Packages accordion - Honor Packages Facet selection.

- src/components/query-search-list/query-search-list.js
- src/components/search-form/components/packages-filter-accordion/packages-filter-accordion.js
- src/components/search-form/components/packages-filter-accordion/packages-filter-accordion.test.js
- src/components/search-form/components/packages-filter/packages-filter.js
- src/components/search-form/components/packages-filter/packages-filter.test.js
- src/components/search-form/search-form.js
- src/components/title-search-filters.js
- src/components/title-search-list.js
- src/components/title-search-list.test.js
- src/redux/data.js
- src/redux/data.test.js
- src/routes/search-route/search-route.js
- src/routes/search-route/search-route.test.js
Change the Multiselect to the Selection component for Packages facet.
[UIEH-1350](https://issues.folio.org/browse/UIEH-1350?focusedCommentId=166794&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-166794)
https://user-images.githubusercontent.com/77053927/235162095-6493ebbe-a351-4bd7-99c4-e36cf26dc2e3.mp4
> UIEH-1350: Change the Multiselect to the Selection component for Packages facet.

- CHANGELOG.md
- src/api/common/do-request.js
- src/api/common/get-headers.js
- src/hooks/use-fetch-export-titles-from-package/useFetchExportTitlesFromPackage.js
- src/redux/data.js
- src/redux/epics/update-entity-tags.js
Leverage cookie-based authentication in all API requests.
[UIEH-1345](https://issues.folio.org/browse/UIEH-1345)
> UIEH-1345: Leverage cookie-based authentication in all API requests.

- CHANGELOG.md
- src/components/title/_fields/package-select/package-select-field.css
- src/components/title/_fields/package-select/package-select-field.js
- src/components/title/show/title-show.css
- src/components/title/show/title-show.js
The list of packages is no longer cut off in the modal window.
[UIEH-1397](https://issues.folio.org/browse/UIEH-1397)
https://github.com/folio-org/ui-eholdings/assets/77053927/7cf0cb67-2ef6-4292-8b6d-f6f72c72fe92
> UIEH-1397: The list of packages is no longer cut off in the modal window.

- CHANGELOG.md
- src/components/settings/settings-assigned-users/settings-assigned-users.js
- src/components/settings/settings-assigned-users/settings-assigned-users.test.js
- src/routes/settings-assigned-users-route/settings-assigned-users-route.js
- src/routes/settings-usage-consolidation-route.js
- translations/ui-eholdings/en.json
Improve HTML page titles for Assigned Users and Usage Consolidation Settings pages.
https://github.com/folio-org/ui-eholdings/assets/19309423/df0c5a95-a7a2-4742-826d-b1a392dacf65
[UIEH-1387](https://issues.folio.org/browse/UIEH-1387)
> UIEH-1387 Improve HTML page titles for Assigned Users and Usage Consolidation Settings pages.

- src/components/details-view/details-view.js
- src/components/package/show/package-show.test.js
Follow-up PR. Fix tests.
[UIEH-1408](https://folio-org.atlassian.net/browse/UIEH-1408)
> UIEH-1408: Fix tests.

- package.json
> Missing dependency, which causing snapshot auto build fail

- CHANGELOG.md
- package.json
> Release v9.1.1

- CHANGELOG.md
- src/features/agreements-accordion/agreements-accordion.js
- src/features/agreements-accordion/agreements-accordion.test.js
Open a new tab by clicking the `New` button of agreements accordion.
Add `target='_blank'` to the `New` button of agreements accordion.
[UIEH-1446](https://folio-org.atlassian.net/browse/UIEH-1446)
https://github.com/user-attachments/assets/745e1a6b-4ee2-45fc-b928-c6ecc7758556
> UIEH-1446: Add `target='_blank'` to the `New` button of agreements accordion.

- CHANGELOG.md
- package.json
update stripes deps and react-intl for sunflower
[UIEH-1454](https://folio-org.atlassian.net/browse/UIEH-1454)
[UIEH-1453](https://folio-org.atlassian.net/browse/UIEH-1453)
> update stripes deps and react-intl for sunflower

- CHANGELOG.md
- src/components/contributors-list.js
- src/components/coverage-date-list/coverage-date-list.js
- src/components/details-view-section/details-view-section.js
- src/components/facet-option-formatter/FacetOptionFormatter.js
- src/components/identifiers-list.js
- src/components/list/list.js
- src/components/navigation-modal/navigation-modal.js
- src/components/package/edit/components/edit-coverage-settings/edit-coverage-settings.js
- src/components/package/edit/components/edit-package-settings/edit-package-settings.js
- src/components/package/show/components/holding-status/holding-status.js
- src/components/provider-list-item/provider-list-item.js
- src/components/query-search-list/query-search-list.js
- src/components/resource/_fields/visibility/visibility-field.js
- src/components/resource/components/edit/holding-status/edit-holding-status.js
- src/components/resource/components/edit/resource-settings/edit-resource-settings.js
- src/components/search-form/components/access-types-filter-accordion/access-types-filter-accordion.js
- src/components/search-form/components/tags-filter-accordion/tags-filter-accordion.js
- src/components/search-form/search-filters.js
- src/components/search-package-list-item/search-package-list-item.js
- src/components/search-paneset/search-paneset.js
- src/components/selected-label/selected-label.js
- src/components/selection-modal/selection-modal.js
- src/components/settings/settings-knowledge-base/settings-knowledge-base.js
- src/components/show-hide-password-field/show-hide-password-field.js
- src/components/title/_fields/package-select/package-select-field.js
- src/features/export-package-resources-modal/export-package-resources-modal.js
- src/features/usage-consolidation-accordion/summary-table/summary-table.js
- src/features/usage-consolidation-accordion/usage-consolidation-accordion/usage-consolidation-accordion.js
- src/routes/settings-access-status-types-route/settings-access-status-types-route.js
React v19: refactor away from default props for functional components
[UIEH-1421](https://folio-org.atlassian.net/browse/UIEH-1421)
> UIEH-1421 React v19: refactor away from default props for functional components

- CHANGELOG.md
> Release v11.0.0

- CHANGELOG.md
- package.json
- src/components/package/show/components/PackageTitleList/PackageTitleList.css
- src/components/package/show/components/PackageTitleList/PackageTitleList.js
- src/components/package/show/components/PackageTitleList/PackageTitleList.test.js
- translations/ui-eholdings/en.json
Package Record - Titlelist Display - Add Column for Tags and few column width adjustments.
[UIEH-1449](https://folio-org.atlassian.net/browse/UIEH-1449)
> UIEH-1449 Package Record - Titlelist Display - Add Column for Tags and few column width adjustments.

- CHANGELOG.md
- src/components/search-section/search-section.js
- src/components/search-section/search-section.test.js
Retain the selected search option in the titles search.
https://folio-org.atlassian.net/browse/UIEH-1462
https://github.com/user-attachments/assets/377ee8c0-5c44-4b04-80ab-f5766bf5932d
> UIEH-1462: SearchSection - update the value of Select to match state variable.

- CHANGELOG.md
https://folio-org.atlassian.net/browse/UIEH-1467
> Release v11.0.1
