.travis.yml
This entry in the .travis.yml file forwards a verbose payload of information
to our lita travis handler for all travis ci notifications.  Since Travis
does not provide a way to filter notifications by branch in the .travis.yml
file, we will do the filtering and formatting in the lita handler.
DO NOT MERGE until https://github.com/thefrontside/Bitbot/pull/5 is merged.
=> Configure TravisCI to send notifications to BitBot

mirage/index.js, mirage/start.js, src/index.js
In order to demo and also to build out funcitonality with the server being incomplete and not fully defined, it's best to have mirage going everywhere.
=> Enable mirage in production.

mirage/start.js
Mirage ships with its own camelize() function which it uses for model names, etc... This change uses that one instead of depending on lodash.
=> Use `camelize` function from mirage.

.npmrc, .travis.yml
Previously a fresh checkout of this repo required running `yarn config set @folio:registry https://repository.folio.org/repository/npm-folio/` before running `yarn install`.
Now that step of registering the `@folio` registry will be automatically taken care of.
=> Store scoped registry info in .npmrc

mirage/config.js, mirage/factories/package.js, mirage/factories/vendor.js, src/components/package-show/index.js, src/components/package-show/package-show.js, src/index.js, src/routes/package/package-show.js, tests/harness.js, tests/package-show-test.js, tests/pages/package-show.js, tests/pages/vendor-details.js
**Package Details (Show - Metadata)**
This is the 'show' page for a package, or more specifically a 'vendor package', since there is no API for package as-of-yet.
Currently this only displays a subset of read-only metadata for the package, as well as a link back to the parent vendor.  It makes use of `stripes-components` for some styling, but could probably use a better layout.
As for the list view that should accompany this page, I'm unsure if it should be titles or a list of other vendors providing the package.  I'm pretty sure the former, but if there is no pure "package details" page due to the RM API restriction, then I'm not sure where the latter would go.  We could put both here?
=> Package Details Page

src/components/app.js, tests/app-test.js
Updates the previously-built vendor search to reflect accurate serialization.
While I was at it, I wrapped it in a `<Pane>` and linked to the vendor detail pages from the search results.
=> Put back vendor search

mirage/config.js, package.json, src/components/app.js, src/components/customer-resource-show/customer-resource-show.js, src/components/package-show/package-show.js, src/components/vendor-show/vendor-show.js, src/index.js, src/routes/customer-resource/customer-resource-show.js, src/routes/package/package-show.js, src/routes/vendor/vendor-show.js, tests/app-test.js, tests/customer-resource-show-test.js, tests/harness.js, tests/package-show-test.js, tests/pages/app.js, tests/vendor-show-test.js
- The key in the manifest represents a piece of state in the redux store (that gets created when the manifest is processed).
- That piece of the state seems to be overwritten with subsequent calls.
- Because of this, connected component's manifests should have keys unique to their representation of the data.
- The back button doesn't trigger another request, and so when these keys are not unique, data from `packages` within a vendor would actually be previous `packages` data from our origin page.
I've skipped the error tests for now because they will have to be reworked to align with stripes-connect.
-  A manifest can include an `@errorHandler` key whose value is a function called with a stripes error object. [[docs]](https://github.com/folio-org/stripes-connect/blob/master/doc/api.md#erro …
=> Integrate with stripes-connect

demo/front.js, mirage/scenarios/default.js
Makes the demo vendor and package data setup work again, with far fewer titles being created.
=> Restore demo mirage data

demo/stripes.config.js, mirage/index.js, mirage/serializers/application.js, package.json, src/index.js, src/routes/customer-resource/customer-resource-show.js, src/routes/package/package-show.js, src/routes/search/search-vendors.js, src/routes/title/title-show.js, src/routes/vendor/vendor-show.js
This PR points ui-eholdings towards `okapi.frontside.io` and turns off mirage when running in production.  Mirage serializer was updated to reflect recent changes in RM-API.
For now, required query params are hardcoded for demo purposes.
=> Talk to Okapi

mirage/config.js, src/index.js, src/routes/search/search-packages.js, src/routes/search/search-titles.js, src/routes/search/search-vendors.js
Thought maybe we could get packages and titles searches out before the demo.
**Lacking Tests** for the two new search pages. But since the vendor search tests are mostly skipped right now, I didn't think it would be too big of a deal.
These search pages should be refactored anyway. We will definitely write tests during that.
=> Crude Searches

mirage/factories/package.js, src/components/customer-resource-show.js, src/components/key-value-label/index.js, src/components/key-value-label/key-value-label.css, src/components/key-value-label/key-value-label.js, src/components/package-show/package-show.js, src/components/title-show/title-show.js, src/components/vendor-show/vendor-show.js, tests/customer-resource-show-test.js, tests/package-show-test.js, tests/title-show-test.js, tests/vendor-show-test.js
The new `KeyValueLabel` component mimics stripes' `KeyValue`, but allows passing in an entire node instead of just a string. This enabled much clearer relationship hierarchy on detail pages and better testing through data attributes.
=> Introduce KeyValueLabel component

demo/stripes.config.js
https://okapi.frontside.io is now working with the correct certificate, so the last piece of the puzzle is to point https://folio.frontside.io at that location.
=> Point ui-eholdings to https://okapi.frontside.io

mirage/config.js, package.json, tests/harness.js, tests/stripes.config.js
Brings in https://github.com/folio-org/stripes-core/pull/27 and https://github.com/folio-org/stripes-core/pull/33; keeps locked into the Frontside fork for now. We'll switch to upstream master with the next release tag.
=> Upgrade stripes-core

mirage/factories/custom-coverage.js, mirage/factories/package.js, mirage/factories/visibility-data.js, mirage/models/custom-coverage.js, mirage/models/package.js, mirage/models/visibility-data.js, mirage/serializers/package.js, src/components/package-show/package-show.js, tests/package-show-custom-coverage-test.js, tests/package-show-visibility-test.js, tests/pages/package-show.js
Required a lot of custom serialization on the mirage side for packages, since `visibilityData`and `customCoverage` are essentially records embedded within a package.
=> Add custom coverage and hidden metadata to packages

demo/stripes.config.js, mirage/config.js, mirage/factories/customer-resource.js, mirage/serializers/application.js, mirage/serializers/customer-resource.js, mirage/serializers/package.js, mirage/serializers/title.js, src/components/customer-resource-show.js, src/routes/search/search-packages.js, src/routes/search/search-titles.js, src/routes/search/search-vendors.js, tests/customer-resource-show-test.js, tests/package-search-test.js, tests/pages/customer-resource-show.js, tests/pages/search-packages.js, tests/pages/search-titles.js, tests/title-search-test.js, tests/title-show-test.js, tests/vendor-search-test.js
It took a lot of mirage serialization refactoring to set up future `customerResource` embedded records that will needed for embargo/coverage data.
I added package and title search tests to aid in the refactoring.
Alternatives I explored with the mirage serializers:
- [_hashForModel()](https://github.com/samselikoff/ember-cli-mirage/blob/d93713e90957a62b40507d1fb988dba4d929a18e/addon/serializer.js#L208l) - it's "private" and I was running into circular problems with titles / customer-resources
- every model's serializer implements its own `serialize()` - there ended up being too much duplicated logic that could be abstracted up to the `ApplicationSerializer`
I ultimately chose to introduce the `modifyKeys()` pattern instead.
=> Show package title content type

demo/front.js
We don't need the HTTPS workaround instructions anymore.
=> Edit demo front page

mirage/factories/title.js, src/components/customer-resource-show.js, src/components/title-show/title-show.js, tests/customer-resource-show-test.js, tests/pages/customer-resource-show.js, tests/pages/title-show.js, tests/title-show-test.js
New additions:
- show publisher name and type, managed url on package-title detail
- show publisher type on title detail
=> Add pubType to titles

demo/front.js
Old title ID does not exist. This corrects the title ID based on a title search for the same name
=> Fix url for demo title link

mirage/config.js, mirage/models/title.js, package.json, src/components/customer-resource-show.js, src/index.js, src/routes/customer-resource/customer-resource-show.js, tests/customer-resource-show-test.js, tests/harness.js, tests/helpers.js, tests/pages/customer-resource-show.js
One of the primary use-cases for the e-holdings application is for
digital resource librarians to manage their holdings. To do this they
need the ability to mark a title as being part of their
holdings (toggling it on and off);
This work, along with recent changes to stripes-core, leverages the
concept of 'epics' from 'redux-observable' to ensure async actions
resolve sanely.
=> Select / deselect package titles (customer resources)

mirage/factories/customer-resource.js, mirage/factories/identifier.js, mirage/factories/title.js, mirage/models/identifier.js, mirage/models/title.js, mirage/serializers/application.js, mirage/serializers/title.js, src/components/customer-resource-show.js, src/components/identifiers-list.js, src/components/title-show/title-show.js, tests/pages/title-show.js, tests/title-show-test.js
Adds identifiers (ISSN, ISBN, etc.) to title and package-title detail views.
Implemented following guidelines here: https://issues.folio.org/browse/UIEH-30
=> Show identifiers for titles

tests/customer-resource-show-test.js, tests/pages/customer-resource-show.js
We were seeing flakiness around the tests related to selecting/deselcting packages.
These enhancements ensure the existence of an element to be clicked before performing the click.
We also temporarily increase the mirage server timing to account for requests completing before the convergent `it` gets a chance to assert anything about in-flight requests.
=> Ensure reliable click events in customer resource test

src/components/customer-resource-show.js, src/redux/customer-resource.js, src/redux/index.js, src/routes/customer-resource/customer-resource-show.js
This pulls the original reducer and epics out into their own "duck" file to be used with the `eholdings` root reducer / epic, and splits the customer resource model's state into `record` and `toggle` pieces to reflect the two different operations.
This is related to stripping `stripes-connect` from the app, as all other routes will have their own reducers and epics defined in the `redux` directory as well.
=> Refactor customer resource show route 🦆

mirage/factories/package.js, src/components/package-show.js, src/index.js, tests/package-show-custom-coverage-test.js
Replaces https://github.com/thefrontside/ui-eholdings/pull/47
Stripes provides `intl`, so I made it available to our app via context. We don't have to know what the stripes `locale` is with this setup.
`formatISODateWithoutTime()` should be pulled out of the `PackageShow` component when it's needed in the `CustomerResourceShow` component.
=> Format dates with react-intl

.eslintrc.js, .travis.yml, demo/stripes.js, package.json, src/components/customer-resource-show.js, src/components/list/list.js, src/components/vendor-show.js, src/index.js, src/redux/customer-resource.js, src/redux/search.js, src/routes/customer-resource/customer-resource-show.js, src/routes/package/package-search-results.js, src/routes/package/package-show.js, src/routes/search.js, src/routes/title/title-search-results.js, src/routes/title/title-show.js, src/routes/vendor/vendor-search-results.js, src/routes/vendor/vendor-show.js
When running the dev server, ESLint will emit errors:
`yarn test` will not run `ESLint` assertions, but `yarn lint` will.
Travis CI builds will fail with ESLint errors: https://travis-ci.org/thefrontside/ui-eholdings/builds/274360479
Only pays attention to the `src` directory for now. We should gradually transition over to using the same ruleset as `stripes-core`.
=> Enforce ESLint rules

src/redux/search.js, src/routes/package/package-search-results.js, src/routes/title/title-search-results.js, src/routes/vendor/vendor-search-results.js
Renamed the following search state properties and added `isResolved`
```
isLoading -> isPending
isErrored -> isRejected
records -> content
```
=> Refactor search state to use promise-like booleans

mirage/factories/customer-resource.js, mirage/factories/embargo-period.js, mirage/models/customer-resource.js, mirage/models/embargo-period.js, mirage/serializers/customer-resource.js, src/components/customer-resource-show.js, tests/customer-resource-show-embargo-test.js, tests/pages/customer-resource-show.js
Does not include any business logic around when they should be shown. It's simply: if the RM API returns a custom or managed embargo period, show them. If not, nothing is rendered out.
=> Show embargo periods for customer resources

demo/stripes.js
ESLint validation problems will now just warn to the console, instead of throwing an error in an overlay in the browser.
=> Make eslint-loader quieter

README.md, demo/stripes.js
Up until this point, we've been using Mirage as the default backend for running our development server. This has served us well as we built up the API, but nowadays, we will go large spans of time where we aren't changing the backend at all, but only the UI that is built on top of it.
It makes sense then to make running against the (somewhat) stable backend as the default. However, if you want to enable Mirage then you can do so by setting the `MIRAGE` environment variable
=> Opt in to Mirage.

src/index.js, src/router.js
In order to have a single manifest of routes at the top of our route hiearchy, we need the ability to nest route components into other route components. However, this requires using a closure in the `render` property with vanilla React Router v4.
This becomes unwieldy once you have have routes nested within other routes, especially when you want to have a single, application route sitting at the top of your routes so that your entire routing structure sits inside a closure (ick!)
This re-maps the children of a route over to the component that the route is rendering, letting us keep our routes nice and flat, and using simple JSX without closure properties.
=> Make routes nestable.

src/components/search-form/search-form.css, src/components/search-form/search-form.js
Imports some sass variables from `stripes-core`.
Long-term: should use some `stripes-components` instead of implementing our own.
=> Use styles that are closer to stripes defaults

src/components/customer-resource-show.js, src/components/identifiers-list.js, src/components/package-show.js
Solves two problems shown in the screenshot below:
- Don't show content type if it's not returned from RM API.
- If a type or subtype of an identifier is outside of the bounds of what we know, call it an "Unknown Identifier." We were being returned ids not defined in the RM API docs https://developer.ebsco.com/rmapireference#identifier. It would be much better to receive the string describing the identifier from the RM API, instead of having to manually map ids.
=> Fix some package / package-title attribute displays

src/components/contributors-list.js, tests/title-show-test.js
Authors appear to come back as `Last Name, First Name`, so separating them with a comma like `Melville, Herman, Parker, Philip M.` is ineffective.
Switched to a semicolon.
=> Separate contributors with semi-colon

src/components/identifiers-list.js, tests/title-show-test.js
We only want to see these identifiers.
Subtype | Type | UI Display Label
-- | -- | --
Print = 1 | ISSN = 0 | ISSN (Print)
Print = 1 | ISBN = 1 | ISBN (Print)
Online= 2 | ISSN = 0 | ISSN (Online)
Online = 2 | ISBN = 1 | ISBN (Online)
(I'm also showing ISSN and ISBN with subtype 0.)
=> Ignore identifiers that aren’t ISSN or ISBN

tests/customer-resource-show-embargo-test.js, tests/it-will.js, tests/package-show-custom-coverage-test.js
This fixes tests similar to this: 
```js
it('does not display some thing', function() {
expect(PageObject.someValue).to.equal('');
});
```
With convergent assertions, these will still pass because `someValue` hasn't had a chance to update to the side effects from `beforeEach` (i.e. loading a record).
To see this, simply move one of these negation tests to someplace it should fail, and **it will still pass**.
We could assert that a record has been loaded before our assertions are run, however sometimes the DOM may be milliseconds behind in rendering and the convergent assertion will still pass.
Instead we should use `it.still` which assures that the assertion is true for a given amount of time:
```js
it.still('does not display some thing', function() { …
```
=> Fix convergent negation test

mirage/config.js
Previously, stripes-connect required `response.url` to be present on the response. The fetch polyfill used with mirage does not set this property unless the response headers include `X-Request-URL`.
Now that stripes-connect usage has been removed from our app, it is safe to clean up these extraneous headers from the config.
=> Clean up mirage headers

package.json, src/components/list/list.css, src/components/results-pane/index.js, src/components/results-pane/results-pane.css, src/components/results-pane/results-pane.js, src/components/search-form/search-form.css, src/components/search-form/search-form.js, src/components/search-pane-vignette/index.js, src/components/search-pane-vignette/search-pane-vignette.css, src/components/search-pane-vignette/search-pane-vignette.js, src/components/search-pane/index.js, src/components/search-pane/search-pane.css, src/components/search-pane/search-pane.js, src/components/search-paneset/index.js, src/components/search-paneset/search-paneset.css, src/components/search-paneset/search-paneset.js, src/redux/request.js, src/redux/search.js, src/routes/search.js
Now responsive with two panes. In the middle range the search pane will pop out with a vignette behind it.
Biggest size:
Middle size:
Smallest size:
=> Rework search layout

demo/front.css
Making sure the nav bar is visible and having contained apps scroll underneath it seems like it should be part of `stripes-core`. However there is currently no such enforcements in place (as there is no comprehensive responsive styles in most of stripes).
App's typically use `Pane` and `Paneset` components to render their content, and these components _do_ take the header height into account in their styling. However, our `front` component does not use a `Pane`, and so we need to ensure that the header height is taking into account ourselves.
=> Fix frontpage mobile styles

src/components/search-pane-vignette/search-pane-vignette.css
If the browser window was resized, the search pane vignette (the partially transparent background between the search form and the results) was still showing up. It should never appear above the largest breakpoint.
=> Hide search pane vignette at large sizes

demo/stripes.js, package.json, yarn.lock
Uses `stripes-core` fork branch to appropriately build css for production.
This will basically be a test deploy. If successful, I'll be opening a PR on `stripes-core` upstream to match the changes on the fork, then opening another PR here to go back to `stripes-core` master later.
Related to https://issues.folio.org/browse/UIEH-88
=> Change webpack config for css

demo/stripes.config.js, mirage/config.js
`disableAuth` is no longer available as a `stripes` config option.
This creates the endpoints needed for `mirage` to mock a login against an actual Okapi instance.
There's an `autoLogin` option in `stripes` configs that we should explore: https://github.com/folio-org/stripes-core/blob/a0ed2792a3cfc497191aa769258c921e1015bbd8/src/components/Login/LoginCtrl.js#L34
In my quick try of it, the login screen would confusingly appear before the session authenticated, which I found pretty not great. There should be a loading animation instead that prevents the login screen from ever appearing if `autoLogin` is set.
=> Adjust to Okapi now needing login

src/redux/request.js
Currently, any request we make from the UI does not include our user's token. So the server complains about permissions or missing tokens with any request. This adds that token to the request headers that are created using the request epic.
Adds the Okapi token to request headers
Also change Content-Type to be JSON API compliant
=> Add Okapi token to request headers

src/components/search-form/search-form.js, src/components/search-paneset/search-paneset.js, src/routes/search.js, tests/package-search-test.js, tests/pages/package-search.js, tests/pages/title-search.js, tests/pages/vendor-search.js, tests/title-search-test.js, tests/vendor-search-test.js
Previously, in a narrow view when switching search types, it would trigger the search pane to close due to the presence of a new `search` query in the URL. Additionally, this trigger caused a new search to be made with the old query but within a different search type.
Now in both `componentWillReceiveProps` hooks, we check if we are using the same search type as before, before creating a new search or closing the open search pane.
A few tests were also added to make sure switching between search types keeps the old results when switching back (and doesn't actually cause a new query in a different search type context).
=> Fix triggering a search when switching search types

demo/boot-mirage.js, demo/stripes.js, mirage/config.js, mirage/scenarios/default.js, mirage/scenarios/load-error-backend.js, mirage/scenarios/no-backend.js, mirage/scenarios/unconfigured-backend.js, mirage/start.js, package.json, src/components/error-screen/error-screen.css, src/components/error-screen/failed-backend.js, src/components/error-screen/invalid-backend.js, src/components/error-screen/no-backend.js, src/components/search-form/search-form.css, src/components/settings/index.js, src/components/settings/settings.css, src/components/settings/settings.js, src/index.js, src/redux/application.js, src/redux/index.js, src/routes/application.js, src/routes/settings.js, tests/backend-configuration-test.js, tests/harness.js, tests/helpers.js, tests/pages/application.js, tests/pages/helpers.js, tests/pages/settings.js, yarn.lock
As it stood, the value for the RMAPI customer ID and API key were per
deployment. Now however, it can be configured via the
/eholdings/configuration endpoint so that each tenant can maintain
their own set of credentials. We needed a way to detect if the
eholdings app is usable, and if its backend is configured
correctly, and also to be able to change credentials.
This change checks on every eholdings application entry to see if
infact there _is_ a  backend for eholdings and gives you instruction
on how to download it. If there is a backend, it will ensure that it
is configured properly, and if not, it will direct the user to a new
settings screen with which a tenant admin can view the current
configuration and make changes where necessary.
In order to support development against server …
=> View and set backend settings

mirage/factories/package.js, mirage/scenarios/default.js, src/redux/customer-resource.js, src/redux/package.js, src/redux/utilities.js, tests/customer-resource-show-test.js, tests/package-show-custom-coverage-test.js, tests/package-show-test.js, tests/package-show-visibility-test.js
We want to show prettily-formatted content types instead of exactly what the RM API returned.
https://issues.folio.org/browse/UIEH-86
In the `package` and `customer-resource` reducers, transform the `contentType` when deserializing the server response.
We probably want to do this serialization step in `mod-kb-ebsco` instead of in the front-end, because the mappings will change for every knowledge base.
=> Display friendly formatted content type

src/redux/customer-resource.js, src/redux/package.js, src/redux/utilities.js, tests/customer-resource-show-test.js
Sometimes a customer resource / package-title will come back from the RM API without a `contentType`. The implementation in https://github.com/thefrontside/ui-eholdings/pull/96 ignored that case, and we would get this error:
Put in some checks against a blank or missing `contentType` for both packages and customer resources.
=> Bulletproof against missing contentType

src/routes/search.js
When you click a link that is missing the `searchType` parameter when the parameter was previously present, the search UI should disappear. It doesn't.
When there is no `searchType` found during `componentDidReceiveProps`, still set the state to remove the existing search type
=> Remove search type from search route state when the param is removed

mirage/config.js, src/components/package-show.js, src/redux/package.js, src/routes/package-show.js, tests/package-show-test.js, tests/pages/package-show.js
[UIEH-51](https://issues.folio.org/projects/UIEH/issues/UIEH-51) - Add/Remove package to/from holdings
Copied the approach from toggling a customer resource (package-title):
- New request reducer for sending the `PUT` request to the package endpoint
- Existing package reducer now handles the response from the `PUT` request
- The toggle switch component was used in place of the "Yes"/"No" display for packages
- New tests were pretty much copy+pasted and altered from the customer resource tests
To support the titles and selected title count being updated, two additional measures are taken.
- Reload the package titles list once the toggle request has resolved
- Update the selected title count to show all or no titles are selected depending on the package's selected state
- Requests are …
=> Implement toggling a package's selected state

src/redux/request.js, yarn.lock
The action$ in our epic inherits the Observable created in stripes-core. Any operators chained from this action$ must be defined in stripes-core. However when we create our own Observable using `from` or `of` we need to add the operators we expect to use in our own app
- Removes `switchMap` as that is now defined in `stripes-core`
- Adds `map` since we need it when we use `Observable.from(request)`
=> Add map operator for Observable

mirage/config.js, mirage/factories/vendor.js, mirage/serializers/application.js, mirage/serializers/package.js, mirage/serializers/vendor.js, src/components/vendor-list-item.js, src/components/vendor-search-results.js, src/components/vendor-show.js, src/redux/request.js, src/redux/search.js, src/redux/utilities.js, src/redux/vendor.js, tests/customer-resource-show-test.js, tests/package-show-custom-coverage-test.js, tests/package-show-test.js, tests/package-show-visibility-test.js, tests/pages/vendor-search.js, tests/pages/vendor-show.js, tests/vendor-search-test.js, tests/vendor-show-test.js
The `/eholdings/vendors` and `/eholdings/vendors/:id` endpoints are now available as JSON API documents at `/eholdings/jsonapi/vendors` and `/eholdings/jsonapi/vendors/:id`.
There's a new mirage serializer only for vendors that extends `JSONAPISerializer`, but not the `ApplicationSerializer`.
=> Switch to new JSON API vendor endpoints

src/components/customer-resource-show/customer-resource-show.js, tests/customer-resource-show-coverage-test.js
Correct display issue found after release of Managed Coverage Dates on Title Package Display. Specifically a lone 0 appears below manage url in cases where a record has an empty managedCoverageList.
Consistent with checks for other lists (such as subject list) 
Even though length of ManagedCoverageList of 0 is falsey - because of the context of where it is used in - the JSX it results in the display of 0 in ui (as in below screenshot)
and below image shows the offending element in DOM
=> Correct manageCoverageList length check > 0 - avoid incorrect display of 0 length in ui

demo/stripes.js, mirage/config.js, yarn.lock
`stripes.build()` and `stripes.serve()` now return promises.
Because this upgrades `stripes-core`:
- Removes bootstrap global CSS; Source Sans Pro now default font
- `mod-notify` is now being used by `stripes-core`
=> Adjust to stripes.build promise

demo/stripes.config.js
Our sandbox Okapi cluster now points to sandbox RM API.
Our production Okapi cluster now points to production RM API.
With this PR, running `yarn start` or `yarn build` will point to the sandbox cluster, and `environment=production yarn build` (which Travis runs) will point to the production cluster.
=> Point to sandbox okapi cluster by default

src/components/customer-resource-show/customer-resource-show.js
"Managed URL" links are external, but we were treating them as internal and routing them through our application's router.  This changes the "Managed URL" to behave more like a normal link and take us out of the application.
=> Don't route Managed URL through React router

mirage/factories/vendor.js, tests/helpers.js, tests/package-search-test.js, tests/pages/package-search.js, tests/pages/title-search.js, tests/pages/vendor-search.js, tests/title-search-test.js, tests/vendor-search-test.js
PR #99 got merged a little quick before @cowboyd got his review in. We need to test the functionality of that PR to ensure no regressions happen in the future.
- Adds a `goBack` helper which navigates backwards through our apps router history using the `TestHarness`'s `history` property.
- Creates additional mirage data during tests to click deeply inside of the preview pane on the various search routes.
- Tests that clicking deeply hides the search UI and navigating back shows it again.
=> Add tests for search type removal

package.json, tests/harness.js, yarn.lock
This feels a little gross, but it gets us the latest `stripes-components` without a new release of it.
I pointed the `stripes-components-fork-master` branch of `thefrontside/stripes-core` to `master` of `thefrontside/stripes-components` (instead of the versioned release).
=> Use newer stripes-core and stripes-components

mirage/config.js
Mirage spat out a bunch of unhandled route errors when requesting `/notify`. I thought the endpoint might have just changed from `/notify/_self`, but apparently there are two requests for notify that return the same payload at these two endpoints.
Adds a second `/notify` endpoint that returns the same payload as `/notify/_self`
- _Why?_
=> Add other notify endpoint to mirage

.stylelintrc.js, package.json, src/components/key-value-label/key-value-label.css, src/components/preview-pane/preview-pane.css, src/components/search-form/search-form.css, src/components/search-pane-vignette/search-pane-vignette.css, src/components/search-pane/search-pane.css, src/components/search-paneset/search-paneset.css, src/components/settings/settings.css, src/components/toggle-switch/toggle-switch.css, yarn.lock
CSS conventions should be just as consistent as our JS conventions, so let's lint it. https://github.com/stylelint/stylelint
This sets up `.stylelintrc` for the repo and fixes the results of running `stylelint "src/**/*.css"`.
I installed a plugin in my editor (https://github.com/stylelint/stylelint/blob/master/docs/user-guide/complementary-tools.md#editor-plugins) to help stick to conventions in realtime.
- Make `stylelint` a part of the CI pipeline.
- Make `stylelint` violations show up with a webpack dev server.
- Make this setup a first-class citizen for the FOLIO ecosystem with `eslint-config-stripes`.
Sample console output
=> Set up stylelintrc

.gitignore, src/components/customer-resource-show/customer-resource-show.js, src/components/link.js, src/components/package-list-item.js, src/components/package-show/package-show.js, src/components/title-list-item.js, src/components/title-show/title-show.js, src/components/vendor-list-item.js, src/components/vendor-show/vendor-show.js, tests/customer-resource-show-test.js, tests/package-search-test.js, tests/package-show-test.js, tests/pages/customer-resource-show.js, tests/pages/package-search.js, tests/pages/package-show.js, tests/pages/title-search.js, tests/pages/title-show.js, tests/pages/vendor-search.js, tests/pages/vendor-show.js, tests/title-search-test.js, tests/title-show-test.js, tests/vendor-search-test.js, tests/vendor-show-test.js
Users need a way to step out / exit areas of the application and get back to another section as they navigate through the application. It is true that we have the back button in the web browser that will give user this functionality for free. However, as we have a response layout and user can be on varying devices the use of the native-button may not be a option. In addition having a back-button within the UI may feel more intuitive as Users are accustomed to clicking a `X` button to close things, `hamburger` icon to open hidden trays etc.
Add a back button to:
* Package-details.
* Vendor-package-title aka customer-resource.
* Vendor-details.
* Title-details.
Create a `<Link />` Component that is used to track if a users location originated from within `eholdings`. That will allow us to …
=> Add Back button in eholdings UI

.travis.yml, karma.conf.js, package.json, yarn.lock
There was a bug in our date handling code that caused the application to bug-out on Safari. This didn't get caught by our test suite because we never actually run our series of automated tests on Safari.
This adds safari testing to our CI with BrowserStack (https://browserstack.com) by using the Karma browser stack launcher.
The travis build is split into two jobs: one for our standard Chrome running on the travis container, and the other running Safari on BrowserStack.
=> Add Safari build to CI test run

src/components/package-show/package-show.js, src/components/title-show/title-show.js, src/components/vendor-show/vendor-show.js, tests/package-search-test.js, tests/pages/package-search.js, tests/pages/title-search.js, tests/pages/vendor-search.js, tests/title-search-test.js, tests/vendor-search-test.js
Back button should not show if there is a queryString meaning that there was a search performed. There is already an exit button. The back-button is redundant and not useful in this context. A User in this context would just want to "close" this search detail pane completely and not step back.
Prior we were using a queryString value that seemed to be only passed in through props on a Vendor and not Package or Title. So on a Package or Title search detail pane there would be a "X" and "<-" rendered in the UI.
- Check the router to see if a search property exist.
=> Show back button only if there is no query string

demo/front.css, karma.conf.js, package.json, yarn.lock
Context of why we want to upgrade here: https://github.com/thefrontside/ui-eholdings/pull/126
There's a new reset stylesheet in `stripes-components`, along with CSS updates for buttons, etc.
- The front component styles needed a few updates to look ok again.
- Search result lists look a little different, but I didn't make any changes there yet.
=> Upgrade to latest stripes-core and stripes-components

src/components/customer-resource-show/customer-resource-show.css, src/components/list/list.css, src/components/package-show/package-show.css, src/components/search-form/search-form.css, src/components/title-show/title-show.css, src/components/vendor-show/vendor-show.css
`stripes-components` now has a reset stylesheet. The biggest side effect was that we lost a lot of spacing.
I also bumped up some headline sizes/weights and tweaked the style of the search form's segmented control.
=> Adjust some CSS post-reset

package.json
From @MikeTaylor:
This is necessary for Stripes to display the icon of the eholdings application in its top bar and to enable the route `eholdings`.
=> Add permissionSets to package.json

src/redux/application.js, src/redux/package.js, src/redux/title.js, src/redux/vendor.js
When uglified, the production build does not include class names for these models. So when the model helper tries to infer a model type from the class name, they all become "es".
Explicitly set a type for each model so that the class name does not matter
- Should the production build be losing class names? Is this a setting we have control over in stripes?
**Production Model Names**
**Development Model Names**
=> Explicitly declare model types

src/components/search-paneset/search-paneset.css, src/components/search-paneset/search-paneset.js, src/routes/search.js, tests/package-search-test.js, tests/pages/package-search.js, tests/pages/title-search.js, tests/pages/vendor-search.js, tests/title-search-test.js, tests/vendor-search-test.js
Show the search results total for vendors, packages, and titles
Copies how the total number is displayed for ui-users (under the results pane header).
=> Show Search Results Total

mirage/config.js, src/redux/customer-resource.js, src/redux/package.js, src/redux/title.js, src/redux/vendor.js, tests/customer-resource-show-test.js, tests/package-search-test.js, tests/package-show-test.js, tests/title-search-test.js, tests/vendor-search-test.js, tests/vendor-show-test.js
Now that we're exclusively using the new `mod-kb-ebsco` JSON API endpoints, we no longer need them sandboxed under `/jsonapi/`.
=> Remove /jsonapi namespace

src/components/search-paneset/search-paneset.js
FOLIO apps should internationalize numbers. In my locale, a comma gets added as a thousands separator:
=> Format results number with intl-friendly separators

demo/front.js, demo/stripes.js, package.json, yarn.lock
SVG loading by webpack is now in `stripes-core`.
Mostly includes visual tweaks, including fixing the overabundance of icons on date pickers (@elrickvm 😁 ):
=> Upgrade stripes-core and stripes-components

mirage/config.js, mirage/scenarios/unconfigured-backend.js, src/redux/application.js, src/routes/settings.js
eHoldings settings is broken.
The `configurations` endpoint needs type `configurations` and id `configuration`. It's currently returning type `configuration` and id `rmapi`.
=> Pluralize configuration type

.travis.yml, mirage/config.js, mirage/scenarios/no-backend.js, tests/harness.js, tests/pages/package-search.js, tests/pages/package-show.js, tests/pages/vendor-search.js
The only existing failures were from malformed data attributes selectors (they were missing the closing `]`).
=> Fix Safari errors in Travis

src/components/customer-resource-show/customer-resource-show.js, src/components/key-value-label/key-value-label.css, src/components/package-show/package-show.js, src/components/search-paneset/search-paneset.css, src/components/search-paneset/search-paneset.js, src/components/title-show/title-show.js, src/components/vendor-show/vendor-show.js, tests/pages/customer-resource-show.js, tests/pages/package-search.js, tests/pages/package-show.js, tests/pages/title-search.js, tests/pages/title-show.js, tests/pages/vendor-search.js, tests/pages/vendor-show.js
`stripes-components` has several style updates that were not applied to `ui-eholdings`.
- Pane header actions are using the new `IconButton` for consistent padding.
- Our `KeyValueLabel` component now uses the same styles as the `stripes-components` `KeyValue` component (which doesn't accept blocks as the value, only strings).
- We can now use `paneSub` in `PaneHeader`s for the search results count.
=> Update to current FOLIO styles

src/components/search-paneset/search-paneset.css
`overflow: scroll` causes the scrollbar to always be visible even with no scrollable content. When there is nested scrollable content, this causes a double scrollbar.
This isn't noticable on an OS that hides scrollbars, but viewing on another OS, or setting the scrollbars to always be visible surfaces this issue.
Use `overflow: auto` for the `.scrollable-container` class.
To set scrollbars to be visible on MacOS, go to `System Preferences > General > Show Scrollbars`
*before*
*after*
=> Fix double scrollbars

src/components/modal/index.js, src/components/modal/modal.css, src/components/modal/modal.js, src/components/package-show/package-show.js, tests/package-show-selection-test.js, tests/package-show-test.js, tests/pages/package-show.js
If a user wants to deselect a package, ask them in a confirmation modal whether they actually want to commit that destructive action.
Part of https://issues.folio.org/browse/UIEH-34
The key to making this feature work was keeping the state of the selection toggle independent of the model state. With a toggle component, it would've been strange if you clicked it, the toggle didn't move, but you received a confirmation modal. The UI feels more natural when the toggle always moves with a click/touch, but reverts back if the user decides to cancel the action or the server runs into a problem.
The current `stripes-components` modal was incompatible with `ui-eholdings`. I copy-and-pasted it over and made some necessary modifications. That's not sustainable, but requires more thought and care at …
=> Interrupt package deselection with confirmation modal

src/components/search-paneset/search-paneset.js, src/redux/model.js, src/routes/search.js, tests/package-search-test.js, tests/title-search-test.js, tests/vendor-search-test.js
Display "Loading..." message in place of the total results count when loading search results.
When a collection does not have any loaded records, show the "Loading..." message.
If we used the collection's `isLoading` property, that would return `true` when the requests for the _current page_ in the collection is pending.
The `isLoaded` property (renamed to `hasLoaded`) returns `true` when _any page's_ request for the collection are no longer pending (resolved or rejected).
The previous method for finding the first resolved request in a collection stopped looking for resolved pages after the current page. So if `page=5` is loaded and we view `page=1`, `hasLoaded` would be `false` even though `page=5` has indeed already loaded. 
This method has been updated to keep searching for resolved …
=> Show loading indicator for loading the total results count

src/components/package-list-item/package-list-item.js, src/components/package-show/package-show.js, src/components/vendor-list-item/vendor-list-item.js, src/components/vendor-show/vendor-show.js, tests/package-show-test.js, tests/vendor-show-test.js
Whenever we show a number, we want to make sure it's internationalized. In many cases, this will add thousands-separating commas.
Closes https://issues.folio.org/browse/UIEH-26.
Use `react-intl` provided by Stripes.
=> Internationally format counts

src/components/package-list-item/package-list-item.css, src/components/package-list-item/package-list-item.js, src/components/title-list-item/title-list-item.css, src/components/title-list-item/title-list-item.js, src/components/vendor-list-item/vendor-list-item.css, src/components/vendor-list-item/vendor-list-item.js
Show a loading indicator for individual list-items within the search results list.
Facebook's approach uses a single background with multiple divs clipping away from each visual element to hide parts of the background. This approach uses multiple css backgrounds, one for each skeleton element, and the shimmer effect is created using a psuedo element with some opacity.
- It might be more cross-browser friendly to use multiple divs like facebook (for browsers that do not support multiple backgrounds).
[How the Facebook content placeholder works](https://cloudcannon.com/deconstructions/2014/11/15/facebook-content-placeholder-deconstruction.html)
=> Use skeleton loading css for list-item loading state

src/components/package-list-item/package-list-item.css, src/components/scroll-view/scroll-view.css, src/components/search-paneset/search-paneset.css, src/components/title-list-item/title-list-item.css, src/components/vendor-list-item/vendor-list-item.css
- Scrolling through a list of results should allow momentum scrolling. In iOS Safari, momentum scrolling is reserved for the root document so it is disabled by default on other elements.
- The shimmer skeleton loading effect should be white & transparent. In Webkit browsers, `transparent` is rendered as `rgba(0,0,0,0)` and the transition from white to transparent black produces some gray.
- Set `-webkit-overflow-scrolling: touch` to enable momentum scrolling in scrollable elements.
- Use `color(white a(0))` instead of `transparent` when transitioning from white to transparent.
- Stripes should have this enabled on some of it's components, but none of them are mobile-ready yet anyway.
[-webkit-overflow-scrolling](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling) …
=> Fix iOS scroll-view issues

package.json
Correct dependency mismatches between ui-eholdings and mod-kb-ebsco. 
Update interface name and version (format) mismatches between the two modules. 
Also see PR for mod-kb-ebsco.  https://github.com/folio-org/mod-kb-ebsco/pull/60
=> update 'okapiInterfaces' to 'eholdings'; and two-part interface version

src/components/settings/settings.css, src/components/settings/settings.js, src/routes/application/application.css, src/routes/application/application.js, src/routes/application/index.js
Because the eHoldings settings form was not in a `Pane`, the form was inaccessible on small screens.
Wrapped the form in a `Pane` that has a back button. The back button only appears at small sizes.
=> Wrap settings in Pane for responsiveness

src/components/customer-resource-show/customer-resource-show.js, src/redux/customer-resource.js, src/routes/customer-resource-show.js, tests/customer-resource-deselection-test.js, tests/customer-resource-selection-test.js, tests/pages/customer-resource-show.js
When the final title in a package is deselected, the entire package
itself is also deselected.  This will eliminate all package-level
customization, so we warn the user of this before proceeding.
=> Warn user on deselection of final title in package

mirage/models/customer-resource.js, src/routes/customer-resource-show.js, src/routes/package-show.js, tests/customer-resource-deselection-test.js, tests/package-show-selection-test.js
To be more explicit about RM API's side effects, `mod-kb-ebsco` is very strict about `isSelected`. If you `PUT` a package or package-title to `mod-kb-ebsco` with `isSelected` set to false but `customCoverage(s)`, `visibilityData`, or `customEmbargoPeriod` set, `mod-kb-ebsco` will reject the request.
`ui-eholdings` is not yet doing anything to ensure those values were dismissed,  so attempting to deselect a package or package-title with any customizations fails.
Clear out those customizations in the route when switching `isSelected` to false.
We may want to eventually do all the un-customization handling in the show component instead. Maybe. This solution is simpler at the moment.
=> Clear out model data when deselecting

CONTRIBUTING.md, LICENSE, README.md, package.json
The repository move broke the Travis badge. Same as https://github.com/folio-org/mod-kb-ebsco/pull/62
While I was in there, I updated copyright and license info (FOLIO is on Apache license, not MIT).
=> Update repository url and license info

src/components/package-list-item/package-list-item.css, src/components/title-list-item/title-list-item.css, src/components/vendor-list-item/vendor-list-item.css
Previously, the overflow-y was allowed to be visible due to descenders being cut off. The line-height has since been adjusted and the overflow-y property is causing permanent scrollbars to be visible for these elements. 
Since the line-height is adjusted, we can safely hide the overflow on these elements without cutting off descenders.
=> Hide scrollbars for list-item elements

src/components/customer-resource-show/customer-resource-show.js, src/components/package-show/package-show.js, src/redux/data.js
When saving a change to a package's or customer resource's `isSelected` attribute, we were previously just relying on `model.update.isPending` to determine if the selection toggle should be in a loading state.
That was fine until we started trying to modify model attributes individually. For example, editing custom coverage does not change `isSelected`, and should not trigger a loading state for `isSelected`.
Redux Form expects `onSubmit` to return a promise, but that doesn't jive with our use of observables. Instead, we can shove some extra data in the redux store to know which specific attributes have pending changes.
When saving a model, there will now be a `model.update.changedAttributes` object containing the keys of changed attributes, and an array of the old value and new value for …
=> Track specific attribute changes in redux store

bin/link-self
When ui-eholdings is being brought in as a dependency of a stripes platfom build, and is not the platform itself, the node_modules are flattened out into the module that contains eholdings as a dependency. This means that the `bin/link-self` script fails because it expects node_modules to exist already, but that won't happen until yarn links dependencies from the root directory.
This is a bit of a hack, but we have the `link-self` script check for the availability of the node_modules directory _first_, and only then proceed if it exists.
This is acceptable since the entire `bin/link-self` script will go away completely once UI eholdings can be built on stripes-cli.
=> Don't link self when pulled in as a dependency.

package.json, yarn.lock
With the `folio-org` `stripes-core` and `stripes-components` compatibility with `ui-eholdings` no longer an issue, there's not any reason to point to `thefrontside` forks of those repos anymore.
This updates the header to some shiny new styles.
=> Switch to upstream stripes

package.json
When using ui-eholdings as a dependency, it doesn't install its devDependencies. This isn't a problem when running the CI build because it's installed as the root package so all the dev-dependencies make it in, but when running it as part of a containing stripes platform, it breaks because it doesn't bring in things it needs to build.
This adds:
- inflected
- query-string
as hard dependencies of ui-eholdings so that it will always get pulled into every build of which it is a part.
=> Make `inflected` and `query-string` primary dependencies.

src/routes/customer-resource-show.js, src/routes/package-show.js
We noticed an issue when deselecting customer resources, and traced it
to an issue with embargo values.  Looks like we had a typo in there,
and were clearing out the wrong field during deselection.  This work
adjusts the clear-out logic to use empty objects where possible, in
lieu of nulling out specific data members within those objects.
**Before**
**Typo in Embargo Payload**
**After**
=> Fix a typo while clearing out customizations during deselection

src/redux/model.js, tests/unit/redux-model-test.js
This first surfaced earlier this week while we were investigating a UI hiccup.  The specific manifestation in the UI was a flickering of data being loaded from related resources when navigated to through a search or a parent detail view.  
For instance, our queries on the customer resource page use the `include` param to grab information about the related package so that the record is complete if the user navigates directly to that detail page.  However, through the parent, the data for the package had already been loaded but the relationship to the customer resource isn't realized until the customer resource detail page is loaded.  Since this was our sole linking mechanism, the data layer would lag a bit as it linked the records via `relationship`.  With this change it can link them …
=> Check for foreign key attributes in `belongsTo` relationships

.travis.yml, tests/customer-resource-show-test.js
An eslint warning snuck in because eslint wasn't returning >0 for warnings. Travis therefore didn't pick up that it should report a failure.
ESLint's CLI has a [`--max-warnings`](https://eslint.org/docs/user-guide/command-line-interface#options) option.
I validated that the CI build will now fail: https://travis-ci.org/folio-org/ui-eholdings/builds/331831932
`eslint-loader` has a [`failOnWarning`](https://github.com/MoOx/eslint-loader#failonwarning-default-false) option. That actually stops the bundle from building at all, which is probably too restrictive in a non-CI environment.
We should revisit what ESLint config comes out of the box with `stripes-cli`, and make it sure it's the behavior we want. Related: should we provide boilerplate Travis/Circle CI configs in `stripes-cli`?
=>  Fail Travis build on eslint warnings

demo/stripes.config.js
When spinning up ui-eholdings locally, the default would be to point
at okapi-sandbox.frontside.io unless the environment was explicitly
set to production.  Since okapi-sandbox is not in the automated deploy
pipeline and cannot be relied upon to have the most up-to-date backend
code, it's better to point at our prod instance by default and point
to sandbox only when explicitly told to do so.
=> Point ui-eholdings at okapi.frontside.io by default

yarn.lock
Stripes CLI wasn't exiting with >0 when karma reported errors. https://issues.folio.org/browse/STCLI-17
Fixed in https://github.com/folio-org/stripes-cli/pull/29
Validated with https://travis-ci.org/folio-org/ui-eholdings/builds/332432411
=> Update stripes-cli to fix karma reporting failures

mirage/config.js, mirage/factories/package.js, src/components/package-list-item/package-list-item.js, src/components/package-show/package-show.css, src/components/package-show/package-show.js, src/components/title-list-item/title-list-item.js, src/components/toggle-switch/toggle-switch.css, src/routes/package-show.js, tests/package-show-visibility-test.js, tests/pages/package-show.js, tests/pages/title-search.js, tests/pages/vendor-show.js, tests/vendor-show-test.js
Implement show/hide functionality at the Package Detail level.  This involves
- adding a toggle to package details that represents the isHidden state, toggle behaves as follows:
1. When the toggle is "off", isHidden=true: label is "Hidden from patrons"
2. When the toggle is "on", isHidden=false: label is "Visible to patrons"
- displaying a message to the right of toggle if package is hidden by ep  (message is Set by System - specific message text to be set in mod-kb-ebsco)
- displaying Hidden message in list of customer resources on Package details page
Also updated Vendor Detail page to show Hidden status on list of displayed packages
Updated Hide/Show toggle (disable if Package is Not Selected)
Related Jira Tickets
- https://issues.folio.org/browse/UIEH-116
- …
=> Implement Package Level Hiding UI Changes

.stripesclirc.js
#178 Missed an instance where we need to change the default okapi url
=> Default to okapi.frontside.io in .stripesclirc

src/components/customer-resource-show/customer-resource-show.css, src/components/customer-resource-show/customer-resource-show.js, src/components/toggle-switch/toggle-switch.css, src/routes/customer-resource-show.js, tests/customer-resource-show-visibility-test.js, tests/pages/customer-resource-show.js
- Implement Show/Hide functionality for title-packages
- If the package is hidden or customer resource in a package is not selected, a toggle switch which is read-only and cannot be toggled will appear with a message. 
- Message in above case will be "All titles in this package are hidden." if the package is hidden. If the customer resource within package is not selected, there is no message.
- If a package is not hidden and if a package or customer resource is selected, a toggle switch reflecting current state of the title-package appears with the appropriate message, being 'Set by System' if it is 'Hidden by EP' from RM API or none if it is 'Hidden by Customer' or any other message from RM API
JIRA Tickets: 
https://issues.folio.org/browse/UIEH-47
https://issues.folio.org/browse/UIEH-36 …
=> Show/Hide functionality for title-packages

src/components/customer-resource-show/customer-resource-show.js, tests/customer-resource-show-test.js, tests/pages/customer-resource-show.js
Per https://issues.folio.org/browse/UIEH-95, managed URL for a title-package should open in a new tab as opposed to the current behavior of opening in the same tab.
- Add target="_blank" to open url in a new tab
- Add associated unit tests
https://stackoverflow.com/questions/850058/is-it-possible-to-detect-if-a-user-has-opened-a-link-in-a-new-tab
=> Open managed URL in a new tab

src/components/package-show/package-show.js
Minor update to package level display to include ```<HR>```  between selected and hidden toggles to be consistent with package title level display
=> Add <HR> to package hide/show to be consistent with package-title

.travis.yml, karma.conf.js, tests/pages/helpers.js, tests/pages/settings.js
We can run our tests in more browsers on BrowserStack, but `allow_failures`.
`fast_finish` tells Travis it doesn't have to wait for allowed failures before it can declare the build successful.
- Firefox: really close to passing, I would think it's an easy fix
- Edge: having some date issues
- IE11: doesn't even start running the tests
=> Run tests in IE, Edge, and Firefox

src/components/customer-resource-show/customer-resource-show.js, src/components/package-show/package-show.js, tests/customer-resource-show-embargo-test.js, tests/customer-resource-show-visibility-test.js, tests/package-show-visibility-test.js, tests/pages/customer-resource-show.js
The EBSCO KB RM API has a limitation: unselected packages and package-titles can't have any customizations. The UI shouldn't show any customization options unless the package/package-title is selected.
Hide away the visibility toggle and custom embargo info from the user if the package/package-title is unselected.
The same logic will apply to custom coverage dates.
The visibility toggle's loading state was tied to `model.update.isPending`, meaning a change to the selection status would fire off a loading state on the visibility toggle. Instead, the visibility toggle's loading state should be `model.update.isPending && 'visibilityData' in model.update.changedAttributes`. Unfortunately, something in our redux layer isn't dealing with the nested `visibilityData` attribute in a way that …
=>  Only show visibility toggle if record selected

.travis.yml
The test for seeing if a new tab/window has opened (https://github.com/folio-org/ui-eholdings/pull/184) does not work in Firefox. Master branch is currently failing: https://travis-ci.org/folio-org/ui-eholdings/jobs/335864468.
Let's just allow failures for Firefox on Travis until we figure out how to fix the test.
=> Allow Firefox to fail on Travis

src/components/details-view/details-view.css, src/components/details-view/details-view.js, src/components/package-show.js, src/components/provider-show.js, src/components/query-list/query-list.js, src/components/scroll-view/scroll-view.css, src/components/scroll-view/scroll-view.js, src/redux/model.js, tests/details-view-test.js, tests/package-show-test.js
This fixes two bugs with the details-view introduced with the paginated related resources.
1. When clicking on one package and then clicking on another package, the previous package's related customer-resources persisted on the second package's page.
2. When loading related resources, the list is scrollable with 25 items with loading states. However, on pages with few related resources, the list portion of details-view remains as tall as the container to allow scrolling the previous loading items. This causes extra white space when the items are actually loaded.
1. Give collections a better unique `key` property. This unique key is used to reload the impagination component. Without including the `path`, this key evaluates to be the same for related customer-resources for any given …
=> Fix related resource pagination bugs

mirage/config.js, yarn.lock
Stripes now generates a translation bundle: https://issues.folio.org/browse/STCOR-49
Mirage doesn't know about it yet, so it blocks access to the translation files.
Resolves https://issues.folio.org/browse/UIEH-132
- This upgrades `stripes-core` and `stripes-cli` to newer versions.
- Mirage (pretender) passthrough created to allow access to the translation file(s).
Stripes CLI now reports warnings from `duplicate-package-checker`. We should resolve some of those.
=> Incorporate translation bundle files

.stripesclirc.js, package.json, yarn.lock
We use attributes like `data-test-eholdings-contributors-list-item` as selectors for the `ui-eholdings` test suite to use. We don't need those in production builds.
https://issues.folio.org/browse/UIEH-112
There were a lot of babel plugins out there doing more or less the same thing. I picked one that had >0 tests and took an array of regular expressions (vs. just a single string or array of strings).
This change barely made any impact in the size of the `dist` - I was hoping for more :)
This behavior is an excellent candidate to move into `stripes-core`.
=> Strip data-test attributes from production builds

src/components/impagination.js, tests/package-search-test.js, tests/pages/package-search.js
When records are resolved, impagination keeps a reference to the record in our store. When the record is updated immutably, the old record becomes stale and is not reflected in UI using the impagination component.
By using impagination's state machine directly we can resolve or reject records at will, without promises. This allows us to update any records currently in the load horizon with accurate records from our own data store.
=> Rewrite impagination component

mirage/config.js, src/components/custom-coverage-date/custom-coverage-date.css, src/components/custom-coverage-date/custom-coverage-date.js, src/components/custom-coverage-date/index.js, src/components/package-custom-coverage/index.js, src/components/package-custom-coverage/package-custom-coverage.js, src/components/package-show.js, src/routes/package-show.js, tests/package-show-custom-coverage-test.js, tests/package-show-selection-test.js, tests/pages/helpers.js, tests/pages/package-show.js
A user needs to be able to perform CRUD (create, read, update, and delete) operations on custom coverage dates on a package.
Create a custom-coverage-date component that encapsulates those CRUD operations and incorporate those actions into the application. Forms have a lot of state around them state that is 'internal' or a concern to the Form itself and state that is 'external' and a concern to the application and Redux-Store. To aid with this integration of 'internal', 'external' state, crud operations, dispatched actions to store and connecting and communicating with store and the like we employed the use of Redux-Form.
The validation around the custom-coverage-date component complies with https://issues.folio.org/browse/UIEH-50.
[Form …
=> Editable custom coverage date on package

package.json, yarn.lock
I wanted something small to verify our new Circle CI deploy pipeline is working correctly.
This is a small version bump to `stripes-cli` (plus `stripes-core`). We can also probably start using released versions of the CLI from now on, vs. the tip of `master`.
=> Install fresher stripes cli, core

src/components/search-form/search-form.js, tests/package-search-test.js, tests/pages/package-search.js, tests/pages/provider-search.js, tests/pages/title-search.js, tests/provider-search-test.js, tests/title-search-test.js
After the upgrade to React 16, the segmented control for selecting search type (Providers/Packages/Titles) could get in a state where more than one link was active.
It also started throwing a warning to the console:
In React 16, `className` can't accept a statement that evaluates to false. Luckily, that console warning was very helpful: we can use a ternary that returns undefined if the condition evaluates to false.
I added tests that would've failed before this change.
https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html
=> Fix search type segmented control active state

src/components/settings/settings.js, tests/backend-configuration-test.js
Hide the RM-API encryption key on the settings page
https://issues.folio.org/browse/UIEH-105
Simply set input type to password to hide text of api key
Not sure if a react component is needed here - https://www.npmjs.com/package/react-component-password
=> Update Settings API Key field to not show encryption key

mirage/factories/embargo-period.js, mirage/factories/package.js, mirage/scenarios/default.js, mirage/serializers/application.js, src/redux/model.js, src/router.js, tests/helpers.js, tests/it-will.js, tests/pages/helpers.js, tests/unit/redux-collection-test.js
Increases the current coverage percentages by a few points so other branches have a little more breathing room.
- Added unit tests for collections
- Selectively ignored some files and statements that do not get run during normal tests:
- The default mirage scenario is never run during testing
- A couple mirage factory methods are also never used
- The test helpers also consist of development helpers that aren't used during actual testing
- A few else blocks are currently never executed
Before:
After:
=> Increase coverage numbers

src/components/custom-embargo/custom-embargo.css, src/components/custom-embargo/custom-embargo.js, src/components/custom-embargo/index.js, src/components/customer-resource-show.js, src/routes/customer-resource-show.js, tests/customer-resource-show-embargo-test.js, tests/pages/customer-resource-show.js, yarn.lock
Initially, custom embargo was only readable but could not be edited. This implementation makes the custom embargo editable. 
- Custom Embargo Section should show up and be editable only when a title-package is selected, if not, it should be hidden
- If custom embargo is not present, "Add custom embargo" button should show up
- When the user clicks on the button, a form should open up containing a textfield to input embargo 
value, a dropdown to select embargo unit, a save button and a cancel button
- If custom embargo is present, that value should be displayed with a edit icon next to it, clicking on which the custom embargo form should open up
- User should be able to enter only positive integers in the text field
- User should be able to select one of None, Days, Weeks, Months, Years as …
=> Implement editable custom embargo

package.json, yarn.lock
Related to https://issues.folio.org/browse/STRIPES-504.
CircleCI production builds are failing:
https://yarnpkg.com/en/docs/package-json#toc-resolutions
=> Lock in uglify-es version at 3.3.9

.travis.yml
I noticed we're installing an older version of `yarn` over the one already on Travis.
Yarn is at a much more stable point now than it was six months ago, so just going with the `yarn` version already installed seems pretty safe.
Let's just stick with the version of `yarn` that comes by default on the Travis boxes.
=> Use newer version of yarn on Travis

tests/backend-configuration-test.js, tests/customer-resource-show-coverage-test.js, tests/customer-resource-show-test.js, tests/customer-resource-show-visibility-test.js, tests/package-show-custom-coverage-test.js, tests/package-show-visibility-test.js, tests/pages/package-show.js, tests/title-show-test.js
Some of our tests can be flakey due to varying reasons. This attempts to fix some of that flakiness.
- Fix customer-resource test where we were incorrectly testing for `false`.
- Remove coverage display test because there will never be a situation in which the API returns invalid dates.
- Use it.still for checking if states are not equal
There are probably other flakey tests as well, but this is a good start to fixing some of them.
- When writing tests for things that do not change, or for states that are not equal, we must use `it.still`. This is because when using the convergence `it`, it might pass before the DOM is updated to display the correct information. `it.still` will make sure the assertion passes for at least 50ms before considering it to actually be passing.
[The readme for …
=> Fix flakey tests

mirage/config.js, src/components/title-search-filters.js, src/routes/search.js, tests/title-search-test.js
Adds the selection status filter to title searches
Adds another accordion component with radio buttons for the selection status.
- We should really return the available filters from the API. Any suggestions on how that would look?
=> Add selected title search filter

src/components/customer-resource-show.js
When any update to the customer resource is submitted to the server, the visibility toggle goes into a loading state. It should only switch to a loading state if it is the attribute that's been changed.
=> Fix visibility toggle loading bug

mirage/config.js, mirage/factories/custom-coverage.js, mirage/factories/customer-resource.js, mirage/factories/package.js, mirage/models/customer-resource.js, src/components/coverage-dates/coverage-dates.js, src/components/coverage-form/coverage-form.css, src/components/coverage-form/coverage-form.js, src/components/coverage-form/index.js, src/components/custom-coverage-date/custom-coverage-date.css, src/components/custom-embargo/custom-embargo.css, src/components/customer-resource-show.js, src/redux/customer-resource.js, src/routes/customer-resource-show.js, tests/customer-resource-coverage-test.js, tests/customer-resource-deselection-test.js, tests/customer-resource-show-test.js, tests/pages/coverage-form.js, yarn.lock
Most of https://issues.folio.org/browse/UIEH-33.
As an electronic resource librarian
I want to add/edit custom coverage at the title-package level
So that I can accurately detail my library's access to that title in the package as our coverage differs from the provided managed coverage.
This gets the bare minimum implementation out for editing custom coverage on a package title. There's a lot more business logic from the EBSCO KB RM API that can be worked out in separate pull requests.
- I figured out an `isPending` pattern that seems to work nicely, where the form doesn't disappear until the change applies. It should be applied to package coverage and package title embargo editing.
- I used a `fieldset`, and the entire `fieldset` (including the `legend`) gets a blue background when in …
=>  Add editing for customer resource custom coverage

src/components/title-search-filters.js
Adds an "all" option for title selection status to align with the publication type when no filter is selected.
Just adds the "all" label and selects it when `filter[selected]` is `undefined`
=> Add "all" filter for title selection status

src/components/coverage-form/coverage-form.js, src/components/custom-coverage-date/custom-coverage-date.js, src/components/customer-resource-show.js, src/index.js, tests/package-show-custom-coverage-test.js
Part of https://issues.folio.org/browse/UIEH-33
Previously, we were showing the error message "Enter Date in 02/19/2018 format."
Instead we can peel off the format string using `moment`. This is how the `stripes-components` `Datepicker` determines its placeholder.
New: "Enter Date in MM/DD/YYYY format."
Applied to package and package-title custom coverage editing.
=> Get date format string from moment

src/components/coverage-form/coverage-form.css, src/components/custom-coverage-date/custom-coverage-date.css
On both the package and the customer resource custom coverage forms, entering a value into either a start date or end date would cause the row's layout to recalculate. The datepicker inputs would then change size.
The flex children that wrap the date pickers needed a `flex-basis` set (the third parameter of the `flex` shortcut).
https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis
=> Fix custom coverage datepicker row layout

mirage/config.js, src/components/search-form/search-form.js, src/routes/search.js, tests/package-search-test.js, tests/pages/package-search.js, tests/pages/title-search.js, tests/title-search-test.js
Implement Targeted Search Options for Title Searches.  This allows searching for titles by
- title (ie name)
- issn/isbn
- publisher
- subject
https://issues.folio.org/browse/UIEH-120
- Search form is updated to use searchfield component ( (combines a select and text box) for Title searches. Continue to use simple search text box for Provider and Package searches
- eHoldings URL continues to use **q** parameter and adds a new **searchfield** parameter for Title search options, For example?q=education&searchfield=subject
- Supporting requests to mod-kb-ebsco are made using a JSON API filter syntax (for example, filter[subject]=education)
- Updates to mirage configuration to support new search filters
- When switching between search options (for example from publisher to subject), the …
=> Implement Targeted Search Options on Title List

src/components/search-form/search-filters.js, src/components/search-form/search-form.css, src/components/search-form/search-form.js, src/components/title-search-filters.js, tests/pages/title-search.js, tests/title-search-test.js
Styles the search filters to match the stripes search-and-sort filter styles. 
Since these styles will be used in other search filters, a common component was made
- The current title-search-filters will be unnecessary once the API supports returning available filters via an endpoint. Instead, we can have the search-form render the search-filters component directly with the data returned from the API.
*Before*
*After*
=> Make common-component for search-filters

mirage/config.js, src/components/package-search-filters.js, src/routes/search.js, tests/package-search-test.js, tests/pages/package-search.js
Adds package search filters for content type and selection status using the filters `filter[type]` and `filter[selected]` respectively.
For the most part, copy and pasted the filter component for titles and just changed the relevant pieces to reflect the package filters. Same copy-paste method for the tests as well.
=> Add package search filters for content type and selection status

src/components/identifiers-list.js, tests/title-show-test.js
Per https://issues.folio.org/browse/UIEH-153, isbns on the title page are supposed to be separated by commas
- Use comma as separator
- Modify associated unit test
=> Separate ISBNs with commas

.stripesclirc.js, mirage/serializers/customer-resource.js, package.json, src/components/customer-resource-show.js, src/components/details-view/details-view.js, tests/customer-resource-show-test.js, tests/details-view-test.js, tests/pages/bigtest/customer-resource-show.js, tests/pages/package-show.js, tests/pages/title-show.js, yarn.lock
We'd like to use [BigTest](https://github.com/thefrontside/bigtest) tools in `ui-eholdings` to improve the speed and reliability of the test suite.
I refactored the `CustomerResourceShow` test to use a BigTest page object and assertions. When we've refactored all the page objects, we can move them back out of the `tests/pages/bigtest` directory to `/tests/pages`.
In the process, I discovered a regression where the subject list wasn't actually being printed out to the customer resource pages. I tried to lean more on comparing to explicit strings instead of generated mirage data (how that regression slipped in there in the first place).
[Babel Legacy Decorator plugin](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) makes it so we can use the `@page` decorator. …
=>  Refactor customer-resource-show test to use BigTest

package.json, yarn.lock
Gets rid of this.
Regenerated `yarn.lock` from scratch with an empty `node_modules` directory.
We'll now be relying on the `stripes-core` and `stripes-components` from `stripes-cli`.
=> Remove duplicate packages

mirage/config.js, src/components/custom-embargo/custom-embargo.css, src/components/custom-embargo/custom-embargo.js, src/components/customer-resource-coverage/customer-resource-coverage.css, src/components/customer-resource-coverage/customer-resource-coverage.js, src/components/customer-resource-show.js, src/components/package-custom-coverage/package-custom-coverage.css, src/components/package-custom-coverage/package-custom-coverage.js, src/components/package-show.js, src/routes/customer-resource-show.js, src/routes/package-show.js, tests/customer-resource-deselection-test.js, tests/package-custom-coverage-test.js, tests/pages/customer-resource-show.js, tests/pages/package-show.js
The inline editing for package custom coverage, package-title custom coverage, and package-title custom embargo should be very similar experiences.
Now they have consistent designs and the same `isPending` behavior. Package custom coverage borrowed the `FieldArray` setup from package-title custom coverage, but with modifications that it can only have one row.
=> Make coverage and embargo editing UX consistent

mirage/config.js, mirage/factories/package.js, src/components/package-show.js, src/redux/package.js, src/routes/package-show.js, tests/package-add-new-titles-test.js, tests/pages/package-show.js
Per https://issues.folio.org/browse/UIEH-54, implement functionality for allowing knowledge bases to add titles at package level. For now, the only KB ui-eholdings interacts with is Ebsco KB.
- Leverage the toggle-switch component for this functionality
- Toggle switch reflects the value of "allowKbToAddTitles" that we receive from mod-kb-ebsco
- User has the ability to toggle the switch and appropriate update is saved to "allowKbToAddTitles" in mod-kb-ebsco
- When user selects a package, then "allowKbToAddTitles" toggle should be set to true by default
- When user deselects a package, then "allowKbToAddTitles" should be reset to false
- Add associated unit tests for this functionality
- Update to previous comment: Investigated to find out that RM API does not send "allowEbscoToAddTitles" …
=> Implement allow KB to add titles functionality

src/components/custom-embargo/custom-embargo.js
We had disabled linting on a few lines due to the `no-restricted-globals` rule.
We can follow the rule just by changing `isNaN()` to `Number.isNaN()`.
https://github.com/airbnb/javascript#standard-library--isnan
=> Fix eslint no-restricted-globals errors

src/components/details-view/details-view.js, src/components/package-show.js, src/components/provider-show.js, src/components/search-paneset/search-paneset.js, src/components/title-show.js, tests/customer-resource-show-test.js, tests/package-show-test.js, tests/pages/bigtest/customer-resource-show.js, tests/pages/customer-resource-show.js, tests/pages/package-search.js, tests/pages/package-show.js, tests/pages/provider-search.js, tests/pages/provider-show.js, tests/pages/title-search.js, tests/pages/title-show.js, tests/provider-show-test.js, tests/title-show-test.js
Reference: https://issues.folio.org/browse/UIEH-187
In order to match the rest of FOLIO, this adds titles to preview pane headers.
We moved the back button and the close pane logic into a single place.
We learned that the `PaneHeader` paneTitle accepts a node as well as a string.
=> Add a pane title to detail views

.stripesclirc.js, yarn.lock
Code coverage reporting is broken. It reports 100% for everything and doesn't generate any files.
I broke it by improperly adding `babel-plugin-transform-decorators-legacy` in https://github.com/folio-org/ui-eholdings/pull/231. I overwrote the `babel-loader`'s plugins instead of just adding to them.
I rearranged the `plugins` additions to work properly.
=> Fix coverage reporting

src/components/package-list-item/package-list-item.css, src/components/package-list-item/package-list-item.js, src/components/package-search-list.js, src/components/provider-list-item/provider-list-item.css, src/components/provider-list-item/provider-list-item.js, src/components/provider-search-list.js, src/components/title-list-item/title-list-item.css, src/components/title-list-item/title-list-item.js, src/components/title-search-list.js, src/index.js, tests/package-search-test.js, tests/pages/package-search.js, tests/pages/provider-search.js, tests/pages/title-search.js, tests/provider-search-test.js, tests/title-search-test.js
Per https://issues.folio.org/browse/UIEH-172, when user conducts a search and selects a result in the provider/package/title result list pane, the selected result should be highlighted within the result list pane. 
- Modify index.js to pass 'type' and 'id' of the provider/package/title being selected in search route. 
- Within search list, compare the 'type' and 'id' to identify which item has been selected
- If an item has been selected, set its corresponding "active" prop type to true; else false
- Modify css of the selected item to have a gray background color, white text and the hover color to match the background color
- Also, add associated unit tests
- CSS Selectors and Combinators
- react-cx
=> Highlight selected provider/package/title

src/components/customer-resource-show.js, src/components/details-view/details-view.js, src/components/package-show.js, src/components/provider-show.js, src/components/title-show.js, tests/customer-resource-show-test.js, tests/package-show-test.js, tests/pages/bigtest/customer-resource-show.js, tests/title-show-test.js
Reference: https://issues.folio.org/browse/UIEH-187
Continuation of PR #243 to add sub title. We wanted to show sub titles just for package-titles.
Fixed some naming of test assertion.
Build threw warning when trying to put a `<div>` inside of a `<span>`.
=> Add pane sub to customer resources

src/components/custom-embargo/custom-embargo.js
https://github.com/folio-org/ui-eholdings/pull/226 introduced a new warning when running tests:
```ERROR: 'Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a string.```
I needed to take the approach Jason mentioned:
https://github.com/folio-org/ui-eholdings/pull/226#issuecomment-367519623
=> Fix new isNaN warning

mirage/config.js, mirage/helpers.js, src/components/provider-search-filters.js, src/components/search-form/search-form.js, src/routes/search.js, tests/pages/provider-search.js, tests/provider-search-test.js
Adds functionality to sort providers by either provider name or relevance as described https://issues.folio.org/browse/UIEH-84
- Followed same logic as used for filters on other search types to add sort filters
- Updates to Search Form to support a url of `sort=name`. Internal to component passes a filter object with sort onto child filters component.
- Updates to Search form to automatically search when the sort filter is selected. Change is made specific to provider sort filter. Another ticket - https://issues.folio.org/browse/UIEH-157 addresses behavior of filters for other search types
- Updated Mirage Config to support A-Z sorting and a simulated Relevance Sort
- A-Z uses string localeCompare so the sort can be done as case insensitive and can sort numbers naturally ( 1 < 2 < 10)
- …
=> Implement Provider Sort Options

src/routes/search.js, tests/package-search-test.js, tests/provider-search-test.js, tests/title-search-test.js
After conducting a search users are presented with a list of results and detail view associated with clicking on an item from the results list. When a user conducts a new search removing the detail view that contains the old  information from the last clicked item makes it a more pleasing user experience
Remove the third pane after a new search it conducted in any Provider, Package, or Title search
UIEH-104
=> Remove detail pane upon conducting new search

src/components/customer-resource-coverage/customer-resource-coverage.js, src/components/customer-resource-show.js, tests/customer-resource-custom-coverage-test.js, tests/pages/customer-resource-coverage.js
Package/Titles require more intensive custom coverage validation than
Package-level custom coverage.  Since Package/Titles can have multiple
custom coverage ranges, additional care must be taken to prevent
overlap among these ranges.  Additionally, Package/Titles must respect
the custom coverage range (if any) of their parent package.  If a
package has a custom coverage range set, all titles within that
package are relegated to custom coverage within the package's range.
These new validations, being significantly more complex than those on
packages, crowded the `validate` method, and so all validations were
pulled out into functions and called in sequence during validation.
**NOTE**
_This replaces https://github.com/folio-org/ui-eholdings/pull/235.  The functionality is the same, but I …
=> Package/Title-Specific Custom Coverage Validations

src/components/customer-resource-coverage/customer-resource-coverage.js, src/components/package-list-item/package-list-item.js, src/components/package-show.js, src/components/provider-show.js, src/components/query-list/query-list.js, src/components/settings/settings.js, src/components/title-list-item/title-list-item.js, src/components/title-show.js, tests/backend-configuration-test.js, tests/customer-resource-custom-coverage-test.js, tests/customer-resource-visibility-test.js
Per https://issues.folio.org/browse/UIEH-168, Folio uses sentence case, where as ui-eholdings uses Title case. Update title case where used to sentence case.
- Go through each file, figure out where static text is in title case and update it to sentence case.
- Update associated tests as well that check for specific error messages.
- Update certain mirage files as well for consistency.
=> Update title case to sentence case

mirage/config.js, src/components/package-search-filters.js, src/components/search-form/search-form.js, tests/package-search-test.js, tests/title-search-test.js
Adds sort options as filter to package search (as documented at https://issues.folio.org/browse/UIEH-119)
- Added Sort Options as filter (similar to what was done for Providers)
- Updated filter behavior for all search types so that search is conducted upon selection of filter (not requiring a user to click the search button) - This functionality is required for https://issues.folio.org/browse/UIEH-157
- Updated filter tests so that search is not clicked on filter selection
- Updated Mirage search configuration so that title searches are handled in the same way as package and provider searches (results containing any word in a query are returned)
=> Implement Package Sort Options

src/components/package-search-filters.js, src/components/title-search-filters.js
Update selected label from `Selected by EBSCO` to `Ordered through EBSCO` on both Title and Package search as noted https://issues.folio.org/browse/UIEH-154.
Also update Publication Type and Content Type filters from sentence case to title case (noted as part of https://issues.folio.org/browse/UIEH-168)
Updated labels - no unit tests involved
=> Update Filter Labels on Title and Package Search

src/components/package-show.js
Per https://issues.folio.org/browse/UIEH-191, labels for "allow KB to add new titles" should be updated to "Automatically select new titles"
- Update only the labels and do not modify names of props or state because they still hold the meaning of this toggle
=> Update labels for allow kb to add new titles

tests/harness.js, tests/helpers.js
Replaces #232
These imports are normally found in the webpack config used by stripes-core, but when running tests using karma-webpack the entry field is discarded. By adding them to our test harness, we can ensure they will be included in our tests as well.
Import the missing style assets directly into our test harness and set the `#react-testing` div's height to `100%` to align with the `100%` height given to the typical root element.
=> Add style imports to test harness

Jenkinsfile
❌  Jenkins only leaves comments in the PR when the lint fails, but does not fail the build.
✅  Travis fails the build with linting errors. 
No need to run lint on Jenkins.
=> Only run linting on Travis, not Jenkins

package.json, tests/backend-configuration-test.js, tests/customer-resource-show-test.js, tests/helpers.js, yarn.lock
Upgrades `@bigtest/mocha` to fix mocha timeout errors
- Upgrade `@bigtest/mocha` to `^0.3.0` which removes mocha timeouts
- Unskipped the `it.always` tests that were previously flakey
- Use `@bigtest/convergence` for the `visit` helper
- Also removed `goBack` since it's never used
- And removed `window.pauseTest` since we now have `it.pause`
=> Upgrade @bigtest/mocha

package.json, src/components/details-view/details-view.css, src/components/package-list-item/package-list-item.css, src/components/provider-list-item/provider-list-item.css, src/components/search-form/search-form.css, src/components/title-list-item/title-list-item.css
I've been noticing my editor catching some stylelint errors recently on files I hadn't been working on. I realized we put stylelint in the `ui-eholdings` dependencies, but weren't actually running it in CI.
Run stylelint whenever we run `yarn lint`.
Long-term, we probably want to run stylelint separate from ESLInt - should make for easier to parse CI runs. We should also explore exposing stylelint errors at runtime (https://www.npmjs.com/package/stylelint-webpack-plugin?) and getting stylelint into the `stripes-cli` blueprint.
=> Run stylelint in Travis

src/components/details-view/details-view.css, src/components/details-view/details-view.js, src/components/modal/modal.js, src/components/package-show.js, src/components/provider-show.js, src/components/search-form/search-form.js, src/components/title-show.js, src/routes/search.js
Part of https://issues.folio.org/browse/UIEH-143
We'd like to eventually have a way to search lists of related items on detail panes. I created a proof-of-concept that opens a modal containing the search filters for that type of item.
Proof-of-concept (not implemented in this PR):
This ships some groundwork of that proof-of-concept that's ready for production. The search form needed to be more independent of the search route to be able to render it in a modal in a different place. The list header is also now ready for a right-aligned icon button to be dropped in.
No functionality changes with this PR.
=> Lay groundwork for new list search modal

PULL_REQUEST_TEMPLATE.md
Our PR template doesn't provide support to folks new to the project, and is instead more geared towards people who have already "drunk the koolaid" so to speak. It provides terse boilerplate that can, ironically, leave you wondering "why am I filling out this template?"
Some specific things I've noticed:
1. It doesn't provide any context as to why each section exists
2. Some sections are optional, yet often people feel obliged to fill
them out. This will inevitably feel like busy-work and degrade the
experience of the PR author as well as the PR reader.
3. If someone wants to educate themselves about writing good pull
request, it doesn't actually provide them with any resources to do
so.
This expands unpacks each section of the pull request and gives a purpose and approach for each …
=> Make PR template more user friendly.

.circleci/config.yml, karma.conf.js, package.json, yarn.lock
CircleCI 2.0 has a lot of optimizations over Travis that can improve the speed and reliability of our CI builds.
[CircleCI 2.0 Workflows](https://circleci.com/docs/2.0/workflows/)
- Circle doesn't have the nice `allow_failures` option that Travis does, so the IE and Edge jobs just have to report passing, even though those test runs failed.
- ESLint and Stylelint are not yet reporting their results in JUnit format, which enables Circle to have some nicer UI and reporting.
- We can dry up the YAML a lot with anchors and references.
=> Create CircleCI config

.circleci/config.yml, .travis.yml, karma.conf.js
Last week we were seeing lots of "browser disconnected" messages from BrowserStack. Any disconnection would fail the build on CI. It would happen sometimes with Safari, but much more frequently with Firefox.
I tried increasing the disconnection tolerance so the browser would attempt to reconnect x number of times, and that succeeded (https://github.com/karma-runner/karma-browserstack-launcher/issues/61). The side effect was that Firefox would sometimes take 30-40 minutes to complete its test run with BrowserStack. I'm guessing that's because BrowserStack has had a rough time with newer versions of Firefox: https://www.browserstack.com/question/670.
I then tried just running the Firefox tests directly on the CI container, since both Travis and Circle have Firefox available directly on the …
=>  Allow Firefox failures on CI

src/components/package-show.js, tests/package-add-new-titles-test.js, tests/pages/bigtest/package-show.js
Change `package-add-new-titles-test` to use BigTest page objects and assertions.
Ran into an issue around clicking confirmation modal buttons. The confirmation modal is being rendered directly into the `body` rather than as a child of the `package-show` component. Since BigTest page objects are all scoped to `$root` this meant adding a separate page object for the modal. Once that was added, simply appending the two interactions together works as a nice clean fix.
=> Refactor package-add-new-titles-test to use BigTest

.gitignore, mirage/factories/package.js, src/components/customer-resource-show.js, tests/customer-resource-embargo-test.js, tests/package-show-test.js, tests/pages/bigtest/customer-resource-show.js, tests/pages/customer-resource-show.js
BigTest page objects are nice. Let's use them.
Now the custom embargo test doesn't need to use bigtest/convergence directly.
Removes the need for some chicanery in https://github.com/folio-org/ui-eholdings/pull/268
Copied the modal-in-page-object pattern from https://github.com/folio-org/ui-eholdings/pull/253
=> Use BigTest for custom embargo test

src/components/custom-embargo/custom-embargo.css, src/components/custom-embargo/custom-embargo.js, src/components/customer-resource-coverage/customer-resource-coverage.css, src/components/customer-resource-coverage/customer-resource-coverage.js, src/components/customer-resource-show.js, src/components/details-view-section/details-view-section.css, src/components/details-view-section/details-view-section.js, src/components/details-view-section/index.js, src/components/details-view/details-view.css, src/components/details-view/details-view.js, src/components/list/list.css, src/components/package-custom-coverage/package-custom-coverage.css, src/components/package-custom-coverage/package-custom-coverage.js, src/components/package-show.js, src/components/provider-show.js, src/components/title-show.js
Replaces https://github.com/folio-org/ui-eholdings/pull/272.
The main benefit of the accordions was the nice headlines organizing the content. I made a component that mimics the accordion headline styles, minus the accessibility issues.
Detail panes also have the appropriate headline hierarchy now (with the exception of the duplicated title, which will eventually be resolved with https://github.com/folio-org/ui-eholdings/pull/252).
=> Refine preview pane design with headers

src/components/custom-embargo/custom-embargo.js, src/components/customer-resource-coverage/customer-resource-coverage.js, src/components/package-custom-coverage/package-custom-coverage.js, tests/pages/bigtest/customer-resource-show.js
A few times when using `<Field>` from `redux-form`, we've defined an extra method to render the relevant component. Ex: `renderDatepicker`.
Since the `stripes-components` `Datepicker`, `TextField`, and `Select` are all designed to work with `redux-form` and have all the errors UI built into them, we can pass them in directly to `Field`s without any extra processing or ornamentation.
=> Simplify redux-form render components

tests/pages/helpers.js
As part of moving to BigTest page objects, the old prototype `blur()` helper is no longer in use.
=> Remove unused blur() helper

.circleci/config.yml, karma.conf.js, package.json, yarn.lock
We're bumping against rate limits on BrowserStack, and Firefox is frequently running very slowly: https://www.browserstack.com/question/670
We can run Firefox tests in Linux directly on the Circle container instead of trying to run them on macOS through BrowserStack. That should help cut down the BrowserStack usage and avoid its Firefox problems.
=> Run Firefox tests directly on Circle container

.circleci/config.yml, .travis.yml
`ui-eholdings` has been rate-limited on BrowserStack lately, causing CI builds to take sometimes 10x longer than they should.
- Firefox, now being tested directly on the Linux container, now needs to pass on Circle.
- Travis will now test Firefox directly on its containers instead of BrowserStack.
- Stop running Edge and IE 11 tests. IE can't even begin to run the test suite, and we can revisit Edge with https://issues.folio.org/browse/UIEH-182
- Only run Travis or Circle, not both.
=> Minimize BrowserStack usage

src/components/customer-resource-show.js, src/components/details-view/details-view.css, src/components/package-show.js
Ref [UIEH-193](https://issues.folio.org/browse/UIEH-193)
This change confines the elements inside the label to the length of the label itself, preventing functionality applied to the label from spanning the length of the container.
By placing the `ToggleSwitch` and `<h4>` within the label element and styling them within a confined space, we are now only able to click the switch itself to change it's state. As a note, the only way I was able to make the `<h4>` and `ToggleSwitch` remain stacked was by adding a `<br />` between them.
=> UIEH-193: Prevent toggling switch when clicking in label's white space

tests/package-custom-coverage-test.js, tests/pages/bigtest/package-show.js
We weren't using the full power of page objects when it came to the datepickers on package pages.
Create a Datepicker page object to DRY things up.
- Apply the same pattern to the datepickers on customer resource pages.
=> Refactor datepicker page objects

src/components/search-form/search-form.css, src/components/search-paneset/search-paneset.js, src/routes/search.js, tests/package-search-test.js, tests/pages/package-search.js, tests/pages/provider-search.js, tests/pages/title-search.js, tests/provider-search-test.js, tests/title-search-test.js
Close out remaining functionality for Filter Behavior and result list update as described at:
_[UIEH-157](https://issues.folio.org/browse/UIEH-157)_
Prior pull request - https://github.com/folio-org/ui-eholdings/pull/251 addressed filter selection (without requiring click of search button).
The following 2 items are addressed by this PR
- When the search box is empty the search button is currently disabled and remains disabled until text is entered in the search box. There was no visual indication that the button is disabled. Added styling to the button so this is more apparent. (this is done instead of displaying a message about an empty search)
- Updated behavior of search/filter panel visibility on small screens. Rules as follows:
1. Hide Panel if the user enters a new search term
2. …
=> Update logic for search/filter panel visibility on smaller screens +style for disabled search button

.circleci/config.yml
Circle's `circleci/node:latest-browsers` image runs Firefox 47. We were trying to install the `sid` version, which didn't always install on the Circle `jessie` boxes.
Install Firefox's extended support release instead. Right now it's 52.7.2.
=> Run Firefox ESR in Circle

src/components/search-form/search-form.css, src/components/search-form/search-form.js
There's no longer a compelling reason to use our own button that mimics the upstream styles - we should just use the available `stripes-components` button.
=> Use stripes-components Button for search

mirage/config.js, mirage/factories/customer-resource.js, src/components/coverage-statement-fields.js, src/components/coverage-statement-form/coverage-statement-form.css, src/components/coverage-statement-form/coverage-statement-form.js, src/components/coverage-statement-form/index.js, src/components/customer-resource-edit/customer-resource-edit.css, src/components/customer-resource-edit/customer-resource-edit.js, src/components/customer-resource-edit/index.js, src/components/customer-resource-show.js, src/components/details-view/details-view.js, src/index.js, src/redux/customer-resource.js, src/routes/customer-resource-edit.js, src/routes/customer-resource-show.js, tests/customer-resource-coverage-statement-test.js, tests/customer-resource-edit-test.js, tests/pages/bigtest/customer-resource-edit.js, tests/pages/bigtest/customer-resource-show.js
When a package-title is selected, a user can customize it by setting a coverage statement.
Resolves https://issues.folio.org/browse/UIEH-79
This will be the first example of a set of `redux-form` fields being shared in two places, the customer resource edit and show routes. Eventually we'll want embargo and coverage dates to work the same way.
A lot of the page objects and event handling could be done more elegantly, but in the interests of time, we've got a bulky-but-working version.
=> UIEH-79 Add coverage statement editing

src/components/package-list-item/package-list-item.js, src/components/search-form/search-filters.js, tests/package-search-test.js, tests/pages/bigtest/customer-resource-show.js, tests/pages/bigtest/package-search.js, tests/pages/customer-resource-show.js, tests/pages/title-show.js
By refactoring to use BigTest, we can resolve a lot of our flakiness.
Made a package-search bigtest page-object, and refactored the tests to make use of it. 
Removed the old page-object and also removed most of the title-show page-object and a few properties from the customer-resource-show page-object to bump up coverage.
Some tests around the search pane vignette were skipped since those tests are heavily reliant on screen size and fail depending on the browser's window.
- We should figure out how to properly test mobile-specific features. Do we isolate those tests? Can we change the browser size from within our tests?
=> Refactor package-search to use BigTest

tests/package-visibility-test.js, tests/pages/bigtest/package-show.js, tests/pages/package-show.js
~~Skipped one assertion using `allTitlesHidden` from the page object. We can revisit that the next time this test gets touched.~~ No skips added.
Someday to-do: figure out how to instrument the mirage server to test loading states.
=> UIEH-196 Use BigTest page object for package visibility test

mirage/factories/customer-resource.js, tests/customer-resource-visibility-test.js, tests/pages/bigtest/customer-resource-show.js
Convert `customer-resource-visibility` to BigTest to continue ongoing migration efforts.
Changed some of the `it` statements for readability and to better match the wording on other visibility tests.
=> UIEH-196 Refactor customer resource visibilty test to BigTest

tests/package-show-test.js, tests/title-show-test.js
Using a `.once().do()` is preferable to `convergeOn()`.
=> UIEH-196 Replace a few instances of convergeOn()

src/components/title-list-item/title-list-item.js, tests/package-selection-test.js, tests/package-show-test.js, tests/pages/bigtest/package-show.js, tests/pages/package-show.js
Only three tests left using legacy page objects:
=> UIEH-196 Use BigTest page object for package selection test

src/components/coverage-statement-fields/coverage-statement-fields.css, src/components/coverage-statement-fields/coverage-statement-fields.js, src/components/coverage-statement-fields/index.js, src/components/custom-embargo/custom-embargo.css, src/components/customer-resource-coverage-fields/customer-resource-coverage-fields.css, src/components/customer-resource-coverage-fields/customer-resource-coverage-fields.js, src/components/customer-resource-coverage-fields/index.js, src/components/customer-resource-coverage/customer-resource-coverage.css, src/components/customer-resource-coverage/customer-resource-coverage.js, src/components/customer-resource-edit/customer-resource-edit.js, src/components/customer-resource-show.js, src/routes/customer-resource-edit.js, tests/customer-resource-edit-test.js, tests/pages/customer-resource-custom-coverage.js, tests/pages/customer-resource-edit.js
Package-title custom coverage dates should be editable both inline and in the full-page edit view.
Resolves https://issues.folio.org/browse/UIEH-222.
Abstract out the fields and validations in the `CustomerResourceCoverageFields` component.
- Copy custom embargo editing the same way (https://issues.folio.org/browse/UIEH-221)
- Create an `InlineForm` component to handle a lot of the shared interactions and styles.
=> UIEH-222 Copy custom coverage editing to full-page view

src/components/utilities.js, yarn.lock
Completely removes React 16.2 and upgrades stripes cli/core/components. Required one change to follow edited `eslint-config-stripes` rules.
=> Only include React 16.3 in the bundle

src/components/coverage-statement-form/coverage-statement-form.js, src/components/custom-embargo-form/custom-embargo-form.js, src/components/customer-resource-coverage-fields/customer-resource-coverage-fields.js, src/components/customer-resource-coverage/customer-resource-coverage.js, src/components/customer-resource-edit/customer-resource-edit.js, src/components/customer-resource-show.js, src/components/details-view/details-view.js, src/components/package-coverage-fields/index.js, src/components/package-coverage-fields/package-coverage-fields.css, src/components/package-coverage-fields/package-coverage-fields.js, src/components/package-custom-coverage/package-custom-coverage.js, src/components/package-edit/index.js, src/components/package-edit/package-edit.css, src/components/package-edit/package-edit.js, src/components/package-show.js, src/components/settings/settings.js, src/index.js, src/routes/package-edit.js, tests/package-edit-test.js, tests/pages/package-edit.js, tests/pages/package-search.js, tests/pages/package-show.js, tests/pages/provider-search.js, tests/pages/title-search.js
https://issues.folio.org/browse/UIEH-223
A package's attributes should be editable from a "full-page" view, not just an "inline" form. 
I used the same patterns established in https://github.com/folio-org/ui-eholdings/pull/305 and https://github.com/folio-org/ui-eholdings/pull/317.
I had to avoid using the pane header dropdown because of the lack of z-index management in FOLIO. When there's an active search query, the pane header dropdown isn’t visible, because the z-indices we’re using for eHoldings layout are higher than anything in `stripes-core` or `stripes-components` (but there aren’t enough integers between those used in Stripes and zero for the things we’re doing). Instead I just put a pencil icon in the top right, which is what other FOLIO apps have at the moment anyway. I …
=> UIEH-223 Copy coverage date editing to full page package edit route

src/components/customer-resource-show.js, src/components/package-show.js, src/components/provider-show.js, src/components/title-show.js, src/components/utilities.js, tests/customer-resource-show-test.js, tests/package-show-test.js, tests/pages/provider-show.js, tests/pages/title-show.js, tests/provider-show-test.js, tests/title-show-test.js, yarn.lock
Re: [UIEH-71](https://issues.folio.org/browse/UIEH-71)
Currently we do not have `GET` errors displaying to the user. This change displays a generic `error` message to users so that they know that the application is listening, but also that something has gone awry.
I based my work off of @Robdel12's pull request #301 to add similar functionality to the `GET` errors as the `PUT`s, utilizing the `toast` components written here. To make the code a bit more dry and reusable, I added both the aforementioned `PUT` errors work, as well as my `GET` errors work, into the `utilities` file.
This is an example of an error that displays with a package that does not exist. Identical to the errors one gets for `PUT`s.
=> UIEH-71: Display GET errors

src/components/preview-pane/preview-pane.css, src/components/results-pane/results-pane.css, src/components/search-form/search-form.css, yarn.lock
Sets a `flex-basis` on the results and preview panes, so they can never shrink lower than 320px wide. The `flex-grow` proportions are the same - the preview pane will grow at an 11 to 5 ratio vs. the results pane.
Also includes stripes cli/core/components upgrade, to fix pane header CSS bug.
=> Adjust search layout proportions

src/components/error-screen/invalid-backend.js, src/components/settings-detail-pane/index.js, src/components/settings-detail-pane/settings-detail-pane.css, src/components/settings-detail-pane/settings-detail-pane.js, src/components/settings-knowledge-base/index.js, src/components/settings-knowledge-base/settings-knowledge-base.css, src/components/settings-knowledge-base/settings-knowledge-base.js, src/components/settings-root-proxy.js, src/components/settings/index.js, src/index.js, src/routes/settings-knowledge-base.js, src/routes/settings-root-proxy.js, src/routes/settings.js, tests/backend-configuration-test.js, tests/pages/settings.js
Until now, ui-eholdings has only had one screen of settings. With root proxy settings about to be built and custom labels coming very soon, we needed a way to have more than one screen of settings.
Groundwork for https://issues.folio.org/browse/UIEH-212
To compare to https://github.com/folio-org/ui-eholdings/pull/318, this uses the `stripes-components` `Settings` with modifications: https://github.com/folio-org/stripes-components/pull/301
=> UIEH-212 Create settings subnavigation (alternate implementation)

tests/helpers.js
Now that we've fully migrated over to bigtest and we can return convergences from our hooks, this `.timeout().run()` is no longer necessary since bigtest/mocha does that for us.
This will hopefully squelch some timeout errors we're seeing when running our tests in Firefox (#315)
=> Fix visit helper

src/components/customer-resource-show.js, src/components/package-show.js
Resolves https://issues.folio.org/browse/UIEH-237.
I had moved the "package information" and "resource information" sections lower.
=> UIEH-237 Move metadata for records to top of detail view

src/components/search-form/search-form.js
Another quick win. Although it didn't change VoiceOver's behavior, it satisfied axe-devtools to add an `ariaLabel` to the search field.
=> Add ariaLabel to search field in absence of label markup

tests/customer-resource-edit-test.js
This test has been flaky: https://circleci.com/gh/folio-org/ui-eholdings/1582
Sometimes it can't find the validation message at all, and sometimes it is the wrong message.
My best guess is that the validation isn't being properly triggered, so I explicitly blur the field. That's the approach we've taken on some other inputs.
=> Blur embargo value for validation tests

src/components/customer-resource-edit/customer-resource-edit.js, src/components/customer-resource-show.js, src/components/package-edit/package-edit.js, src/components/package-show/index.js, src/components/package-show/package-show.css, src/components/package-show/package-show.js, src/components/provider-show/index.js, src/components/provider-show/provider-show.css, src/components/provider-show/provider-show.js, src/components/title-show/index.js, src/components/title-show/title-show.css, src/components/title-show/title-show.js
Evolution of https://issues.folio.org/browse/STCOM-194
When a user is looking at a three-pane search layout, we want to give them the option to see the third pane by itself.
The "Full view" link kicks the user out to a new page that shows the record without any search query.
Media queries hide the "Full view" link at high browser zoom or small screen width, since at those sizes the third pane is already full-width. That means the action menu is empty for providers and titles at small sizes, but I imagine there will very soon be more items in the menu to make that less strange.
=> Add action menu items to pane headers

src/components/package-list-item/package-list-item.js, src/components/package-search-list.js, src/components/provider-list-item/provider-list-item.js, src/components/provider-search-list.js, src/components/title-list-item/title-list-item.js, src/components/title-search-list.js
Right now, if you open a native context menu from a search results item and select "Open Link in New Tab" or "Open Link in New Window", it will link to the full search results layout with that record's preview pane open.
We can default to the href of the record by itself, but capture that click and add the search parameters to stay within the search results context.
=> Create right-clickability for search results items

src/components/list/list.css, src/components/package-list-item/package-list-item.css, src/components/package-list-item/package-list-item.js, src/components/package-show/package-show.js, src/components/provider-list-item/provider-list-item.css, src/components/provider-list-item/provider-list-item.js, src/components/provider-show/provider-show.js, src/components/title-list-item/title-list-item.css, src/components/title-list-item/title-list-item.js, src/components/title-show/title-show.js
`h1`/`h2`/`h3`/etc. should only increment by one in the DOM hierarchy.
Add a `headingLevel` prop to list item renderers. Defaults to `h3`.
https://dequeuniversity.com/rules/axe/3.0/heading-order
=> Only increase heading levels by one

src/components/settings-knowledge-base/settings-knowledge-base.css, src/components/settings-knowledge-base/settings-knowledge-base.js, src/routes/settings-knowledge-base.js, tests/backend-configuration-test.js, tests/pages/settings.js
The knowledge base settings form wasn't using `stripes-components` text inputs, or the `redux-form` patterns established in the rest of `ui-eholdings`. For consistency, we should handle this form the same way.
Also now uses `Toast`s when an error occurs.
=> Refactor KB auth form to use redux-form

package.json, src/redux/data.js, src/redux/helpers.js, tests/unit/redux-merge-relationships-test.js, yarn.lock
As we navigate through the eholdings app, data from resolved requests is persisted in the redux store.  When we're loading a search route with a selected detail record, one request is fired off for the list of search records and one is fired off for the singleton detail record.  If the search request resolves after the detail request, the detail page's related records are overwritten by the "newer" request, which contains no relationship data.  
The result in the UI is the list of related records on a detail page flickering and disappearing (see [UIEH-199](https://issues.folio.org/browse/UIEH-199)).  This was particularly evident in the Title Details pane, because Title searches take longer than any other RMAPI resource to resolve, and frequently resolved after the detail pane request. …
=> UIEH-199 Persist Relationship Data in Store

.circleci/config.yml
Sometime in the last few days BrowserStack upgraded the version of Safari used by its tests on High Sierra. It moved from Safari 11.0.3 to 11.1.
Since then, Circle hasn't been able to maintain a consistent connection to BrowserStack. It tries to reconnect a few times, but at around 40 min or so it hits the maximum number of disconnects and fails the run.
Last time Safari tests passed on master: https://circleci.com/gh/folio-org/ui-eholdings/1842
First run when it started failing: https://circleci.com/gh/folio-org/ui-eholdings/1872
We can't point to an earlier Safari on High Sierra. I tried Safari 10.1 on Sierra and got ten failures that would be pretty painful to go debug.
I reached out to BrowserStack, but in the meantime, since PR merges are blocked, I recommend just turning off tests …
=> Turn off Safari tests in CI

src/components/package-show/package-show.js, tests/package-selection-test.js, tests/package-show-test.js, tests/pages/package-show.js
Instead of saying "Knowledge base does not automatically select titles.", custom packages shouldn't show a "Title management" section at all.
Resolves https://issues.folio.org/browse/UIEH-281
=> UIEH-281 Hide title management section for custom packages

mirage/config.js, mirage/scenarios/default.js, src/components/custom-package-edit/custom-package-edit.js, src/components/package-content-type-field/index.js, src/components/package-content-type-field/package-content-type-field.css, src/components/package-content-type-field/package-content-type-field.js, src/components/package-content-type/index.js, src/components/package-content-type/package-content-type.css, src/components/package-content-type/package-content-type.js, src/components/package-show/package-show.js, src/routes/package-edit.js, src/routes/package-show.js, tests/custom-package-edit-test.js, tests/package-content-type-test.js, tests/pages/package-edit.js, tests/pages/package-show.js, yarn.lock
Adds the capability for users to assign a content type to a custom package. We now have the ability to choose a content type on the `custom-edit` page as well as inline on the `package-show` page.
Resolves [UIEH-249](https://issues.folio.org/browse/UIEH-249)
=> UIEH-249: Custom Package Content Type

mirage/config.js, mirage/helpers.js, src/components/details-view/details-view.js, src/components/modal/modal.css, src/components/modal/modal.js, src/components/provider-show/provider-show.js, src/routes/provider-show.js, tests/pages/provider-show.js, tests/pages/search-modal.js, tests/provider-show-package-search-test.js
Adds a search button and modal to provider details that allows searching the list of packages pertaining to the provider. ([UIEH-278](https://issues.folio.org/browse/UIEH-278))
The `SearchForm` component was reused, but within a modal that is displayed when clicking on a search button in the header of the provider's related packages list.
When a new search string is given, the modal will close itself on search. When only the sort or filter options change, the modal remains open but the search is still performed in the background.
- The inner search params are not persisted in the URL. This prevents us from deep linking searches within the details view. The current params are persisted in the route state, and in the future we can make this route use query params instead of it's state …
=> UIEH-278 Search packages within provider details

mirage/config.js, mirage/factories/resource.js, mirage/scenarios/default.js, src/components/custom-resource-edit/custom-resource-edit.css, src/components/custom-resource-edit/custom-resource-edit.js, src/components/custom-resource-edit/index.js, src/components/managed-resource-edit/index.js, src/components/managed-resource-edit/managed-resource-edit.css, src/components/managed-resource-edit/managed-resource-edit.js, src/components/resource-coverage-fields/resource-coverage-fields.js, src/components/resource-name-field/index.js, src/components/resource-name-field/resource-name-field.css, src/components/resource-name-field/resource-name-field.js, src/components/resource-show.js, src/redux/resource.js, src/routes/resource-edit.js, tests/custom-resource-edit-test.js, tests/managed-resource-edit-test.js, tests/pages/resource-edit.js
Sets up editing for the name and coverage dates of a custom title.
Resolves https://issues.folio.org/browse/UIEH-257
Resolves https://issues.folio.org/browse/UIEH-276
When hitting eholdings/customer-resources/:id/edit, determine from the resource's isTitleCustom attribute whether to show the managed or custom package edit form.
_Custom title editing currently does not work in production. This PR does not change that, but sets up everything needed in mirage to keep iterating on the UI._
=> UIEH-257  Set up editing for custom titles

mirage/scenarios/default.js, src/components/custom-resource-edit/custom-resource-edit.js, src/routes/resource-edit.js, tests/custom-resource-edit-test.js
This adds editing capabilities to the coverage statements in the full page editing view.
This resolves [UIEH-295](https://issues.folio.org/browse/UIEH-295)
=> UIEH-295: Add coverage statement to edit page

src/components/package/edit.js, src/components/resource/edit.js, src/routes/package-edit.js, src/routes/resource-edit.js
@cowboyd pointed out that in the `PackageEdit` and `ResourceEdit` routes, the check to see whether we should show the form for a managed or custom object is purely presentational:
```
if (model.isCustom) {
View = PackageEditCustom;
}
```
Moves the `isCustom` and `isTitleCustom` checks to new components out of the route. We can also combine the `initialValues` props for managed/custom. The `initialValues` managed packages/resources/ lack will just be ignored.
=> Simplify package and resource edit routing

src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/package/_forms/custom-coverage/package-custom-coverage.js, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/resource/_fields/custom-coverage/resource-coverage-fields.js, src/components/resource/_forms/custom-coverage/resource-coverage.js, src/components/resource/edit-custom/custom-resource-edit.js, src/components/resource/edit-managed/managed-resource-edit.js, tests/pages/resource-custom-coverage.js, tests/resource-custom-coverage-test.js
When a user clicks the "circle X" icon to remove custom coverage from a package or resource, they should get a warning that saving changes will remove the previously set date range(s). The message was being shown too eagerly - any time a user removed the last date range row, they saw the "Saving will remove" message, even if they didn't previously have any custom coverage dates set.
Check the `initialValue` of `customCoverages` to determine whether to show the "Saving will remove custom coverage" message on removing all date range rows.
For a package, `customCoverage` is an object with `beginCoverage` and `endCoverage` keys, vs. a resource, which has a `customCoverages` array. The `PackageCoverageFields` component uses a `redux-form` `FieldArray` to have the same UX as setting coverage …
=> Adjust custom coverage fields behavior

mirage/config.js, mirage/factories/resource.js, mirage/scenarios/default.js, src/components/resource/_fields/peer-reviewed/index.js, src/components/resource/_fields/peer-reviewed/peer-reviewed-field.css, src/components/resource/_fields/peer-reviewed/peer-reviewed-field.js, src/components/resource/edit-custom/custom-resource-edit.js, src/components/resource/show.js, src/redux/resource.js, src/routes/resource-edit.js, tests/custom-resource-edit-test.js, tests/pages/resource-edit.js, tests/pages/resource-show.js
Enables checkbox on the edit page that will display to users that a custom title has, or has not, been reviewed.
Resolves [UIEH-250](https://issues.folio.org/browse/UIEH-250)
=> UIEH-250: Peer reviewed field

mirage/config.js, mirage/factories/resource.js, mirage/factories/title.js, mirage/scenarios/default.js, src/components/resource/_fields/description/description-field.css, src/components/resource/_fields/description/description-field.js, src/components/resource/_fields/description/index.js, src/components/resource/edit-custom/custom-resource-edit.js, src/components/resource/show.js, src/redux/resource.js, src/routes/resource-edit.js, tests/custom-resource-edit-test.js, tests/pages/resource-edit.js, tests/pages/resource-show.js
Adds editable description to edit page and description field to resource view.
Resolves [UIEH-254](https://issues.folio.org/browse/UIEH-254)
=> UIEH-254: Add description field to custom title

.gitignore, mirage/config.js, src/components/details-view-section/details-view-section.css, src/components/details-view-section/details-view-section.js, src/components/package/create/index.js, src/components/package/create/package-create.css, src/components/package/create/package-create.js, src/components/package/show/package-show.js, src/components/toaster/toast.js, src/index.js, src/redux/data.js, src/redux/model.js, src/redux/resolver.js, src/routes/package-create.js, tests/package-create-test.js, tests/pages/package-create.js
[UIEH-259](https://issues.folio.org/browse/UIEH-259)
Sets up the route and view for creating a custom package, and adds fields for name, content type, and custom coverage to the creation form.
While creating custom packages are not yet supported in the backend, we can utilize mirage to iterate on the frontend.
- The route for creating custom packages is `/eholdings/packages/new`.
- A navigation modal is shown if there are changes to the form and a user clicks "cancel"
- When a custom package is successfully created, the user is redirected to the show route for the newly created package and a toast success message is shown.
- The current fields were preexisting in the edit route, but re-utilized for this creation route.
- A `create` action was added to models which will trigger a request …
=> UIEH-259: Custom Package Creation

mirage/config.js, src/components/modal/modal.js, src/components/package/edit-custom/custom-package-edit.js, src/components/package/show/package-show.js, src/components/toggle-switch/toggle-switch.css, src/components/toggle-switch/toggle-switch.js, src/components/utilities.js, src/redux/data.js, src/redux/model.js, src/routes/package-edit.js, src/routes/package-show.js, tests/custom-package-edit-test.js, tests/custom-package-selection-test.js, tests/custom-package-show-selection-test.js, tests/pages/package-edit.js, tests/pages/package-search.js
With a custom-package as a resource librarian I want to be able to remove that custom-package from my holdings. 
- Ensure holding-status work within and not within a context of a Redux-Form
- Make Toggle Switch accessible. Making sure the toggle is usable from Assistive Devices.
- Report holding-status toggle / removal errors back to the user.
- Add destroys Errors to Toast
- Keeps user on current page to make a decision based on the failure.
- Add the capability to to adjust holding-status from both inline and full-page edit mode.
- Allow the custom package holding-status is adjusted from either direct access from pasting into URL or navigating after a search.
- Redirect the user after a successful removal of a custom-package from either a inline, full-page and from either direct input …
=> UIEH-261 Custom Package holding status

src/components/package/create/package-create.js, src/components/search-paneset/search-paneset.css, src/components/search-paneset/search-paneset.js, tests/package-search-test.js, tests/pages/package-search.js, tests/pages/provider-search.js, tests/pages/title-search.js, tests/provider-search-test.js, tests/title-search-test.js
Making eHoldings more consistent with the `<SearchAndSort>` UX used by other FOLIO modules.
We'll need the header there to add "+ New" buttons for custom packages and titles.
Add a pane header and mimic the `stripes-smart-components` `<NoResultsMessage>`, which unfortunately is tightly coupled to `<SearchAndSort>`.
I decided against reusing a `<ResultsPane>` for the empty state to avoid the scroll logic there.
The "+ New" button that will soon appear in the header won't be accessible on small screens until conducting a search.
=> UIEH-308 Add pane header to results pane even if no search yet

src/redux/data.js
`POST`s from `ui-eholdings` to `mod-kb-ebsco` were failing because `jsonapi-rails` was receiving `content-type: application/json` instead of `content-type: application/vnd.api+json`.
=> Send JSON API content type header for POSTs

src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/package/show/package-show.js, src/components/resource/show.js, src/components/title/edit/title-edit.css, src/components/title/edit/title-edit.js, src/components/title/show/title-show.js, tests/custom-title-edit-test.js, tests/managed-package-edit-test.js, tests/pages/package-edit.js, tests/pages/package-show.js, tests/pages/resource-edit.js, tests/pages/resource-show.js, tests/pages/title-edit.js, tests/pages/title-show.js, tests/resource-edit-test.js
When clicking to edit a package, title, or package-title, there's not reason to leave the three-pane search results layout.
When leaving to a full-page layout, the back button was occasionally not being shown, because we were not passing the `eholdings: true` state through `stripes-components` `<IconButton>`s.
https://issues.folio.org/browse/UIEH-341
The `IconButton` `href` prop actually accepts a router location object, even though its `PropTypes` throw a warning if the `href` isn't a string:
```
Warning: Failed prop type: Invalid prop `href` of type `object` supplied to `IconButton`, expected `string`.
```
=> UIEH-341 Smooth out back button logic

src/components/search-paneset/search-paneset.js, tests/package-search-test.js, tests/provider-search-test.js, tests/title-search-test.js
When getting back a single search result, the subtitle of the results pane currently reads "1 search results". _nails scraping on blackboard_
Remove the `s` when there's only one search result.
=> Singularize string when only one search result

src/components/package/show/package-show.js, src/components/resource/show.js, src/components/title/show/title-show.js, yarn.lock
`ERROR: 'Warning: Failed prop type: Invalid prop 'href' of type 'object' supplied to 'IconButton', expected 'string'.`
Use new `to` prop on `IconButton`. Thanks @JohnC-80!
https://github.com/folio-org/stripes-components/pull/345
```
WARNING in duplicate-package-checker:
<lodash>
4.17.10 ./~/lodash
4.17.5 ./~/react-apollo/~/lodash
```
Probably needs a PR to `react-apollo`. I'm not sure why they're locked into that specific `lodash` vs. allowing patch/minor updates. I'll look into it.
=> Use IconButton to prop instead of href

.circleci/config.yml
CircleCI's `latest` images started using node 10, which caused some dependency errors: https://circleci.com/gh/folio-org/ui-eholdings/2523
=> Run Circle CI on node 9

src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/package/show/package-show.js, tests/custom-package-edit-test.js, tests/managed-package-edit-test.js, tests/package-create-test.js
When successfully saving changes to a package (either managed or custom) on `/eholdings/packages/:id/edit`, show a success toast on redirecting to back to `/eholdings/packages/:id`.
Resolves https://issues.folio.org/browse/UIEH-310
=> UIEH-310 Show success toast when package saved

src/components/package/show/package-show.js
In some flows the package-show component would get into a bad state and throw an error, interrupting the user with a white error screen. This PR adds a simple null check to avoid ever hitting that state.
Resolves [UIEH-344](https://issues.folio.org/browse/UIEH-344) and [UIEH-345](https://issues.folio.org/browse/UIEH-345)
Error Screen:
=> UIEH-344, UIEH-345: Adds a null check to package-show success toast logic

mirage/config.js, mirage/factories/title.js, mirage/scenarios/default.js, mirage/serializers/resource.js, src/components/resource/show.js, src/components/title/_fields/edition/edition-field.css, src/components/title/_fields/edition/edition-field.js, src/components/title/_fields/edition/index.js, src/components/title/edit/title-edit.js, src/components/title/show/title-show.js, src/redux/resource.js, src/redux/title.js, src/routes/title-edit.js, tests/custom-title-edit-test.js, tests/pages/resource-show.js, tests/pages/title-edit.js, tests/pages/title-show.js, tests/resource-show-test.js, tests/title-show-test.js
Per https://issues.folio.org/browse/UIEH-253, users should be able to add or edit an edition for a custom title and view the same on title-record as well as resource-record pages.
- Created a component called "edition" in _fields in title
- Used that component in title-edit, resource-show and title-show
- Added needed config for mirage
- Added unit tests
=> UIEH-253 - Add edition field to custom title edit page

mirage/config.js, src/components/title/_fields/contributor/contributor-field.css, src/components/title/_fields/contributor/contributor-field.js, src/components/title/_fields/identifiers/identifiers-fields.css, src/components/title/_fields/identifiers/identifiers-fields.js, src/components/title/_fields/identifiers/index.js, src/components/title/edit/title-edit.js, src/components/title/show/title-show.js, src/routes/title-edit.js, tests/custom-title-edit-test.js, tests/pages/title-edit.js
Users should be able to edit the identifiers of a custom title.
Finishes https://issues.folio.org/browse/UIEH-256.
The server wants separate type and subtype fields; we merge them into one for the UI.
The UI implementation leans heavily on `redux-form`'s `FieldArray`, like we've previously done with custom coverage dates.
=> UIEH-256 Edit identifiers on a custom title

mirage/serializers/resource.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/edit.js, src/components/resource/show.js, src/redux/resource.js, src/routes/resource-edit.js, src/routes/resource-show.js
`mod-kb-ebsco` tries to flatten out RM API's `title` and `resource` payloads, but in the process ends up attaching a bunch of attributes to `resources` that actually belong to `titles`.
We can't completely untangle until `PUT /titles` and `POST /titles` are available, but this clears up the distinction in the resource show and edit routes.
=> Get title attributes from included on resource routes

mirage/config.js, mirage/scenarios/default.js, mirage/serializers/title.js, src/components/title/_fields/package-select/index.js, src/components/title/_fields/package-select/package-select-field.css, src/components/title/_fields/package-select/package-select-field.js, src/components/title/create/index.js, src/components/title/create/title-create.css, src/components/title/create/title-create.js, src/components/title/show/title-show.js, src/index.js, src/redux/title.js, src/routes/title-create.js, tests/pages/title-create.js, tests/title-create-test.js
[UIEH-304](https://issues.folio.org/browse/UIEH-304) 
There should be a route where we can create custom titles just like the custom package creation route.
The custom title creation route is `/eholdings/titles/new`. It includes a navigation modal that appears when attempting to navigate away with unsaved changes, and an error toast when a server error is encountered. When the custom title is successfully created, the title show page for the new title is shown with a success toast.
The existing fields that can be found when editing a custom title were included in the creation form. Additionally, a package select field was added. This field requires us to get a list of custom packages when the route component is mounted. For now, we can develop and iterate on this page using mirage, but …
=> UIEH-304 Create Custom Titles

src/components/modal/modal.css
When performing a package search from within a provider record, the modal that pops up with the search interface simply cuts off the overflowing filter radio inputs.
Resolves: [UIEH-322](https://issues.folio.org/browse/UIEH-322)
I've changed the Modal component content area from `overflow: hidden` to `overflow: auto`.
=> UIEH-322: Alter Modal css rule to enable scrolling of content

mirage/config.js, src/components/package/show/package-show.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/resource-view/index.js, src/components/resource/resource-view/resource-view.js, src/components/resource/show.js, src/redux/data.js, src/routes/resource-edit.js, src/routes/resource-show.js, tests/custom-package-show-selection-test.js, tests/custom-resource-edit-selection-test.js, tests/custom-title-edit-test.js, tests/managed-resource-edit-selection-test.js, tests/managed-resource-edit-test.js, tests/pages/package-search.js, tests/pages/resource-edit.js, tests/provider-search-test.js, tests/resource-custom-coverage-test.js, tests/resource-deselection-test.js, tests/resource-edit-managed-title-in-custom-package-test.js, tests/resource-edit-managed-title-test.js, tests/resource-show-test.js
The eholdings application allows users to add and remove a resource aka title from their holdings. To add a resource aka title to their holdings they "select" it which means its now in their holdings and they have the rights for patrons to access it. A user adding a resource / title to their holdings can happen in two types of packages within eholdings a `'Managed Package'` or a `'Custom Package'` and the resource / title its self can either be a `'Managed-Title'` or a `'Custom-Title'`.
`Managed Packages` are Packages that are completely managed / controlled by the Knowledge Base. `Custom-Packages` are Packages that are created by a eholdings user and the user is now responsible for the maintenance of the Package, for example any name changes, or ISBN updates, etc. These same descriptions …
=> UIEH-285 Deselect managed and custom titles

src/components/package/edit-custom/custom-package-edit.js, tests/custom-package-edit-selection-test.js, tests/custom-package-edit-test.js, tests/pages/package-edit.js
[UIEH-358 - Edit: unselect Package Details Records (package name/content type)](https://issues.folio.org/browse/UIEH-358)
When users are on the full page edit form for a custom package, they can toggle the packages Holding Status from Selected to Unselected.  The toggle is changed on the form, but not yet committed to the backend. The commit is only done once the form is submitted via a Save button. In the case of Unselecting a Custom Package and committing via Save, the package is essentially deleted. When the toggle appears as unselected on the full page edit form (and has not yet been submitted), all other editable fields should be disabled. The majority of this work was addressed in the following PR: 
https://github.com/folio-org/ui-eholdings/pull/385 
This PR addresses the disabling …
=> UIEH-358 - Custom Package Full Page Edit (Name/Content Type Disable when deselected)

src/routes/title-create.js
While working on https://github.com/folio-org/mod-kb-ebsco/pull/128, I discovered that RM API's max page size is 100.
We should request 100 custom packages, instead of 1000.
Use some type of UI element that can paginate for showing the list of available custom packages.
=> UIEH-287 Adjust number of custom packages fetched

src/components/package/edit.js, src/routes/package-edit.js
A Routes responsibility is to pass along data and just return a View not determine which kind of View to return. View branching logic belongs in the View. The View receives data and then looks at that data to determine what kind of View it should return to the Route. 
- Move View Logic from the Route to a intermediate View that will contain the branching logic to determine what kind of View to return.
=> Remove package view logic from route

mirage/config.js, src/components/title/_fields/package-select/package-select-field.js, src/components/title/_forms/add-to-package.js, src/components/title/create/title-create.js, src/components/title/show/title-show.css, src/components/title/show/title-show.js, src/routes/title-show.js, tests/pages/title-show.js, tests/title-add-to-custom-package-test.js
[UIEH-286](https://issues.folio.org/browse/UIEH-286)
We need the ability to add titles to a custom package and create a resource as a result.
Added a button to titles that will open a modal allowing the user to choose a custom package to add the title to, which will then send a request to `POST /resources` to create the related resource.
Updated the `PackageSelectField` component to accept an array of options instead of a collection so that the view component can control which fields are disabled.
Packages that already contain the title (i.e. the title's resources) are disabled in the package select field instead of being omitted entirely.
=> [UIEH-286] Add title to custom package

src/components/package/create/package-create.js, src/components/title/create/title-create.js, src/components/title/show/title-show.js, src/routes/title-show.js, tests/package-create-test.js, tests/pages/package-create.js, tests/pages/title-create.js, tests/pages/title-show.js, tests/title-add-to-custom-package-test.js, tests/title-create-test.js
[UIEH-360 - Attach loading states to custom title forms](https://issues.folio.org/browse/UIEH-360) 
The following forms all do not disable the Save/Submit and Cancel Buttons when the form is being submitted and do not display an animated loading indicator next to the Save Button
- Form for Creating a Custom Title
- Form for Creating a Custom Package 
- Modal for adding a title to a custom package
This PR adds these features to the 3 forms.
Additionally, for Create a Title and Create a Package forms, the Save button is disabled if the form is in a pristine state.
Similar as has been done in other forms, added check for request.IsPending to disable the Cancel and Save Buttons and to enable the loading indicator.  Also added disable of Save button on Title Create and Package Create forms. …
=> UIEH-360 Attach loading state to title/package create forms and modal

src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, tests/pages/resource-edit.js, tests/resource-edit-custom-title-test.js, tests/resource-edit-managed-title-test.js
Managed-Titles and Managed-Packages are capable of being 'unselected' from a users electronic holdings and not not viewable to a patron but still present and able to be interacted with by a eHoldings application user. However, the level of interaction a user can have with a title differs from when the title is 'selected' vs 'unselected'. Until a title is 'selected'  the user should not be able to make any customization to that title because titles that are not selected are essentially not added to the user eHoldings and giving them permission to make customizations. 
- Hide / Disable editable sections until the title is "selected".
- https://issues.folio.org/browse/UIEH-355
=> UIEH-355 Hide editable areas when managed-title in managed-package is unselected

package.json
FOLIO UI modules should explicitly require stripes-components as a dependency.
We were previously just leaning on whatever platform `ui-eholdings` was running on, but `ui-eholdings` should be more explicit about its `stripes-components` version.
I also added a `peerDependency` on `react`, like the `stripes-cli` blueprint for a UI module: https://github.com/folio-org/stripes-cli/blob/master/resources/ui-app/package.json
=> Explicitly require stripes-components as dependency

src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/edit.js, src/routes/resource-edit.js, tests/managed-resource-edit-test.js, tests/pages/resource-edit.js, tests/resource-edit-custom-title-test.js
Add the ability to toggle the visibility on a custom resource and a custom package. 
From the looks of it custom package full page edit already has the visibility toggle
This follows the same pattern as toggling a selected package.
=> [UIEH-359] Add visibility toggle to custom resource

src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/edit.js, src/components/resource/show.js, src/routes/resource-edit.js, src/routes/resource-show.js, tests/custom-resource-edit-visibility-test.js, tests/managed-resource-edit-visibility-test.js, tests/pages/resource-edit.js, tests/pages/resource-show.js, tests/resource-visibility-test.js
[UIEH-380 - Package Title Edit: Issue with Visibility and isSelected in Combo](https://issues.folio.org/browse/UIEH-380) 
[UIEH-365 -Remove Inline Editing - Title+Package Show - Visibility Field ONLY](https://issues.folio.org/browse/UIEH-365) 
This PR resolves Title Package Edit  issues noted in UIEH-380, specifically the following issues exist for  managed title package (full page edits)
- Go to a managed title package record (select full page edit mode) . Toggle visibility status - note that the Save Button remains disabled. It should be enabled upon a change.
-  Go to a managed title package record that is both selected and visible (full page edit mode). Toggle to NOT selected and save
Get error (Invalid Hidden and Invalid Contributor) pop up as toast messages.
Additionally, as noted …
=> UIEH-380 - Title Package:Issue with Visibility and IsSelected + Remove Inline Edit of Visibility

mirage/helpers.js, mirage/serializers/package-list.js, mirage/serializers/provider-list.js, mirage/serializers/title-list.js, src/redux/data.js, src/redux/helpers.js, tests/unit/redux-merge-attributes-test.js
[UIEH-363](https://issues.folio.org/browse/UIEH-363)
Merge attributes from newly resolved requests and override only values that exist and are not undefined.
This fixes an issue with our search results not returning complete data. If a search is resolved after a find, the find data was replaced with the incomplete data. Now the data gets merged so that any missing data that already exists in the store is not purged.
Similar to #271 except with attributes instead of relationships.
Even though the tests do not use mirage, I updated mirage to also omit results like the backend does. The backend serializers inherit from the partial list serializers. But for mirage, the list serializers inherit from the normal serializers and include an additional whitelist which excludes the omitted fields.
- …
=> [UIEH-363] Merge attributes data

src/routes/resource-edit.js, tests/resource-edit-managed-title-test.js
[UIEH-386](https://issues.folio.org/browse/UIEH-386)
The missing `intl` from props was causing the validation to throw an error for coverage dates because `formatISODateWithoutTime` is dependent on `intl.formatDate()`.
Provide `intl` as a prop in the route for editing resources
To cause a test failures, I only needed to add an additional coverage date to some existing tests. Providing the `intl` as described above caused them all to start passing again.
- Why is the validation run for multiple coverages but not single coverages?
**Before**
**After**
=> [UIEH-386] Full Page Edit of Resource with Multiple Custom Coverage Dates Error

src/components/package/edit-managed/managed-package-edit.css, src/components/package/edit-managed/managed-package-edit.js, src/routes/package-edit.js, tests/managed-package-edit-add-new-titles-test.js, tests/managed-package-edit-selection-test.js, tests/pages/package-edit.js
This is the first step in replacing our toggles with radio buttons. This is because the toggle switches weren't obvious what state they were in.
Remove the toggle switch and use `RadioButtonGroup` with redux form. This removed the weird complexity we had with the toggles. Now it's falling more inline with the way the rest of the form works.
=> [UIEH-354] Replace title management toggle with radios for managed packages

.circleci/config.yml
https://github.com/folio-org/ui-eholdings/pull/415 broke the `build` command, but that wasn't caught until `folio-ui-eholdings-deploy` tried to run it.
Test `yarn build` as part of the Circle workflow for `ui-eholdings`. I confirmed that this would've caught the previous bug: https://circleci.com/gh/folio-org/ui-eholdings/3650
=> Add build step to Circle workflow

package.json, src/components/search-paneset/search-paneset.js, translations/ui-eholdings/en.json, yarn.lock
Replaces https://github.com/folio-org/ui-eholdings/pull/421
After more reading about `react-intl`, this feels like the better approach. `injectIntl()` is really only needed when you need to get a bare string. In most cases the `<FormattedMessage>` component is the way to go.
=> UIEH-351 Introduce translations file 

src/components/resource/_fields/visibility/index.js, src/components/resource/_fields/visibility/visibility-field.css, src/components/resource/_fields/visibility/visibility-field.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/show.js, src/routes/resource-edit.js, tests/custom-resource-edit-visibility-test.js, tests/managed-resource-edit-visibility-test.js, tests/pages/resource-edit.js, tests/pages/resource-show.js, tests/resource-edit-custom-title-test.js, tests/resource-edit-deselection-test.js, tests/resource-edit-managed-title-test.js, tests/resource-visibility-test.js
[UIEH-353](https://issues.folio.org/browse/UIEH-353)
A resource's visibility setting is more clear when using radio buttons as oppose to a toggle with a dynamic label. The visibility setting should also be included in "resource settings" as opposed to it's own "visibility" section.
For the show page, the "Resource information" section was changed to "Resource settings" to line up with "Package settings" and the screenshot attached to the ticket. Resource settings includes the managed or custom URL along with the visibility data. When a reason is given with the visibility data, it is displayed inline next to the visibility status ("yes" or "no").
A new field was created for the edit page so it can be reused on the custom and managed resource edit pages. When a resource's visibility …
=> [UIEH-353] Resource Visibility Radios

src/components/details-view/details-view.css, src/components/details-view/details-view.js
[UIEH-408](https://issues.folio.org/browse/UIEH-408)
When packages were loading within a providers detail view, the number `0` would display until the list loaded.
Also, when there were no results count the bottom padding of the list heading was collapsed.
Ensure that the logical operator `&&` has a boolean before it. When the first part of this operator is falsey, it is used. Since the `resultsCount` was returning `0`, that was being rendered to the screen. Actually casting it as a boolean ensures that it is not rendered.
To fix the bottom padding when there is no results count, a css rule for `:not(:only-child)` was added to the heading.
*Before*
*After*
=> [UIEH-408] Fix details view list results count bug

src/components/package/edit-managed/managed-package-edit.css, src/components/package/edit-managed/managed-package-edit.js, src/components/package/show/package-show.js
To clean up the managed packaged edit and show view to have the right copy.
=> [UIEH-354] Clean up managed package view & labeling

src/routes/package-create.js, tests/package-create-test.js, tests/pages/package-create.js
Within the eholdings application users have the ability to create a custom package that has a 'contentType' selection that is required when creating a custom-package. Upon the initial intent to create a custom-package we are going to set the default content type to 'Unknown'. If the user does not explicitly change this default the custom package they create will have the content-type of Unknown.
- Pass an initialValue to the content-type field in the form
=> UIEH-393 Default content type to 'Unknown'

mirage/config.js, mirage/models/rootProxy.js, src/components/settings-root-proxy/_fields/root-proxy-select/root-proxy-select-field.js, src/components/settings-root-proxy/settings-root-proxy.js, src/redux/application.js, src/redux/index.js, src/routes/settings-root-proxy.js, tests/pages/settings-root-proxy.js, tests/settings-root-proxy-test.js
From the ui-eholdings application a user has the ability to pick from a list of available Root-Proxy and then set it. When a user reaches the settings page a list of available Root-Proxy is populated but when they have to send a request to update the Root-Proxy the request cannot contain the collection but rather a single root-proxy. This work here utilizes two new endpoints in mod-kb-ebsco to facilitate in the updating of what is deemed a singular resource in Root-Proxy. 
- Create two new models:
- `Proxy-Types`: which is the collection of available of Root-Proxy
- `Root-Proxy`: which is the Singular Root-Proxy and the Proxy that the user current has set or is trying to set from the UI.
- Make use of the two new endpoints:
- `eholdings/proxy-types`: will `GET` return a collection
- …
=> UIEH-212 Refactor root proxy to use new endpoints

src/components/coverage-date-list/coverage-date-list.js, src/components/package-list-item/package-list-item.js, src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/package/show/package-show.js, src/components/provider-list-item/provider-list-item.js, src/components/provider-show/provider-show.js, src/components/resource/_fields/custom-coverage/resource-coverage-fields.js, src/components/resource/show.js, src/components/utilities.js, src/index.js, src/routes/resource-edit.js, tests/custom-package-edit-test.js, tests/custom-resource-edit-custom-coverage-test.js, tests/managed-package-edit-test.js, tests/managed-resource-edit-custom-coverage-test.js, tests/package-create-test.js, tests/package-custom-coverage-test.js
Now that we know it's on the fast train to deprecation, we want to avoid using the old React context API.
Use `react-intl`'s `FormattedDate`, `FormattedNumber`, and `injectIntl` instead of `context.intl` or `stripes.context.intl`. When `react-intl` moves to the new context API under the hood, those abstractions should still work.
=> Use intl from react-intl instead of stripes context

src/components/details-view/details-view.css
[UIEH-410- Detail Record: List of Packages / Titles header is bleeding into first package/title on list](https://issues.folio.org/browse/UIEH-410) 
Under certain conditions, we are seeing result list header text overlap with the first item in a result list.  The overlap condition was found to happen in cases when screen size is adjusted/scaled or when testing in responsive mode and adjusting height. This condition was also happening in some windows installations. All cases were observed with Chrome Browser.
Thanks to consult with @wwilsman for css fix which resolves this issue. Added flex-shrink setting of 0.
`What was happening, is by default `flex-shrink` is `1`. Which means it's allowed to shrink by that "factor". When the list didn't have a height, it was causing the header to shrink …
=> UIEH-410 - Package Titles header is bleeding into first package/title in list

src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/package/create/package-create.js, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/resource/_fields/custom-coverage/resource-coverage-fields.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/show.js, src/index.js, src/routes/resource-edit.js
Now that we know it's on the fast train to deprecation, we want to avoid using the old React context API.
Use `locale` from the `intl` prop injected by `react-intl` rather than `context.intl` or `stripes.context.intl`. When react-intl moves to the new context API under the hood, those abstractions should still work.
I don't love the way the `injectIntl` pattern plays with our `redux-form` `validate()` organization (ESLint picks up some "unused" props), but this means we're now not retrieving `context.stripes` at all. :tada:
=> Use locale from react-intl instead of stripes context

src/components/package/edit-custom/custom-package-edit.css, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.css, src/components/package/edit-managed/managed-package-edit.js, src/components/package/show/package-show.js, src/routes/package-edit.js, tests/custom-package-edit-selection-test.js, tests/custom-package-edit-visibility-test.js, tests/managed-package-edit-selection-test.js, tests/managed-package-edit-visibility-test.js, tests/package-visibility-test.js, tests/pages/package-edit.js
To be consistent with other Folio apps, we are changing the Visibility toggle to radio buttons.
This resolves [UIEH-352](https://issues.folio.org/browse/UIEH-352)
There was some great work done for changing the visibility toggles in resources that helped guide my approach here for packages. 
*_Before_*
*_After_*
=> UIEH-352: Change package visibility toggle to radio inputs

src/components/contributors-list.js, src/components/identifiers-list.js, src/routes/title-edit.js, tests/custom-title-edit-test.js, tests/pages/title-edit.js, tests/pages/title-show.js
This change fixes the bug, outlined in [UIEH-388](https://issues.folio.org/browse/UIEH-388), that prevented the user from adding additional contributors and identifiers to a custom title. 
Where I was hung up the most was in the tests. For the longest time I was unable to get the values of the _type_ of contributor and the _name_ of the contributor separately, as they appear to the user.
To do this, I ended up having to modify the components a touch to give the `type` and `name/id` separate data attributes as there wasn't a way to differentiate them in the test otherwise. 
Before, the test would return the text value of both the type and name combined for contributor, as the page object was looking for just any text in that row:
` …
=> [UIEH-388] Custom title adding identifiers and contributors

.circleci/config.yml, package.json, yarn.lock
HTML coverage reports are now on by default :) https://github.com/folio-org/stripes-cli/pull/82
Update to `stripes-cli` `1.2.x`.
=> Upgrade to stripes-cli 1.2.x

src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/package/show/package-show.js, tests/managed-resource-edit-visibility-test.js, tests/package-visibility-test.js, tests/resource-visibility-test.js
This changes `Visible to patrons` to `Show titles in package to patrons` in package details in order to be consistent with the rest of the app. I also changed the wording in a few tests to meet this as well. 
This resolves [UIEH-437](https://issues.folio.org/browse/UIEH-437).
=> [UIEH-437 ]Change visibility label

src/components/package/edit-custom/custom-package-edit.js, src/components/package/show/package-show.js
Simply a change to the modal messaging when deleting a custom package to better reflect that the consequence of deselecting a custom package is to DELETE it.
=> UIEH-314: Change modal message when deleting a custom package from holdings

src/components/resource/show.js, tests/pages/resource-show.js, tests/resource-deselection-test.js, tests/resource-edit-selection-test.js, tests/resource-embargo-test.js, tests/resource-selection-test.js, tests/resource-show-test.js, yarn.lock
UI-eHoldings users are able to add and remove `titles` also referred to as `resources` to their holdings. Here we are refactoring from using a toggle-switch to rather use a button to add and then removing is done from the action menu in the dropdown. This change and UX is more in line with what the rest FOLIO applications are doing so we conforming to ensure users have the same experience across the the various FOLIO applications. 
- Replace the ToggleSwitch component with Button component
- Add the actions to the drop-down within the Resource Page header
=> UIEH-404 Refactor holding status away from ToggleSwitch

package.json, translations/ui-eholdings/en.json
We now have a way to provide translations for the module name. Upstream changes: https://github.com/folio-org/stripes-core/pull/327
=> STCOR-228 Add translation for module title

src/components/details-view/details-view.js, src/components/package-list-item/package-list-item.js, src/components/package-search-list.js, src/components/package/show/package-show.js, src/components/provider-list-item/provider-list-item.js, src/components/provider-search-list.js, src/components/provider-show/provider-show.js, src/components/search-paneset/search-paneset.js, src/components/should-focus.js, src/components/title-list-item/title-list-item.js, src/components/title-search-list.js, src/components/title/show/title-show.js, src/routes/search.js, tests/package-search-test.js, tests/package-show-test.js, tests/pages/package-search.js, tests/pages/package-show.js, tests/pages/provider-search.js, tests/pages/provider-show.js, tests/pages/resource-show.js, tests/pages/title-search.js, tests/pages/title-show.js, tests/provider-search-test.js, tests/provider-show-test.js, tests/resource-show-test.js, tests/title-search-test.js, tests/title-show-test.js
[[UIEH-440]](https://issues.folio.org/browse/UIEH-440)
This initially started as a spike to see how accessible routing looked in eholdings. This cleans up that POC and adds tests.
As it turned out, this POC has little to do with the actual routing or routes. 
- **Focus the pane title when a new search is conducted**
This was done in the `SearchPaneset` component. When the component updates with a new search within the same search type, the results pane title will receive focus. Similarly, when navigating directly to an existing search (via external link), the results pane title is also focused on mount (as long as the details view is not also visible).
- **Focus the search results list item when a details pane is closed**
The search route knows which element is currently, and was …
=> [UIEH-440] More Accessible Routing

src/components/impagination.js, src/components/navigation-modal/navigation-modal.js, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/query-list/query-list.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/show.js, src/components/scroll-view/scroll-view.js, src/components/search-form/search-form.js, src/components/settings-root-proxy/settings-root-proxy.js, src/components/title/edit/title-edit.js, src/components/toaster/toaster.js, src/components/toggle-switch/toggle-switch.js, src/index.js, src/routes/application/application.js, src/routes/package-edit.js, src/routes/package-show.js, src/routes/provider-show.js, src/routes/resource-edit.js, src/routes/resource-show.js, src/routes/settings-knowledge-base.js, src/routes/settings-root-proxy.js, src/routes/title-edit.js, tests/harness.js
Among the changes that React 17 brings to the table, several problematic component lifecycle hooks are now deprecated and need to be removed from the codebase. In order to adopt the latest version of the AirBnB eslint rule-set we need to go through the code and convert away from these old lifecycle hooks to make sure our builds are not failing on a big ol' pile of deprecation warnings.
The deprecated hooks are: 
```
componentWillMount
componentWillReceiveProps
componentWillUpdate
```
According to the react documentation and a few helpful [blog posts](https://hackernoon.com/problematic-react-lifecycle-methods-are-going-away-in-react-17-4216acc7d58b) there are some new methods to use to avoid using the old stuff.
The new hooks are:
```
UNSAFE_componentWillMount …
```
=> UIEH-382: Refactor out React17 deprecated lifecycle hooks

.eslintignore, package.json, src/components/impagination.js, src/components/navigation-modal/navigation-modal.js, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/package/show/package-show.js, src/components/query-list/query-list.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/show.js, src/components/scroll-view/scroll-view.js, src/components/search-form/search-form.js, src/components/search-paneset/search-paneset.js, src/components/toaster/toaster.js, src/components/toggle-switch/toggle-switch.js, src/routes/search.js, yarn.lock
- Cleans up some component declaration ordering.
- Disables the warnings for the remaining lifecycle hook deprecations.
- Adds `.eslintignore` to improve linting performance.
=> Upgrade eslint-config-stripes to 2.0.2

.circleci/config.yml, package.json, yarn.lock
CircleCI has nicer test summary UI when results are reported in JUnit-style XML.
Resolves https://issues.folio.org/browse/UIEH-239
Use `stylelint-junit-formatter` reporter.
=> UIEH-239 Generate stylelint JUnit-style report

.circleci/config.yml
CircleCI has nicer test summary UI when results are reported in JUnit-style XML.
Resolves https://issues.folio.org/browse/UIEH-238
Use `eslint`'s built-in `junit` reporter.
=> UIEH-238 Generate ESLint JUnit-style report

src/components/search-paneset/search-paneset.css
The "+ New" button on search pages no longer matched other FOLIO modules.
Related: https://issues.folio.org/browse/STCOM-301
=> Match padding of other FOLIO New buttons

src/components/package/show/package-show.js, tests/custom-package-show-selection-test.js, tests/package-add-new-titles-test.js, tests/package-search-test.js, tests/package-selection-test.js, tests/pages/package-edit.js, tests/pages/package-show.js
The "Select / Deselect" toggle switch was increasingly out of place in
the current UI so we're abandoning it in favor of an action in the
pane header.  Additionally we're adding a button inline with the field
if the package is not in the librarian's holdings.  This latter piece
should eliminate any ambiguity if a new user is approaching a package
and unsure how to select it.
This changed the flow on the page fairly significantly.  Altering the page required some business logic changes that were led by @cherewaty and coordinated with @elrickvm so the resource show page and package show page are in parity.  Combing through the tests was more challenging - many tests were no longer relevant and were dropped and in one case a test required some structural realignment.  The interactor also …
=> UIEH-406: Holding status: package show page: Ability to add/remove the entire package

docs/data-layer.md
The data layer in eHoldings is pretty unique. We should have some documentation about it
There was some old documentation, but it was written before some refactoring happened and was also more about why we moved away from reducers and actions for each individual type of resource.
I gave a walkthrough of the data layer not too long ago, so I took my notes from that and added some paragraphs & examples. I didn't spend too much time on it, so it's not nearly as details as it could be, and just focuses on how to use the data layer and where to debug it.
- Not sure if I should elaborate somewhere I didn't. Hoping some reviews will suss that out.
- Also wasn't sure of where docs should live, so I just created a `docs` directory. Let me know if anybody thinks it should go somewhere else.
=> Add data layer documentation

src/routes/package-create.js, src/routes/package-edit.js, src/routes/package-show.js, src/routes/provider-show.js, src/routes/resource-edit.js, src/routes/resource-show.js, src/routes/search.js, src/routes/settings-knowledge-base.js, src/routes/settings-root-proxy.js, src/routes/settings.js, src/routes/title-create.js, src/routes/title-edit.js, src/routes/title-show.js
Document titles are part of the essential UX for any browser-based app.
Use `TitleManager` introduced in https://github.com/folio-org/stripes-core/pull/324
I don't love reaching into the `stripes-core` directory structure, but `stripes-core` doesn't have an `index.js` that exports anything.
=> Add document titles

src/components/package/edit-custom/custom-package-edit.js
The i8ln translations pull from a file and in order for the translation to match up with their respective location in the DOM the naming conventions have to match.
- Update and match naming conventions
=> UIEH- 496 Fix i8ln naming in custom package edit

src/components/package/_fields/name/package-name-field.js, src/components/title/_fields/name/title-name-field.js, src/components/title/_fields/package-select/package-select-field.js, translations/ui-eholdings/en.json
Per https://issues.folio.org/browse/UIEH-448, we are supposed to indicate that certain fields are required while creating or editing custom packages and custom titles.
- We tried using the *required* prop in Stripes Components TextField and Select but they did not work per our expectations. We figured that setting those props had nothing to do with the needed asterisk. Moreover, if we set those props, we figured that the browser validation was superseding our redux-form validations.
- We modified our approach to just add an asterisk next to the label referring to what ui-inventory module does.
- I was able to verify the change locally for custom packages and new custom title creation but not edit page of custom title since there seems to be a different error in loading custom titles at …
=> UIEH-448: Add * for certain required fields in custom packages and custom titles

src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/routes/resource-edit.js, src/routes/resource-show.js, tests/custom-resource-edit-embargo-test.js, tests/custom-resource-edit-selection-test.js, tests/custom-resource-edit-visibility-test.js, tests/managed-resource-edit-embargo-test.js, tests/managed-resource-edit-visibility-test.js, tests/pages/resource-edit.js, tests/pages/resource-show.js, tests/resource-edit-custom-title-test.js, tests/resource-edit-deselection-test.js, tests/resource-edit-managed-title-in-custom-package-test.js, tests/resource-edit-managed-title-test.js, tests/resource-edit-selection-test.js
eHoldings users are able to manage their holdings by adding or removing a resource from their holdings. Here we are also providing them that ability when in the 'edit' mode of a resource aka package-title. eHoldings has the concept of a managed-resource and a custom-resource and even though the behavior slightly differs between the two types the base is the same -- a user managing the status of their holdings.
Prior this area used a toggle switch but we are refactoring towards a explicit button and action
from the dropdown to conform with the UX from other FOLIO applications.
To ensure that the eHoldings UX is inline with other FOLIO applications:
- Add a button which allows a user to add a resource to their holdings when the resource is unselected.
- Move the removal of a resource action …
=> UIEH-405 Refactor resource-edit page holding status

src/routes/resource-show.js
Sending a requests to remove a resource that contains contributors will fail if those elements on the model are not cleared out before the request is sent.
- Ensure that contributors and contributorsList are cleared out and sent in the requests are empty elements.
*Before:*
*After:*
=> UIEH-504 Clear contributors and contributorsList before delete requests

package.json, src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/resource/_fields/custom-coverage/resource-coverage-fields.js, yarn.lock
Changes in https://github.com/folio-org/stripes-components/pull/487 needed these updates to `Datepicker` usage.
The `format()` prop on Redux Form `<Field>` takes care of the date transformation we need to do from `YYYY-MM-DD` to whatever the user's locale is.
Seems to work with the current iteration of the `Datepicker` as well, so might as well get it in.
https://redux-form.com/7.4.2/docs/api/field.md/#-code-format-value-name-gt-formattedvalue-code-optional-
=> Use ReduxForm format() on Datepickers

src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/routes/package-edit.js, tests/custom-package-edit-selection-test.js, tests/custom-package-edit-visibility-test.js, tests/managed-package-edit-add-new-titles-test.js, tests/managed-package-edit-selection-test.js, tests/managed-package-edit-visibility-test.js, tests/pages/package-edit.js, tests/pages/package-show.js, translations/ui-eholdings/en.json
The "Select / Deselect" toggle switch is totally out of place now on the edit page, so this PR is to bring the edit page back in line with the pattern already on the show page. This replaces the toggle with an "add" button when deselected and a set of actions in the pane header.
*Before*
*After*
=> UIEH-407: Change holding status toggle into a button on package-edit

src/components/package/show/package-show.js, src/components/package/show/selection-status.js, src/redux/package.js, src/routes/package-show.js, tests/package-show-test.js, tests/pages/package-show.js, translations/ui-eholdings/en.json
The answer to the question "is a package selected?" Is not a simple binary yes or no. All of the titles in a package can be selected, none of the titles in a package can be selected, or some of the titles in the package can be selected. However, packages where _some_ of the titles are selected can only be removed entirely and added entirely in order to make that package _completely_ selected.
This PR introduces the ability to take a package that has some titles selected and select all of the package in one interaction.
See https://issues.folio.org/browse/UIEH-442 for details.
To accomplish this we add two new interactions:
1. We now differentiate between "selected" and and "x of total selected" in the holdings status of a package. In the case where only some of the titles in a package are …
=> UIEH-442 Add partially selected packages to holdings

src/components/external-link/external-link.css, src/components/external-link/external-link.js, src/components/external-link/index.js, src/components/resource/show.js, tests/pages/resource-show.js, tests/resource-show-test.js
Per https://issues.folio.org/browse/UIEH-129, we are supposed to display an external link icon next to managed/custom url in resource show page. Implement that functionality.
- Create a functional component named `ExternalLink`
- Use Stripes-components Icon component within the anchor link
- Add associated unit tests
=> UIEH-129: External Link Component in Resource Show

tests/package-selection-test.js
The package selection tests relying on the timing of mirage responses have been flaking lately, which was probably inevitable. We want to refactor those to have complete control over when the mirage response resolves.
I noticed one incorrectly placed assertion. It checks to see if the package now shows up as selected, which now shouldn't happen until after the endpoint resolves.
Hopefully this will cut down the flakiness until we can solve the root problem.
=> Remove outdated assertion

src/components/search-paneset/search-paneset.js, src/routes/search.js, tests/provider-search-test.js
There is currently a bug wherein selecting a search filter without having a query string in the "Search" field will cause the UI to blow up, showing an uncaught error to the user.
It turns out that there is one place where we should be doing a null check to ensure we're not accessing properties on an object that is not there. In addition I found a spot where a boolean property was being coerced into a string somehow.
=> UIEH-477: Add null checks to avoid trying to focus search results when there are none

tests/package-selection-test.js
https://github.com/folio-org/ui-eholdings/pull/488 and https://github.com/folio-org/ui-eholdings/pull/490 appeared to be good solutions, but these tests are still flaky on `master`: https://circleci.com/gh/folio-org/ui-eholdings/5688
Skipping them for now to unblock other PRs.
=> Skip flaky loading tests

src/components/details-view/details-view.css
Resolves: [UIEH-506](https://issues.folio.org/browse/UIEH-506)
When navigating to a provider/package/title detail record, we are focusing the main page header to inform those using assistive technology of the context switch. On some browsers the focus outline looks jagged and wonky, [UIEH-506](https://issues.folio.org/browse/UIEH-506) was opened to address that look.
After discussing solutions with @Robdel12, we came to the conclusion that removing focus outlines from headings makes the most sense. Seeing as headings are not part of the natural tab order of the web and we are mainly focusing the heading for the benefit of screen-readers (which will outline the focused element anyway) it feels more natural to remove outlines from h-tags in eholdings.
*Before*
*After*
=> UIEH-506: Remove focus outlines from all headings in details view

.stripesclirc.js, README.md
Removes Frontside's demo Okapi cluster as the default back end when running `yarn start`. Instead the default falls back to Stripes CLI's, `http://localhost:9130`.
The dev environment can still point to non-default Okapi clusters with `yarn start --okapi https://okapi.frontside.io`.
=> Remove okapi.frontside.io as default dev back end

src/components/details-view/details-view.js, tests/pages/search-modal.js, tests/provider-show-package-search-test.js
Per [UIEH-320](https://issues.folio.org/browse/UIEH-320) we currently do not have a way to reset all filters back to default within the search modal. This change adds that function to the modal.
With this change I am removing the feature that hides the modal footer and buttons that I put in with [UIEH-371](https://issues.folio.org/browse/UIEH-317) in favor of always displaying the buttons, but just enabling/disabling them when applicable. The `Reset all` button also uses the `stripes-components` modal button styles for consistency.
=> UIEH-320 - Provider Detail: List of Packages: Search Within Modal : Unable to Reset Search

src/components/package/create/package-create.js, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/package/show/package-show.js, src/components/provider-show/provider-show.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/show.js, src/components/title/show/title-show.js, tests/custom-resource-edit-embargo-test.js, tests/pages/resource-show.js, tests/resource-coverage-statement-test.js, tests/resource-custom-coverage-test.js, tests/resource-embargo-test.js, tests/resource-managed-coverage-test.js, translations/ui-eholdings/en.json
To apply the same organizational strategy to detail records that other FOLIO modules have, use the `stripes-components` `<Accordion>`.
- Accordions only applied to show routes, not edit routes. It's recommended we keep it that way, so fields that have a validation error can't end up being hidden within a closed accordion.
- Accordions not applied to infinitely scrolling lists yet.
- Show routes and their accompanying edit routes always have the same order of headlines/sections.
- "Holding status" is always first.
- Does not include expand all / collapse all functionality for accordions.
- Provider information
- Packages
- Title information
- Packages
- Holding status
- Package information
- Package settings
- Coverage settings
- Titles
- Holding status
- Resource information
- Resource …
=> Use Accordions on detail record pages

src/components/details-view/details-view.js, src/components/provider-show/provider-show.js, src/components/search-modal.js, src/routes/provider-show.js
This PR is part of a quest issue #482 that will address [Provider Detail Record (Show): Apply Accordion to List of Packages](https://issues.folio.org/browse/UIEH-438)
The purpose of this PR is to refactor Search Modal functionality into it's own component. This PR doesn't have any user perceivable change but it does set us up to reuse Search Modal in the future. All of the tests should pass as they did previously. 
Instead of rendering Search Modal in Detail View, it is now being rendered in Provider Show route and passed to the view component. The View component then renders is it correct place. This eliminates the need to drip props through view component. 
There is something different here that is worth noting. I'm using `key` prop on Search Modal component to reset the query. …
=> Refactor Search Modal into its own component

bigtest/interactors/package-edit.js, bigtest/interactors/package-show.js, bigtest/interactors/selection-status.js, bigtest/tests/custom-package-edit-selection-test.js, bigtest/tests/custom-package-edit-test.js, bigtest/tests/custom-package-edit-visibility-test.js, bigtest/tests/custom-package-show-selection-test.js, bigtest/tests/managed-package-edit-add-new-titles-test.js, bigtest/tests/managed-package-edit-selection-test.js, bigtest/tests/managed-package-edit-visibility-test.js, bigtest/tests/package-add-new-titles-test.js, bigtest/tests/package-custom-coverage-test.js, bigtest/tests/package-selection-test.js, bigtest/tests/package-show-test.js, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/package/selection-status.js, src/components/package/show/package-show.js, src/redux/package.js, src/routes/package-edit.js, src/routes/package-show.js, translations/ui-eholdings/en.json
[UIEH-476 - Holding status: package edit page: Partially Selected Package Handling](https://issues.folio.org/browse/UIEH-476)
resolves #484 
The Managed Package Edit Page currently displays a holding status area with 2 states:
- Selected
- Not Selected (with an `Add to holdings` button)
The menu area also shows `Remove from holdings` or `Add to holdings` depending upon state.
This PR enhances the Managed Package Edit Page to support partially selected packages. (ie a package that does not have all of its titles selected). Specifically, it allows the user to completely select a partially selected package.  It adds a 3rd state:
- (# selected titles)  of (# total titles) titles selected (with an `Add all to holdings` button)
Added menu item `Add all to holdings`
Additional Items Addressed:
- …
=> UIEH-476 - Package Edit Page - Partially Selected Package Handling

src/components/list/list.css, src/components/list/list.js, src/components/package-search-list.js, src/components/provider-search-list.js, src/components/query-list/query-list.js, src/components/scroll-view/scroll-view.js, src/components/title-search-list.js
https://github.com/folio-org/ui-eholdings/pull/500 created a ton of whitespace and uncomfortable shifting of the search results when clicking a result.
Don't set a `max-width` for the search results. Continue setting a max width on detail records.
This implementation feels a little clunky - we probably have too much coupling between the components used for search results and showing related item lists.
=> Don’t set max width for search results

src/components/details-view/details-view.js, src/components/package/_fields/name/package-name-field.js, src/components/package/create/package-create.js, src/components/package/edit-custom/custom-package-edit.js, src/components/resource/_fields/custom-coverage/resource-coverage-fields.js, src/components/title/_fields/name/title-name-field.js, src/components/title/create/title-create.js, src/components/title/edit/title-edit.js, src/components/toaster/toaster.js
Addresses a few different classes of warnings that were popping up on test runs (https://circleci.com/gh/folio-org/ui-eholdings/6310):
```
ERROR: 'Warning: Failed prop type: The prop `handleExpandAll` is marked as required in `DetailsView`, but its value is `undefined`.
```
`sections` and `handleExpandAll` were set as required props on `<DetailsView>`, but it doesn't appear that they're actually required.
```
ERROR: 'Warning: Failed prop type: Invalid prop `error` of type `object` supplied to `TextField`, expected `string`.
```
`redux-form` expects the message in `errors` to be a string, which means we can't use `<FormattedMessage>` or `<FormattedDate>` in error messages.
```
ERROR: 'Warning: Failed prop type: Invalid prop `error` of type `boolean` supplied to `TextField`, expected …
```
=> Clean up warnings

src/components/key-value-columns/index.js, src/components/key-value-columns/key-value-columns.css, src/components/key-value-columns/key-value-columns.js, src/components/package/show/package-show.js, src/components/resource/show.js, src/components/title/show/title-show.js
To visually resemble other FOLIO modules, lay out the "____ information" section of detail records in columns.
Resolves https://issues.folio.org/browse/UIEH-206 and https://issues.folio.org/browse/UIEH-507.
- Created `<KeyValueColumns>` that can wrap the collections of `<KeyValue>` pairs. To create a column, use a `<div>`.
- The most difficult decision on each was where to place the break:
- Provider: none, so that "_____ selected" is always above "Total ______" like a fraction
- Package: before "Titles selected" and "Total titles" counts
- Title: just tried to pick a halfway point; after identifiers, before subjects
- Resource: break is between fields inherited from the title and fields inherited from the package
- When the detail record container is less than 630px wide, there's only a …
=> Lay out detail record data with KeyValueColumns

bigtest/interactors/settings-root-proxy.js, bigtest/interactors/settings.js, bigtest/tests/backend-configuration-test.js, bigtest/tests/settings-root-proxy-test.js, src/components/search-paneset/search-paneset.js, src/components/settings-detail-pane/settings-detail-pane.css, src/components/settings-detail-pane/settings-detail-pane.js, src/components/settings-knowledge-base/settings-knowledge-base.css, src/components/settings-knowledge-base/settings-knowledge-base.js, src/components/settings-root-proxy/settings-root-proxy.css, src/components/settings-root-proxy/settings-root-proxy.js, translations/ui-eholdings/en.json
Other FOLIO modules have a Save button in the pane header, instead of at the bottom of a form. Completes https://issues.folio.org/browse/UIEH-508
Put the Save button in the pane header `lastMenu` and the Cancel action in the pane header action items dropdown.
- The root proxy page has some odd loading behavior (see GIF below)
- The interactors for clicking items in pane header dropdowns can be DRYed up
=> UIEH-508 Move Save button to header in settings forms

src/components/resource/show.js
Javascript Template strings expected a string to be use in order to create the resulting string ouput. Since we were passing a component it was rendering to screen [Object, Object] and not the actual
string representation.
- use intl.formatMessage to return a string over using the component
=> UIEH-516 Use intl.format within template string

src/components/title/show/title-show.js
Resolves [UIEH-511](https://issues.folio.org/browse/UIEH-511)
This PR is about replicating the work @taras and @cherewaty did on the provider detail page to collapse/expand the package list using the `<Accordion>` from stripes-components.
As it turns out, this ticket was pretty much resolved by #482.
All that I needed to do was fix a spot in the UI where the number of results was displayed as `NaN`
=> UIEH-511: Fix "Results found NaN" on the title-show page

translations/ui-eholdings/en.json
Intl'ed string needed Unicode number instead of HTML entity for ampersand.
=> Fix ampersand in Search Filter pane header

package.json, src/components/details-view/details-view.js, yarn.lock
[UIEH-514](https://issues.folio.org/browse/UIEH-514)
The purpose of this PR is to make sure that list expands to consume all available space after accordion container is collapsed. 
Use [react-measure](https://github.com/souporserious/react-measure) component to watch when the accordion changes size and call `handleLayout` to update the size of the list.
My original strategy was to add hooks to Accordion component that would allow me to call the callback after collapse/expand. It turned out that it's extremely difficult to figure out how to test that a callback was called after RAF. Ultimately, this approach is better because it relies on composition of a specialized component over adding props to common components.
=> UIEH-514: Use react-measure to automatically resize accordion container

src/components/search-form/search-form.css
Resolves https://issues.folio.org/browse/UIEH-517
The search form had a min width of 320px, but the pane with or without a scrollbar was sized at 320px. That meant the `1em` padding was behind the scrollbar instead of to the left of it.
`min-width` reduced to `200px`.
=> UIEH-517 Reduce search form min width

src/components/navigation-modal/navigation-modal.js
To resolve bug [UIEH-518](https://issues.folio.org/browse/UIEH-518).  
In the `NavigationModal` component there were cases in which we would try to access `this.context` from within the class constructor. This is a simple fix for these cases.
=> UIEH-518: Fix accessing context in the scope of a constructor

karma.conf.js, package.json, yarn.lock
Upgrades `stripes-cli`, `stripes-components`, and `stripes-core` used by `ui-eholdings`.
Probably resolves:
=> Upgrade stripes cli/components/core

src/components/package/show/package-show.js, src/components/search-modal/search-modal.js
This is a very small fix to make sure the newly added Modal transition can run correctly. 
Because of the condition wrapping around the `<Modal>` it would only transition when entering. Now it works both when the modal enters and leaves the DOM.
Also fixed a tiny linting error.
=> Minor search form modal fix

src/components/resource/_fields/custom-embargo/custom-embargo-fields.js, src/components/search-modal/search-modal.js, src/components/toaster/toaster.js, src/routes/provider-show.js
Newer `eslint` rule that's not applied to this repo yet but appears in `eslint-config-stripes@3`: [`react/no-access-state-in-setstate`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md)
Use callbacks with `setState` to prevent cases where an old state might be used.
=> Follow react/no-access-state-in-setstate

bigtest/interactors/package-show.js, bigtest/interactors/provider-show.js, bigtest/interactors/search-modal.js, bigtest/network/config.js, bigtest/tests/package-show-titles-search-test.js, src/components/package/show/package-show.js, src/components/search-modal/search-modal.js, src/components/utilities.js, src/routes/package-show.js, src/routes/search.js
Allow the ability for you to filter packages nested resources (which are titles). 
I started with implementing the search modal inside of the `package-show` detail view. A lot of the work was getting the mirage config setup to where we can filter & search nested package resources. Once that work was done I was able to whip up some tests to make sure filtering titles worked properly. 
One thing I noticed while working through this is we could leverage the composability of interactors. We still have a lot of _page objects_. It would be nice to start to refactor our interactors to map to their component. This would allow us to compose interactors the same way we can compose the components. 
For example, the details view component could have it's own interactor. Then we could refactor our …
=> [UIEH-214] Implement filtering for package resources

bigtest/interactors/resource-edit.js, bigtest/tests/resource-edit-custom-title-test.js, bigtest/tests/resource-edit-managed-title-test.js, src/components/resource/_fields/custom-coverage/resource-coverage-fields.css, src/components/resource/_fields/custom-coverage/resource-coverage-fields.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, translations/ui-eholdings/en.json
Changes coverage date selection UI for resources (https://issues.folio.org/browse/UIEH-526).
Does not yet change coverage statement selection; will address in separate PR.
Lean more heavily on the `ResourceCoverageFields` component and the power of `redux-form` `FieldArray`.
=> UIEH-526 Adjust resource coverage date selection UI

bigtest/interactors/provider-edit.js, bigtest/tests/provider-edit-test.js, src/components/provider/edit/provider-edit.js, translations/ui-eholdings/en.json
Add a message in place of fields in edit view on providers with no packages selected. 
Since this is a simple conditional, it should be easy to add onto later with future fields.
=> [UIEH-530] Provider Detail: Show message on edit form when no packages are selected

src/components/preview-pane/preview-pane.css, src/components/search-pane-vignette/search-pane-vignette.css, src/components/search-pane-vignette/search-pane-vignette.js, src/components/search-pane/search-pane.css, src/components/search-paneset/search-paneset.css, src/components/search-paneset/search-paneset.js
Broken in https://github.com/folio-org/ui-eholdings/pull/525
The layout needs two different `<SearchPaneVignette>`s: one behind the search filters pane and one behind the detail record preview pane. At some sizes they can simultaneously appear.
The `hideFilters` refactor lifted the state up for that a level... but there's one use case it didn't account for:
- When I'm on a mobile-sized screen and I click "Search", I want to be taken to the results. BUT on a larger screen, that exact same interaction shouldn't hide the filters pane. It seems like we need one more boolean in the state to deal with that.
=> Fix search paneset vignette behavior

src/components/coverage-date-list/coverage-date-list.js, src/components/resource/_fields/coverage-statement/coverage-statement-fields.css, src/components/resource/_fields/coverage-statement/coverage-statement-fields.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/edit.js, translations/ui-eholdings/en.json, yarn.lock
Part of https://issues.folio.org/browse/UIEH-526
Bulks up the `CoverageStatementFields` component with radio buttons to indicate whether the end patron will see dates or a custom coverage statement.
Resources belonging to a custom title don't need to show the managed coverage dates option - that should be the final PR needed to wrap up UIEH-526.
Gotcha I ran into: when dealing with radio buttons and Redux Form `Field`s, `type="radio"` on the `<Field>` manages the input's `checked` for you.
=> UIEH-526 Create coverage display section on resource forms

docs/data-layer.md
Issue: https://issues.folio.org/browse/UIEH-519
We want future maintainers to understand motivations for why we did something. In this case, we want them to understand why we did not use Stripes Connect and created our own data layer.
[Rendered](https://github.com/folio-org/ui-eholdings/blob/ca49fcc76d6953582c702cbb8bf0abb30d9c8c27/docs/data-layer.md#motivation)
- Added a paragraph to explain our motivations
- Added a table of contents to the document
=> Add a section about motivations for writing our own data layer

src/components/title/_forms/add-to-package.js, src/components/title/show/title-show.js
Display more than 25 packages when adding a title to a custom package.
Resolves a portion of [UIEH-532](https://issues.folio.org/browse/UIEH-532)
We are currently setting 25 as the default page size on the front-end in the model, so the list can only display a max of 25 items. However, `customPackages` is a collection model that has this count attribute on it that is set to 100. So, the list does actually get all of the items beyond the displayed 25, but even when the page size is changed, we are only able to display 100 of them max. This is due to a cap in rmapi. As a temporary solution, I've set the page size to the max limit of 100. I've also added a filter within `AddToPackage` that cuts out the remaining results that do not display so that there is not a large chunk of blank-space in …
=> UIEH-532  Title, 'add to custom package' does not show all packages

bigtest/interactors/provider-edit.js, bigtest/interactors/provider-show.js, bigtest/network/config.js, bigtest/network/factories/provider.js, bigtest/network/factories/token.js, bigtest/network/models/token.js, bigtest/tests/provider-edit-token-test.js, bigtest/tests/provider-show-test.js, src/components/provider/_fields/token/index.js, src/components/provider/_fields/token/token-field.css, src/components/provider/_fields/token/token-field.js, src/components/provider/edit/provider-edit.js, src/components/provider/show/provider-show.js, src/components/provider/token-display.js, src/redux/provider.js, src/routes/provider-edit.js, translations/ui-eholdings/en.json
Per https://issues.folio.org/browse/UIEH-176, users should have the ability to display and edit provider level tokens.
Backend support for provider level tokens has been added with the following
PR https://github.com/folio-org/mod-kb-ebsco/pull/89
There are 3 possible states for a provider with respect to tokens:
(1) Provider does not support tokens - nil value is returned for providerToken
(2) Provider supports tokens but does not have a token value set - providerToken object does not have a value
(3) Provider supports tokens and has a token value set - providerToken object has a value
Provider Token object that is returned from mod-kb-ebsco Providers GET request includes the following fields (factName, prompt, helpText and value)
```
"providerToken": {
"factName": "[[galesiteid]]", …
```
=> UIEH-176 Display and Edit Provider Level Tokens

src/components/provider/_fields/proxy-select/proxy-select-field.js, src/components/provider/proxy-display.js
Per https://issues.folio.org/browse/UIEH-537, we identified an issue where there can be a case discrepancy between proxy set at the provider level and the list of proxies that we get from the root level. RM API, apparently, accepts proxy updates case insensitively without reporting an issue. So, it is quite possible we run into this issue on our end. 
- Add case insensitive checks for proxy list and proxy updates.
=> UIEH-537: Case insensitive checks for proxies

src/components/search-paneset/search-paneset.css, src/components/search-paneset/search-paneset.js
The search filters pane "Apply" button lost its style information, so was showing up too often:
https://github.com/folio-org/stripes-components/pull/558 broke passing a `className` into a `<Button>`. Switched to using `buttonClass` prop instead.
Shown on fairly narrow screen, Apply button disappears at larger sizes.
=> Fix Apply button styles

bigtest/interactors/package-show.js, bigtest/tests/package-visibility-test.js, src/components/package/show/package-show.js
https://issues.folio.org/browse/UIEH-542
Remove duplicate hidden message that appears on Package Show Page and adjust unit tests accordingly
Before
After
=> UIEH-542 - Remove second hidden reason on package show page

.circleci/config.yml, karma.conf.js
The simplifications here to the Circle and Karma configs should make it much easier to run this stuff locally or on any other CI (like Jenkins).
Also:
- starts running Circle on node 10 (previously 9)
- makes Circle config easier to read
- IE 11 removed until a lot more attention paid to it.
=>  Streamline Circle config

package.json
Since, we released v1.0.0, we want to ensure that going forward, builds get a new version. Bump up version for that reason.
=> Bump version up for further releases

.circleci/config.yml
With all tests now using BigTest page objects, we should see far fewer flaky test situations with Firefox on a Linux container.
=> UIEH-240 Run Firefox tests on CircleCI

src/routes/search.js
Resolves https://issues.folio.org/browse/UIEH-556
The search experience only needed to lean on the URL changing and didn't explicitly have to call `this.search()` to fire off the server event.
=> UIEH-556 Remove duplicate search call to server

.npmrc, package.json, yarn.lock
FOLIO has two NPM repositories: https://repository.folio.org/repository/npm-folio/ and https://repository.folio.org/repository/npm-folioci/.
- `npm-folioci` publishes a snapshot tag on every PR merge of any `folio-org` JS repo
- `npm-folio` only publishes explicitly created release tags
Only use `npm-folio`.
- encourages an experience more like using registry.npmjs.org
- only uses explicitly released packages; we'll never magically receive unreleased code
=> Generate lockfile from npm-folio registry

src/components/package/_fields/custom-coverage/package-coverage-fields.css, src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/repeatable-field/ReduxFormFieldArray.js, src/components/repeatable-field/RepeatableField.css, src/components/repeatable-field/RepeatableField.js, src/components/repeatable-field/index.js, src/components/resource/_fields/custom-coverage/custom-coverage-fields.css, src/components/resource/_fields/custom-coverage/custom-coverage-fields.js, src/components/resource/_fields/managed-coverage/managed-coverage-fields.css, src/components/resource/_fields/managed-coverage/managed-coverage-fields.js, src/components/title/_fields/contributor/contributor-field.css, src/components/title/_fields/contributor/contributor-field.js, src/components/title/_fields/identifiers/identifiers-fields.css, src/components/title/_fields/identifiers/identifiers-fields.js, test/bigtest/interactors/package-create.js, test/bigtest/interactors/package-edit.js, test/bigtest/interactors/resource-edit.js, test/bigtest/interactors/title-create.js, test/bigtest/interactors/title-edit.js
Abstract repeatable field design into a component that works with or without Redux Form.
- Uses camelCase CSS to match `stripes-components` practices
- Only design change for eHoldings: remove row button is now a trash can instead of a circle X
- Will replace with upstream `stripes-components` version when that gets released
Example usage:
```
<FieldArray
addLabel={intl.formatMessage({ id: 'ui-eholdings.package.coverage.addDateRange' })}
component={RepeatableField}
emptyMessage={
initialValue.length > 0 && initialValue[0].beginCoverage ?
intl.formatMessage({ id: 'ui-eholdings.package.noCoverageDates' }) : ''
}
name="customCoverages"
renderField={this.renderField}
/>
```
=> STCOM-292 Create new RepeatableField component

package.json, yarn.lock
eHoldings was relying on an upstream `rxjs` instead of specifying its own dependency. At some point the upstream got bumped up to `6.x`, so the `5.x`-style imports in eHoldings broke.
Thanks @rjruizes for the report.
Lock in eHoldings to use `rxjs` `5.x`.
=> Use rxjs 5

src/routes/search.js, yarn.lock
Per https://issues.folio.org/browse/UIEH-558, input text in the search field is being reset due to re-rendering of the search pane. This PR attempts to fix the issue.
- In search.js, conditionally modify when searchString should be updated instead of updating its state always like we were doing before.
- Since `componentWillReceiveProps` lifecycle hook is going to be deprecated from React 17, replace the use of `componentWillReceiveProps` with `getDerivedStateFromProps` and `componentDidUpdate` as suggested here: https://hackernoon.com/replacing-componentwillreceiveprops-with-getderivedstatefromprops-c3956f7ce607
- Ensure that all unit tests are passing with these changes.
https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization …
=> UIEH-558 - Fix for issue with multiple re-rendering of the search pane

src/components/details-view/accordion-list-header.js, src/components/details-view/details-view.js, src/components/package/show/package-show.js, test/bigtest/tests/package-show-titles-search-test.js, test/bigtest/tests/provider-show-package-search-test.js, translations/ui-eholdings/en.json
Per https://issues.folio.org/browse/UIEH-546, there is currently a discrepancy in the 
total number of titles displayed in package detail information and number of records found in the title result list accordion. This specifically happens for a package when the number of related records (ie titles) found is greater than 10,000. This is currently a limitation in RM API as it does not return the exact number of titles and returns 10,000 instead. In these cases, UI should display `Over 10,000` as the number of records found to indicate this fact.
- Check `totalResults` which is returned from a package's related resources request
For example - `eholdings/packages/19-5207/resources?page=1`
- Total results is available as `model.resources.length` in PackageShow Page. Package associated …
=> UIEH-546: Update number of records found when results limited to first 10K

package.json
`react-router-prop-types` needs to be a `dependency` for when eHoldings gets pulled into a FOLIO platform.
```
ERROR in ./node_modules/@folio/eholdings/src/components/navigation-modal/navigation-modal.js
Module not found: Error: Can't resolve 'react-router-prop-types' in '/home/jenkins/folio-testing-platform/node_modules/@folio/eholdings/src/components/navigation-modal'
@ ./node_modules/@folio/eholdings/src/components/navigation-modal/navigation-modal.js 13:0-59 151:11-31
@ ./node_modules/@folio/eholdings/src/components/navigation-modal/index.js
@ ./node_modules/@folio/eholdings/src/components/resource/edit-custom-title/resource-edit-custom-title.js
@ ./node_modules/@folio/eholdings/src/components/resource/edit-custom-title/index.js
@ …
```
=> Move react-router-prop-types to dependencies

.stripesclirc.js
These configs are no longer necessary. `folio-ui-eholdings-deploy` handles the tenant for the folio.frontside.io deployment. Removing that default makes it really easy to point to a different cluster with a different tenant, like `yarn start --okapi http://folio-testing-backend01.aws.indexdata.com:9130`
=> Remove unnecessary CLI defaults

src/components/search-form/search-form.css, translations/ui-eholdings/en.json
Makes eHoldings look more like the `SearchAndSort` changes in https://github.com/folio-org/stripes-smart-components/pull/307
=> Adjust search pane styles

src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/redux/model.js
SonarCloud reported two classes of bugs for `ui-eholdings`:
**Change this condition so that it does not always evaluate to "true"; some subsequent code is never executed.**
The instances of `getDerivedStateFromProps` where this came up can return an empty object instead of `null`.
**Replace this with a constructor function.**
I made the instantiation a little wordier to compensate for it not liking `new this()`.
=> Clean up SonarCloud bug report

src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, test/bigtest/interactors/package-edit.js, test/bigtest/tests/custom-package-edit-selection-test.js, test/bigtest/tests/managed-package-edit-selection-test.js
Per https://issues.folio.org/browse/UIEH-453, users should be able to collapse and expand the sections of custom/managed package edit pages.
- Add the Accordion component from Stripes-components
- Wrap sections of the selected custom/managed package in edit mode. The names of the sections: "Holding Status", "Package settings", "Coverage settings"
- In local state create property containing the status of the sections(whether a section is expanded)
- Pass appropriate props to Accordion components
- Add associated tests
=> UIEH-453: Apply accordions for selected managed/custom package in edit mode

src/components/title-search-filters.js, test/bigtest/interactors/search-modal.js, test/bigtest/interactors/title-search.js, test/bigtest/tests/package-show-titles-search-test.js, test/bigtest/tests/title-search-test.js
Users should have the ability to choose in which manner to sort title search results (by relevance or alphabetically)
* Adjust TitleSearchFilters component so that sorting filter appears among other filters 
* Write related tests
=> UIEH-121: add title search results sorting

src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, test/bigtest/interactors/resource-edit.js, test/bigtest/tests/resource-edit-custom-title-test.js, test/bigtest/tests/resource-edit-managed-title-test.js
According to [UIEH-455](https://issues.folio.org/browse/UIEH-455) librarians should be able to expand and collapse any section displayed on the Edit Custom/Managed Resource Detail Record so that they can easily view the section that they most want to review.
- Add the Accordion component from Stripes-components
- Wrap sections of the selected custom/managed resource in edit mode. The names of the sections are "Holding Status", "Resource settings" and"Coverage settings"
- Create a property containing the status of the sections(whether a section is expanded) in a local state.
- Pass appropriate props to Accordion components.
- Add associated tests.
=> UIEH-455: Apply accordions to edit custom/managed resource detail record

src/components/coverage-date-list/coverage-date-list.js, src/components/resource/_fields/coverage-statement/coverage-statement-fields.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/title-search-filters.js, test/bigtest/interactors/resource-edit.js, test/bigtest/interactors/search-modal.js, test/bigtest/interactors/title-search.js, test/bigtest/network/helpers.js, test/bigtest/tests/package-show-titles-search-test.js, test/bigtest/tests/resource-edit-custom-title-test.js, test/bigtest/tests/resource-edit-managed-title-test.js, test/bigtest/tests/title-search-test.js
Per  https://issues.folio.org/browse/UIEH-544, resource edit page displays an incorrect validation error message `validate.errors.coverageStatement.blank` when coverage statement is blank. It should instead display a properly translated message - for example `Statement field cannot be blank if selected.`
- Corrected translation id for error message -- was using `validate.errors.coverageStatement.blank` instead of `ui-eholdings.validate.errors.coverageStatement.blank`
- Added unit tests for both managed and custom resources to confirm display of correct message
- To recreate interactions for blank message to appear- needed to select radio button for coverage statement, clear text area and then re-select radio button for coverage statement
Before:
After:
=> UIEH-544: Correct Error Message for empty coverage statement

src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/resource/_fields/custom-coverage/custom-coverage-fields.js, src/components/resource/_fields/managed-coverage/managed-coverage-fields.js, src/components/utilities.js, src/routes/package-create.js, src/routes/package-edit.js, src/routes/resource-edit.js
This is related to [STCOR-265](https://issues.folio.org/browse/STCOR-265) to get tests to run in consistent timezones.
While investigating, I found that the app _is_ running in the UTC timezone during testing. Poking around in eholdings revealed that it was actually `moment` which was causing the dates to be incorrect.
In other places in eholdings, we are using `.tz('UTC')` to set the timezone to be consistent for manipulation or comparison. We were **not** doing this for the date validation functions.
Moment has a `.utc()` method to set the moment object to UTC mode for every manipulation. All instances of `moment()` were replaced with `moment.utc()` and the existing places that used `.tz()` were also updated to `.utc()`.
It should be safe to do this for manipulation and comparison of …
=> Fix moment usage to UTC

src/components/resource/show.js, src/routes/resource-show.js, test/bigtest/interactors/resource-show.js, test/bigtest/tests/resource-edit-deselection-test.js, test/bigtest/tests/resource-show-test.js, translations/ui-eholdings/en.json
Adds an "Add token" button for redirecting a user to the package edit page where he can add this token.
Jira issue: https://issues.folio.org/browse/UIEH-241
- Add a button from stripes components to the "resource-show" component.
- Add a loader to avoid "Add token" button flickering.
- Add associated unit tests.
When token is needed:
When token is not needed:
=> UIEH-241: Add "Add token" button for the resource detail page which appears when token is needed

test/bigtest/tests/resource-edit-deselection-test.js
While developing UIEH-241, I found that there is one broken test which should check whether a resource deselects after removing it from holdings.
Add mock of the PUT request for sending data to deselect resource.
=> Fix broken test for deselection logic in resource edit component

src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/package/_fields/name/index.js, src/components/package/_fields/name/package-name-field.js, src/components/package/create/package-create.js, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/provider/edit/provider-edit.js, src/components/token/index.js, src/components/token/token-field.js
Most of the validations we're doing in forms are solely on the field level, but we're registering them all at the global level of each `redux-form`. That leads to some clunkier-than-necessary exports of `validate()` functions and `injectIntl()` happening one level higher than it needs to.
Use field-level validations where possible.
I ran into one exception: validating that a coverage end date is after its begin date. Redux Form provides a `<Fields>` component that could handle that in an elegant way, but the `stripes-components` `<Datepicker>` is still too hard-wired to being the child of a `<Field>` to be able to pull that off. When https://issues.folio.org/browse/STCOM-325 is done, we can make that better.
Apply this same pattern to title and resource forms.
=> Use field-level validation on package form

src/routes/application/application.css
The bug appeared due to the `Settings` component change.
As the `Paneset` was deleted from it.
As the result `flex` item was not wrapped in the `flex` container
=> UIEH-571: Fixed Settings - Knowledge Base and Root Proxy Buttons

src/components/title-list-item/title-list-item.css, src/components/title-list-item/title-list-item.js, src/components/title-search-list.js
When searching for a title, sometimes a result doesn't include a publisher name. That would result in blank lines.
- Combine the publication type and publisher name into a single line.
- Show publication type first, since anecdotally the publication type seems to always be defined.
- If both the publication type and the publisher name are present, separate them with a bullet.
- Long publisher names get cut off with an ellipsis.
- Now that all title search results only have two lines, decrease the result height from 80px to 60px.
- Skeleton loading state for title search results updated to only include two lines.
=> Accommodate lack of publisher name in title results

src/components/search-form/search-filters.js, src/components/search-form/search-form.js
Regarding [UIEH-577](https://issues.folio.org/browse/UIEH-577) a user should be able to focus on the Provider/Package/Title tabs to toggle when using a keyboard (TAB) and to easily navigate filters and options. 
In addition, when the user clicks filter options the whole form shouldn't be highlighted. Only the the current option should be outlined.
- Delete tabIndex for title tabs.
- Remove tabIndex of filters' pane, so it won't be focused ever.
- Add role/aria-label and tabIndex to `<RadioButton/>`
=> UIEH-577: Fix Keyboard navigation issues

src/components/title/show/title-show.js, test/bigtest/interactors/title-show.js, test/bigtest/tests/title-show-test.js
Managed title pages shouldn't link to an edit page, since there's nothing editable.
Regression introduced in https://github.com/folio-org/ui-eholdings/pull/569.
Only show the edit link when the title is custom.
Tests added to verify fixed regression.
=> UIEH-582 Don’t show edit link for managed titles

src/components/search-form/search-form.css, src/components/search-form/search-form.js, test/bigtest/interactors/package-search.js, test/bigtest/interactors/provider-search.js, test/bigtest/interactors/title-search.js
The search type switcher element was highly custom, and not using the upstream `<SegmentedControl>`. This PR fixes some style inconsistencies as a band-aid until https://github.com/folio-org/stripes-components/pull/761 appears in a release.
- Switch to using `stripes-components` `<Button>`s.
- Copy `<ButtonGroup>` CSS from https://github.com/folio-org/stripes-components/pull/761.
- Fixes the one extra pixel of border that had been upsetting me for months :)
=> Fix search type picker styles

src/routes/title-edit.js, test/bigtest/tests/managed-title-edit-test.js
Resolves https://issues.folio.org/browse/UIEH-582
As soon as we know that the title's not custom at `/eholdings/titles/:id/edit`, redirect to `/eholdings/titles/:id`.
=> UIEH-582 Prevent visits to managed title edit form

src/components/package/_fields/custom-coverage/package-coverage-fields.js, test/bigtest/tests/package-create-test.js
According to [UIEH-579](https://issues.folio.org/browse/UIEH-579) the user won't be able to add multiple date range in package-edit and package-create.
This PR resolves [UIEH-580](https://issues.folio.org/browse/UIEH-580).
=> UIEH-579: Disallow adding multiple date ranges

src/components/coverage-date-list/coverage-date-list.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, test/bigtest/interactors/resource-edit.js, test/bigtest/tests/resource-edit-custom-title-test.js, test/bigtest/tests/resource-edit-managed-title-test.js
https://issues.folio.org/browse/UIEH-581
There is an issue related to comma separator for custom coverage date ranges on custom and managed title edit pages. The Comma is displaying when there are empty date ranges. The reason is empty objects which are passing to the CoverageDateList component. So the component renders them as empty strings with a comma separator.
- Filter empty date ranges and pass to the CoverageDateList component only filled date ranges.
- Add tests
- Add property type check to CoverageDateList
=> UIEH-581: Fix displaying of the comma separator for custom date ranges

src/components/resource/_fields/custom-embargo/custom-embargo-fields.js, test/bigtest/tests/custom-resource-edit-embargo-test.js, translations/ui-eholdings/en.json
According to [this story](https://issues.folio.org/browse/UIEH-592), an error message should be displayed if user enters a decimal number when editing "Embargo period" field on edit resource page
=> UIEH-592: add check for decimal numbers on custom embargo fields

src/components/package/_fields/name/package-name-field.js, translations/ui-eholdings/en.json
[UIEH-597](https://issues.folio.org/browse/UIEH-597): to decrease character's limit for package name field as it causes a failure on back end. Because actual maximum string length that can be saved to KB is 200 characters.
- change validation for the field from 300 to 200
=> UIEH-597: Change package name length to 200 characters

src/components/resource/_fields/custom-embargo/custom-embargo-fields.js
This PR fixes embargo period placeholder which displays '[object Object]'.
[Related story](https://issues.folio.org/browse/UIEH-593)
=> UIEH-593: fix embargo period placeholder

src/components/title-list-item/title-list-item.js
Cleared up non necessary space html code separator in the title list item.
=> UIEH-600: Results list displays space html code

src/components/title/_fields/package-select/package-select-field.js, src/routes/package-create.js, src/routes/title-create.js
In UIEH, when user navigates to create a new title -> for example -> https://folio.frontside.io/eholdings/titles/new, they should be able to "Choose a package" to associate the creation of this title with a package. The drop down to choose a package has issues in populating the list. 
Populating with the empty fields was associated to the fact that the count of records was bigger than the page size and was no filtering for the empty records.
Basically filtering of the empty records was added and increased the page size to 100
As already discussed with Khalilah it is a temporary solution. The new component for the dropdown select should be developed that will support pagination and filtering.
=> UIEH:584: Issue with package selection when creating custom title

src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/resource/_fields/custom-coverage/custom-coverage-fields.js, src/components/resource/_fields/custom-embargo/custom-embargo-fields.js, src/components/resource/_fields/managed-coverage/managed-coverage-fields.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js
Part of https://issues.folio.org/browse/UIEH-605
Instead of passing in an `initialValue` to pre-packaged field components, we'll be able to pick it off `meta.initial` with React Final Form.
```
renderRepeatableField = ({ fields, name }) => {
const { initialValue } = this.props;
const hasAddButton = fields.length === 0 || (fields.length === 1 && !initialValue[0]);
const hasEmptyMessage = initialValue.length > 0 && initialValue[0].beginCoverage;
...
```
```
renderRepeatableField = ({ fields, name }) => {
const { initial } = this.props;
const hasAddButton = fields.length === 0 || (fields.length === 1 && !initial[0]);
const hasEmptyMessage = initial.length > 0 && initial[0].beginCoverage;
...
```
```
renderRepeatableField = ({ fields, name, meta: { initial } }) => {
const hasAddButton = …
```
=> UIEH-605 Rename initialValue to initial

src/components/navigation-modal/navigation-modal.js, src/components/package/create/package-create.js, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/package/show/package-show.js, src/components/provider/edit/provider-edit.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/title/create/title-create.js, src/components/title/edit/title-edit.js
We can improve the user experience of the "you have unsaved changes" modal by separating out `<NavigationModal>` into its own `<form>`.
- Isolate `<NavigationModal>` outside of any other `<form>`.
- Every use of `<NavigationModal>` had the same copy, so I DRYed that up.
- I was hoping this work would wire up pressing Enter/Return on the keyboard to select "Keep editing", but it doesn't appear the focus is in the right spot when the modal opens to pull that off. I'll keep investigating.
=> Turn NavigationModal into a form

src/components/provider/_fields/proxy-select/index.js, src/components/provider/_fields/proxy-select/proxy-select-field.css, src/components/provider/_fields/proxy-select/proxy-select-field.js, src/components/provider/_fields/token/index.js, src/components/provider/_fields/token/token-field.js, src/components/provider/edit/provider-edit.js, src/components/token/token-field.css, src/routes/provider-edit.js
Switches provider edit form to use React Final Form instead of Redux Form. Part of https://issues.folio.org/browse/UIEH-605.
- Temporarily duplicated `ProxySelectField` and `TokenField` into `provider` directory. When resources and packages are also switched over to React Final Form, we can DRY that back up.
- Stripped CSS out of `TokenField`, since it was just classes with no styles defined.
=> UIEH-605 Use React Final Form for provider edit

src/redux/resource.js
Currently, if mod-kb-ebsco-java module is deployed and we want to set the coverage statement for the first time, the coverage statement field is not included to the request payload.
The serialize method from the BaseModel was redefined in the Resource class to include all needed fields to the request payload.
=> UIEH-594: fix bug on setting coverage statement for the first time

src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/resource-show.js, test/bigtest/interactors/resource-edit.js, test/bigtest/tests/custom-resource-edit-selection-test.js, test/bigtest/tests/resource-deselection-test.js
Currently, when trying to remove a title, a warning message is always saying that we are going to delete the last title in the package, even if there are other titles in the package. The PR fixes this behavior.
[Related story](https://issues.folio.org/browse/UIEH-595)
=> UIEH-595: fix incorrect warning message on delete resource

src/components/title/_fields/description/description-field.js, translations/ui-eholdings/en.json
Similarly to https://issues.folio.org/browse/UIEH-597, 
on title creation page (https://folio.frontside.io/eholdings/titles/new), it is possible to input description with length of up to 1500, but KB can only save description with length 400.
Expected behavior:
UI validation shouldn't allow description longer than 400 characters.
Revise error message from 
The value entered exceeds the 1500 character limit. Please enter a value that does not exceed 1500 characters.
TO 
The value entered exceeds the 400 character limit. Please enter a value that does not exceed 400 characters.
Changed validation for the description field
Corrected error message
=> UIEH-598: Fixed title create description length

src/components/paneset/Pane.js
https://issues.folio.org/browse/STCOM-405
`actionMenuItems` has been completely replaced by `actionMenu` upstream.
=> STCOM-405 Remove actionMenuItems prop from Paneset fork

src/components/navigation-modal/navigation-modal.js, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/package/show/package-show.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/resource-show.js, src/components/search-modal/search-modal.js, src/components/title/show/title-show.js
Adopts patterns introduced in https://github.com/folio-org/stripes-components/pull/779.
Removes deprecation warnings re: using the `primaryButton` and `secondaryButton` props.
=>  Use new ModalFooter syntax

src/components/search-form/search-form.css, src/components/search-form/search-form.js
Switches the search type tabs to use `<ButtonGroup>` from `stripes-components` (introduced in https://github.com/folio-org/stripes-components/pull/761).
=> Use upstream ButtonGroup for search type tabs

src/components/settings.js, src/index.js, src/routes/settings-route.js
https://issues.folio.org/browse/STCOM-387
The `<Settings>` smart component contains routing glue, which is at odds with the routing-based architecture strategy outlined in https://issues.folio.org/browse/STRIPES-589.
We have all the UI we need from `stripes-components` to be able to construct this functionality with the `<Settings>` smart component, in a way that `ui-eholdings` is in complete control of its settings routing.
The `<Settings>` smart component attempts to programmatically alphabetize the items in each `<NavListSection>` - this PR does not maintain that functionality.
=> STCOM-387 Eject from Settings smart component

src/components/package/create/package-create.js, src/components/paneset/Pane.css, src/components/paneset/Pane.js, src/components/search-form/search-form.css, src/components/search-paneset/search-paneset.js, src/components/settings-detail-pane/settings-detail-pane.css, src/components/settings-detail-pane/settings-detail-pane.js, src/components/settings.js, src/components/title/create/title-create.js
Expands use of new `<Pane>` introduced in https://github.com/folio-org/ui-eholdings/pull/634:
- added to knowledge base and root proxy forms
- added to eHoldings settings navigation
- added to custom package and custom title creation forms (those previously didn't have a fixed-position header)
=> Expand use of new <Pane>

src/components/title/_fields/description/description-field.js, translations/ui-eholdings/en.json
This PR relates to https://github.com/folio-org/ui-eholdings/pull/675
As the translation engine can not distinguish change in the numbers I mowed the characters limit number from the translation to the placeholder
=> UIEH-598: Moved limit number from translation to placeholder

package.json
As part of  https://issues.folio.org/browse/FOLIO-1753 we are releasing mod-kb-ebsco-java module so that it can be included in environments and we can start deprecating the use of mod-kb-ebsco (Ruby Version). The Java module provides eholdings interface version 1.0, the Ruby module provides eholdings interface version 0.1.  
This PR provides for a new release of ui-eholdings -- includes an update version number (1.4.0) and an updated eholdings interface version (1.0)
- Update version and interface
- Once PR has been merged, create release 
Followed release procedures as noted at https://github.com/folio-org/stripes/blob/master/doc/release-procedure.md
=> FOLIO-1753 - Release v1.4.0

src/routes/search.js
According to the https://issues.folio.org/browse/UIEH-610,
The search panel should be opened.
Before it depended on the search query and the results list and the logic was to hide the search panel for the initial load if results list is not empty.
Changed the initial state of the search panel to be always visible at the initial load
=> UIEH-610: Fixed search panel initial state to be open

src/redux/resource.js
Resource serializer needs to be changed in order to not send unrecognized data which caused the following bugs:
https://issues.folio.org/browse/UIEH-621
https://issues.folio.org/browse/UIEH-622
https://issues.folio.org/browse/UIEH-623
Duck typing is used to decide what fields should be added to the request payload
=> UIEH-621: change Resource serializer to not send unrecognized data

test/bigtest/tests/resource-managed-coverage-test.js
The issue appeared due to the wrong test for endCoverage to be null.
Recently the custom propType was added to not allow endCoverage to be other than a string 
This change was in this PR https://github.com/folio-org/ui-eholdings/pull/636/files#diff-5f007f8c99c2c04b8db2b098c898a30aR7
So, there is no need in the test as the null case for the endCoverage is contradicts to the propTypes validation.
=> UIEH-614: Fix CoverageDateList warning

src/redux/title.js, src/routes/title-edit.js, test/bigtest/network/config.js, test/bigtest/network/models/title.js, test/bigtest/tests/custom-title-edit-test.js
https://issues.folio.org/browse/UIEH-636
BE added an endpoint for updating titles separately from resources. It is necessary to change titles updating logic on FE side.
- In `titles-edit` component replace `updateResource` method with  `updateTitle`.
- Exclude unnecessary model params(mark as null and exclude them in titles serializer) before sending a request for updating the titles.
- Add put endpoint to mirage
=> UIEH-636: update title edit to updating titles data through titles endpoint

package.json
Additional permission sets, documented [here](https://docs.google.com/spreadsheets/d/1IJnlWvi4k-wFatDNimx9fQ375evHSIIxtGMookHvs-I/edit#gid=214288204) (eHoldings tab), were added to package.json
=> UIEH-501: define UI permissions

src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/package/package-edit.js, src/components/title/edit/title-edit.js, src/routes/title-edit.js, test/bigtest/interactors/package-edit.js, test/bigtest/interactors/title-edit.js
Currently, when we edit a title or a package and hit save button, the form fields briefly revert back to their previous values which are no longer relevant
Previously, the forms' obtained their initial values from props and rendered it. They always rendered what props provided them with. The problem is that props don't usually contain relevant data.
Now, the form values, coming with props, are first saved to the component's local state and the state is used as the source of data to render. This way can decide if we want to update the state with the props' data on the basis of the props' data relevance 
[Jira ticket](https://issues.folio.org/browse/UIEH-627)
=> UIEH-627: fix form fields reverting to previous values on form submit

src/redux/data.js, src/redux/model.js, src/routes/package-create.js, src/routes/package-edit.js, src/routes/provider-edit.js, src/routes/title-create.js, src/routes/title-edit.js
Currently, we have a bug on closing unsaved form, which is described below:
1. Search for a package
2. Edit it and save (if you clicked close button after changing some form fields, a modal notifying about unsaved changes would appear)
3. Start editing this package again, change some fields of the form, but this time, instead of saving the changes, click close button
4. See that no confirmation modal appeared, even though we have unsaved changes
Same issue can be reproduced for titles and providers. 
The problem was caused by the update request object, which contained not relevant information
1. Create `REMOVE_REQUEST` action which takes the type of request and then is used to remove requests of that type 
2. Use this action in title/package/provider edit components to delete the update …
=> UIEH-637: fix bug on closing unsaved form

src/components/package/show/package-show.js, src/components/provider/show/provider-show.js, src/redux/package.js, src/routes/package-show.js, test/bigtest/interactors/package-show.js, test/bigtest/network/factories/package.js, test/bigtest/tests/package-show-test.js
Purpose: To display, assign, unassign, and output tags associated with individual Package records within the FOLIO eholdings app.
As a staff person
I want to be able to assign, unassign, view, and output tags in a FOLIO eholdings app's package record
So that I can categorize records for filtering and reporting purposes.
Background
Tags are meant to be labels that can be assigned to individual data records in various FOLIO apps. Tags will be used as a visual indicator in the record, to gather records in some way, and to facilitate reporting. This is a cross-app “helper app.” Github repo: https://github.com/folio-org/ui-tags
tags functionality in the eholdings app was developed separately from the tags implemented in the stripes-smart-components as in eholdings we not used the search and …
=> UIEH-586: Assign tags to package record

src/components/title/_fields/contributor/contributor-field.js, test/bigtest/tests/custom-title-edit-test.js, test/bigtest/tests/title-create-test.js
Currently, when we edit a title, click `Add new contributor` and don't change the type of the contributor, the default displayed type (which is `Author`) won't be sent to the back-end. The `Author` value is displayed in the select, but it isn't actually a part of the form's state.
I added `addNewField` method to `contributor-field` component, which is responsible for setting the value of a just created select to the form's state. I also adjusted related tests and tests related to the bug described below.
This PR also fixes another bug which I found. It can be reproduced as follows: 
1. Go to title edit
2. Add some contributors of different type to the title. Save edited title
3. Go to editing the title again
4. Notice that all contributor type selects display 'Author' option, even though …
=> UIEH-656: fix bug on adding a contributor with default type

src/components/package/show/package-show.js, src/components/provider/show/provider-show.js, src/components/resource/resource-show.js, src/components/tags/tags.js, src/components/title/show/title-show.js, src/components/utilities.js, src/redux/resource.js, src/redux/title.js, src/routes/resource-show.js, src/routes/title-edit.js, src/routes/title-show.js, test/bigtest/interactors/resource-show.js, test/bigtest/interactors/title-show.js, test/bigtest/network/factories/resource.js, test/bigtest/network/factories/title.js, test/bigtest/tests/resource-show-test.js, test/bigtest/tests/title-show-test.js, translations/ui-eholdings/en.json
To display, assign, unassign, and output tags associated with individual title+package (aka resource) records within the FOLIO eholdings app.
As a staff person
I want to be able to assign, unassign, view, and output tags on a FOLIO eholdings app's title+package (aka resource) record
So that I can categorize records for filtering and reporting purposes.
Background
Tags are meant to be labels that can be assigned to individual data records in various FOLIO apps. Tags will be used as a visual indicator in the record, to gather records in some way, and to facilitate reporting. This is a cross-app “helper app.” Github repo: https://github.com/folio-org/ui-tags
Screenshot - Same implementation as Provider
https://drive.google.com/drive/folders/1srda9mL1jeP09lKislIkxMuaG5C2a3Ap
tags …
=> UIEH-587: Assign tags to title+package (aka resource) records

src/components/agreements-list/agreements-list.js, src/components/agreements-list/index.js, src/components/package/show/package-show.js, src/components/provider/show/provider-show.js, src/redux/actions/attach-agreement-failure.js, src/redux/actions/attach-agreement-success.js, src/redux/actions/attach-agreement.js, src/redux/actions/get-agreements-failure.js, src/redux/actions/get-agreements-success.js, src/redux/actions/get-agreements.js, src/redux/actions/index.js, src/redux/epics/attach-agreement.js, src/redux/epics/attachAgreement.js, src/redux/epics/common/get-headers.js, src/redux/epics/common/index.js, src/redux/epics/common/parse-response-body.js, src/redux/epics/get-agreements.js, src/redux/epics/getAgreements.js, src/redux/epics/index.js, src/redux/index.js, src/redux/reducers/agreements.js, src/redux/reducers/index.js, src/redux/selectors/index.js, src/redux/selectors/select-agreements.js, src/routes/package-show.js, test/bigtest/interactors/package-show.js, test/bigtest/network/config.js, test/bigtest/tests/package-show-test.js, translations/ui-eholdings/en.json
https://issues.folio.org/browse/UIEH-628
Add new feature for attaching agreements to the package. Apply a new approach of managing data in eholdings app.
- Add an accordion for with a list of agreements
- Add actions, reducers, epics for fetching and updating agreements
- Add a "ui-find-agreements" plugin for attaching an agreement to the package
- Add tests
Full agreements functionality should be tested after an ERM with agreements has been added to the FOLIO snapshot build.
Unit tests for new redux stuff will be added during work on https://issues.folio.org/browse/UIEH-630
=> Add agreements section to package show details page

package.json, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/package/selection-status.js, src/components/package/show/package-show.js, src/components/provider/show/provider-show.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/resource-show.js, src/components/search-paneset/search-paneset.js, src/components/title/show/title-show.js
We want to not let a user do an action if they don't have the permission to do the action.
`IfPermission` component from `stripes-core` was used to render content depending on current user's permissions. I also had to inject stripes into `ResourceShow` component to use stripes's `hasPerm` function. This is needed for conditional rendering.
View permission was deleted from `package.json`, as it was decided to not use it at all. 
One more thing which I've done is removing the selection permission from the edit's sub-permissions (it's not needed there)
=> UIEH-669: Make UI permissions effective 

src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/resource/_fields/custom-coverage/custom-coverage-fields.js, src/components/resource/_fields/managed-coverage/managed-coverage-fields.js
The bug is that when we go to resource/package edit and try to remove a custom coverage from a resource/package, the save button is not enabled.
`FieldArray` component from `react-final-form-arrays` is used to render coverage date fields. It has a prop `isEqual`, which is a function whose role is to check if the values of fields inside of the `FieldArray` was changed. If `isEqual` function is not provided, it will return `true` by default:
To fix the bug I just passed lodash's `isEqual` as a prop to `FieldArray`
=> UIEH-665: fix bug on removing custom coverage from package or resource

test/bigtest/tests/custom-resource-edit-custom-coverage-test.js
Back-end changes the order of custom coverages which it returns. In this PR, I've adjusted UI tests in accordance with the new back-end response.
I also changed some tests' names to be more clean and semantic
* The order of mocked custom coverages was changed to be the same as what the back-end returns
=> UIEH-666: change custom coverages tests according to the back-end response

src/components/resource/_fields/coverage-statement/coverageStatementDecorator.js, src/components/resource/_fields/coverage-statement/index.js, src/components/resource/_fields/custom-embargo/custom-embargo-fields.js, src/components/resource/_fields/custom-embargo/get-custom-embargo-initial.js, src/components/resource/_fields/custom-embargo/index.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/resource-edit.js, src/constants/coverageStatementExistenceStatuses.js, src/constants/coverageStatementStatuses.js, src/constants/index.js, src/routes/resource-edit.js, test/bigtest/interactors/resource-edit.js
In this PR, I fixed the bug with form staying pristine after removing the custom embargo field on the resource edit page. I also changed resource edit page so that it does not render the edit form until the data is loaded since we don't know what kind of form to render if the data hasn't been received. It also gave me a way to fix the issue with the pristine form.
* Wrap the embargo fields in `FieldArray`. `FieldArray` makes it possible to handle situations when an input was removed from the page properly.
=> UIEH-668: fix bug on removing custom embargo

CHANGELOG.md, src/features/agreements-accordion/agreements-accordion.js, test/bigtest/interactors/agreements-accordion.js, test/bigtest/interactors/package-show.js, test/bigtest/interactors/resource-show.js, test/bigtest/tests/package-show-test.js, test/bigtest/tests/resource-show-test.js
https://issues.folio.org/browse/UIEH-680
Add badge to the accordion with agreements on Package and Resource show pages.
- Add badge with agreements quantity, which is visible only when accordion is collapsed
- Cover with tests Package and Resource show pages
=> UIEH-680: Badge for agreements section

src/components/title/show/title-show.js, src/redux/title.js, src/routes/title-show.js, test/bigtest/interactors/title-show.js, test/bigtest/tests/custom-title-edit-test.js, test/bigtest/tests/title-show-test.js
Per https://issues.folio.org/browse/UIEH-685 we are removing tags from title records.
Tags will be supported on resource records (aka title+package records). When performing a filter by tags from Search&Filter for Titles, we will lookup tags associated with resources to support this.
https://issues.folio.org/browse/UIEH-701
- Remove tags accordion and associated methods from Title Show Page Component
- Remove tag methods and model information from Title Show Route
- Remove/Update related tests
- Update Redux title (removing taglist)
Before
After
=> UIEH-685 Title: Remove Tags functionality

test/bigtest/tests/note-create-test.js
For now we can't run notes tests because notes interactors are not yet released.
Unskip the tests after stripes-smart-components is released and notes related interactors are available for use in applications
=> skip note creation tests

src/routes/package-show.js
Updating the package triggered the update it's resources.
Updating the tags does not have any influence on the resources.
So if the package update is due to the tag change than we do not need to  re-fetch the resources
=> UIEH-708: Fixed not needed calls when adding/removing tags for package

.npmrc, test/bigtest/tests/custom-resource-edit-custom-coverage-test.js, test/bigtest/tests/managed-resource-edit-custom-coverage-test.js, yarn.lock
1) npm registry changed to folioci so that testing not fail on CI when non-release features used from the low-level module (stripes-smart-platform)
2) fix test that fail after the yarn.lock update
=> Changed npm registry so that testing not fail on CI and fix tests

src/components/search-form/search-form.js, src/components/search-modal/search-modal.js, src/routes/package-show.js, src/routes/provider-show.js
https://issues.folio.org/browse/UIEH-710
https://issues.folio.org/browse/UIEH-711
There is search modal on package show and provider show pages. The purpose is to add tags filter to this modal. Tags filter performs search hot right after the choosing necessary tag. It works independently. For now disabling of another filters is out of scope.
- Add `MultiSelectionFilter` to the bottom of `SearchModal`
- Provide modal with tags.
- Add filter handler to search modal
=> UIEH-710, UIEH-711: Add tags filter to search modal

src/components/search-modal/search-modal.js
The nature of this but was in resetting the state of the search dropdown when any of the filters changed and the search dropdown not changed.
=> UIEH-706: Package: Search within Titles popup: Title search dropdown is not sticky

src/components/agreements-list/agreements-list.js, src/features/agreements-accordion/agreements-accordion.js, test/bigtest/tests/package-show-test.js, test/bigtest/tests/resource-show-test.js
The URLs to view and create agreements have changed with ERM-253 implemented in https://github.com/folio-org/ui-agreements/pull/219 This PR updates eHoldings to use those new URLs.
Feel free to push to this branch if I missed anything.
Also, there's [big underlying changes to the find-agreement plugin](https://github.com/folio-org/ui-plugin-find-agreement/pull/41), but it looks like eHoldings is completely decoupled from them since the public API has stayed the same and eHoldings doesn't declare a dependency on a particular version of ui-plugin-find-agreement (which makes sense).
=> ERM-253: Update Agreements URLs

package.json
When testing out some changes to BigTest interactors (related to https://issues.folio.org/browse/UIEH-612), I switched my local copy of `ui-eholdings` to use a GitHub-hosted branch of `@bigtest/interactor`, instead of the version published on NPM.
When I tried to push my changed `ui-eholdings` branch to the `frontside-folio` fork with [Git Tower](https://www.git-tower.com), I received an ambiguous error.
I finally traced my inability to push to the pre-push hooks added with https://github.com/folio-org/ui-eholdings/pull/766. Tower was not displaying the ESLint errors caused by my pointing a scoped package to an unpublished branch.
Make sure the errors get printed to STDERR: https://www.git-tower.com/help/mac/faq-and-tips/faq/hook-scripts
I'm generally not in favor of pre-commit or …
=> Modify pre-push hook

package.json, test/bigtest/interactors/note-form.js, test/bigtest/interactors/note-view.js, test/bigtest/tests/package-notes-flow-test.js, test/bigtest/tests/provider-notes-flow-test.js, test/bigtest/tests/resource-notes-flow-test.js, yarn.lock
Per https://issues.folio.org/browse/STSMACOM-226 the assigned accordion section (on both note view and edit ) should be closed by default. This PR adds tests for changes that have been made to assignment accordion https://github.com/folio-org/stripes-smart-components/pull/564
Checks that assignment accordion is closed by default on both view and edit note. Checks are made on Provider/Package/Resource notes flow tests. Tests which check if assignment accordion is closed will fail until merge of other PR
Tests continued to fail -- after change in stripe-smart-components was merged. Note -- I Did the following steps to resolve:
Regenerate lock file
- deleted yarn.lock
- deleted node-modules folder
- yarn cache clean
- yarn 
- yarn start
Also note -- needed changes -- …
=> STSMACOM-226 - Add tests for assignment accordion closed by default

src/components/search-form/search-filters.js, src/components/search-form/search-form.css, src/components/search-form/search-form.js, test/bigtest/interactors/package-search.js, test/bigtest/interactors/provider-search.js, test/bigtest/interactors/search-modal.js, test/bigtest/interactors/title-search.js, test/bigtest/tests/package-search-test.js, test/bigtest/tests/package-show-titles-search-test.js, test/bigtest/tests/provider-search-test.js, test/bigtest/tests/provider-show-package-search-test.js, test/bigtest/tests/title-search-test.js
The purpose of this PR is to make all search filters throughout the application closed by default.
All necessary tests adjustments were done to reflect this change.
=> UIEH-737: make search filters collapsed by default

package.json, test/bigtest/helpers/setup-application.js, test/bigtest/network/boot.js, yarn.lock
https://issues.folio.org/browse/UIEH-756
- Remove stripes-core from devDependencies
- Correct imports for setupStripesCore and startMirage
- In package.json replace stripes -> type with actsAs 
- in package.json remove stripes -> useSettings and add "settings" to actsAs array 
- Regenerate yarn.lock
https://github.com/folio-org/stripes/blob/master/doc/stripes-framework.md#upgrading-to-v26
=> UIEH-756: Migrate to stripes ^2.6.0

CHANGELOG.md, package.json, src/components/settings.js
Instead of a single setting to determine visibility of settings items,
use per-item permissions. Details at [UITEN-35](https://issues.folio.org/browse/UITEN-35)
* Add granular settings permissions in `package.json`
* Use these settings where links to settings pages are rendered
* Remove the generic (and unused) "display list of settings pages" permission
Note that this doesn't actually enforce the permission on the route itself; all it does it prevent displaying the link to the route. That _should_ be added but I wasn't sure of the preferred way to do it.
=> UITEN-35 use granular permissions

CHANGELOG.md, package.json
stripes-core uses `settings.${module}.enabled` to determine whether a
module should be listed on the settings page. Unfortunately, it was
removed in #840 because I didn't realize that requirement.
Here, `settings.${module}.enabled` is being restored BUT without `visible: true` because we do not want to grant this permission to anybody; we want granular, per-item permissions as UITEN-35 indicates.
Fixes UIEH-757; refs UITEN-35
=> UIEH-757 restore eHoldings to settings

src/components/title/_fields/publication-type/publication-type-field.js, src/redux/title.js, translations/ui-eholdings/en.json
There are 2 places in the application where "audio book" is used (should be single work):
1.  `<PublicationTypeField>`. Here  "Audio book" causes a bug because the value expected by the back-en is "Audiobook" 
2. `ui-eholdings.filter.pubType.audioBook` translation string
There are no tests or mirage configs which rely on publication type so no additional fixes are required
=> UIEH-763: fix audiobook misspelling causing inabiliy to create a title

src/redux/model.js, src/redux/resource.js
In this PR we get rid of the `tags` in the PUT payload for the resources/package/provider requets
This clean-up is needed as we currently update tags with separate endpoints.
=> UIEH-769: Remove tags from resource/package/provider PUT payload

test/bigtest/interactors/resource-show.js, test/bigtest/interactors/selection-status.js, test/bigtest/network/config.js, test/bigtest/tests/title-search-test.js
The mirage handler of `GET   /titles ` request containing tags filter works incorrectly. It searches for tags inside titles, however, titles don't have tags. We should make it search for tags inside the titles' resources.
* Fix the `this.get('/titles', ....)` handler. Now it searches for tags inside titles' resources
* Adjust test preparation steps (i.e. beforeEach). Now we don't create a title with a list of tags. Instead, we create a title whose resources contain tags
* [not related to the ticket] fix some failing tests which are not tied code which was changed during the work on the story. Supposedly, the started failing because of some stripes-components updates.
=> UIEH-758: fix mirage handler for GET titles with tags filter

src/components/paneset/Pane.css, src/components/search-paneset/search-paneset.css
https://issues.folio.org/browse/UIEH-760
Pane content is not fully shown
Fit content height with a help of Flexbox css rules
##Screenshot
=> UIEH-760: Fix height of the pane container to fit all content.

src/components/package/_fields/custom-coverage/package-coverage-fields.js, test/bigtest/tests/package-create-test.js
https://issues.folio.org/browse/UIEH-782
Disallow to create more than 1 date range for custom coverage on UI.
- Remove outdated condition
- Cover the case with a test
=> UIEH-782: Disallow to create more than 1 date coverage range

test/bigtest/helpers/setup-application.js, test/bigtest/network/boot.js
The [guide](https://github.com/folio-org/stripes/blob/master/doc/stripes-framework.md#upgrading-to-v26) on how to migrate to stripes 2.6 is misleading.
Changing
`import startMirage from '@folio/stripes-core/test/bigtest/network/start';`
to
`import { startMirage } from '@folio/stripes/core/test';`
results in an application not working in mirage mode.
The reason is that `stripes-core` does not export what `stripes` is trying to import:
[stripes/core/test/index.js](https://github.com/folio-org/stripes/blob/master/core/test/index.js)  has  `export { default } from '@folio/stripes-core/test';`
but [stripes-core/test/index.js](https://github.com/folio-org/stripes-core/blob/master/test/index.js)  has no default export
=> UIEH-793: fix bigtest imports

package.json
`mod-agreements` needs to update the version on the `erm` interface to 2.0 because of the breaking changes to the API to [_set_ agreement dates/periods](https://issues.folio.org/browse/ERM-466). eHoldings needs to support the new interface version for the nightly builds to build.
The breaking change is only to the process of editing the start, end or cancellation date of an agreement. eHoldings does none of these so a simple bump to the version in `okapiInterfaces` is all that's needed.
Note that as of this PR being opened, `mod-agreements` has not yet been updated with the new interface version. I'm opening this PR ahead of time so that this can be merged before then.
=> Support erm interface v2.0

src/components/search-form/search-form.js
The purpose of this PR is to add a focus onto SearchBox when eHoldings app is accessed from the app's menu
=> UIEH-790: Set focus on search box when accessing the eholdings

src/redux/tag.js
Currently tags retrieved for the search filter limited only to 10.
The purpose of this PR is to increase the number of retrieved tags to up to 100k
=> UIEH-796: Retrieve up to 100k of requested tags instead of 10

package.json
https://issues.folio.org/browse/UIEH-803
react-final-form versions greater 6.3.0 breaks the work of the Eholdings forms
Lock react-final-form 6.3.0 version.
=> UIEH-803: lock react-final-form 6.3.0 version

src/api/agreements.js
This PR is to fix the error handling of the agreements api calls.
There was an error in the error handling for the agreements api calls and the error message returned from the server was not propagated to the UI and always "Unknown error" message appeared.
This is fixed and an "unknown error" message is now will be shown only if no message in the the response.
=> UIEH-797: Fixed error handling for agriments related api calls

src/features/agreements-accordion/agreements-accordion.js, src/redux/selectors/index.js, src/redux/selectors/select-user-permissions.js, test/bigtest/tests/unit/selectors/select-agreements-test.js
https://issues.folio.org/browse/UIEH-800
Get agreements only when "erm.agreements.collection.get" exists
=> UIEH-800: Add condition to do agreements GET only when it is allowed

package.json, src/components/package/show/package-show.js, src/components/resource/resource-show.js, src/features/agreements-accordion/agreements-accordion.js, src/redux/selectors/index.js, src/redux/selectors/select-user-permissions.js, test/bigtest/helpers/setup-application.js, test/bigtest/interactors/note-form.js, test/bigtest/tests/package-notes-flow-test.js, test/bigtest/tests/package-search-test.js, test/bigtest/tests/package-show-test.js, test/bigtest/tests/provider-edit-test.js, test/bigtest/tests/provider-notes-flow-test.js, test/bigtest/tests/provider-show-test.js, test/bigtest/tests/resource-notes-flow-test.js
Due to the changes done in the notes-form according to the story:https://issues.folio.org/browse/STSMACOM-270
The tests in ui-eholdings adopted to the new changes in this PR
The PR for the changes in notes form: https://github.com/folio-org/stripes-smart-components/pull/674
Also in this PR the agreements tests fixed
Also fixed the versions for  final-form related libraries
=> Fixed tests for the notes & for the agreements

src/components/search-paneset/search-paneset.js
Initially there were focus set to the app header after the search complete.
When changing the app and returning back the search was not focused.
This behaviour was changed and the focus is set to search in all the cases.
=> UIEH-815: When you access the app the focus should be in the Search box

CHANGELOG.md, src/components/package/show/package-show.js, test/bigtest/interactors/actions-drop-down.js, test/bigtest/interactors/package-edit.js, test/bigtest/interactors/package-show.js, test/bigtest/interactors/resource-edit.js, test/bigtest/interactors/resource-show.js, test/bigtest/tests/custom-package-edit-selection-test.js, test/bigtest/tests/custom-package-show-selection-test.js, test/bigtest/tests/custom-resource-edit-selection-test.js, test/bigtest/tests/package-selection-test.js, test/bigtest/tests/package-show-test.js, test/bigtest/tests/resource-deselection-test.js, test/bigtest/tests/resource-edit-deselection-test.js, test/bigtest/tests/resource-edit-managed-title-in-custom-package-test.js, test/bigtest/tests/resource-embargo-test.js, test/bigtest/tests/resource-selection-test.js
- Make it possible to edit selected packages
- Fix related tests to actions drop down button
The problem was that the last menu use to check permission `stripes.hasPerm()` instead of component `<IfPermission>`. After PR - [STCOM-553](https://github.com/folio-org/stripes-components/pull/1112) this option doesn't work correctly.
https://issues.folio.org/browse/UIEH-829
=> UIEH-829: Fix view of Action button on package view page header

src/components/resource/resource-show.js, test/bigtest/interactors/resource-drop-down-menu.js, test/bigtest/interactors/resource-show.js
Due to  this PR https://github.com/folio-org/stripes-components/pull/1112
The purpose of this PR is to:
- Remove the edit icon from the resource show page
- Adopt the test
=> UIEH-823: Removed edit icon from resource show page

CHANGELOG.md, src/components/package/show/package-show.js, test/bigtest/interactors/package-drop-down-menu.js, test/bigtest/interactors/package-show.js, test/bigtest/tests/package-show-test.js
- Update pane header after [PR](https://github.com/folio-org/stripes-components/pull/1112), since buttons with the same functions are duplicated
- Remove Edit/Pencil icon
https://issues.folio.org/browse/UIEH-822
=> UIEH-822: View Package Record: Remove Edit/Pencil icon

src/components/settings/settings-access-status-types/settings-access-status-types.js
In this PR the sorting for the access statuses was added according to https://issues.folio.org/browse/UIEH-841
=> UIEH-841: Settings > eholdings > Access Status Types CRUD sort order should be name

CHANGELOG.md, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/proxy-select/proxy-select-field.js, src/components/utilities.js, src/routes/package-show.js, src/routes/resource-show.js, test/bigtest/network/config.js, test/bigtest/network/factories/proxy.js, test/bigtest/tests/custom-package-edit-proxy-test.js, test/bigtest/tests/managed-package-edit-proxy-test.js, test/bigtest/tests/package-show-test.js, test/bigtest/tests/resource-show-test.js
- Fix Unsaved Changes Modal not appearing after changing selected status of package.
- Fix need to click 'X' twice to return after changing selected status of resource and visiting Edit page.
[UIEH-854](https://issues.folio.org/browse/UIEH-854)
=> UIEH-854: Edit Package Record | Proxy selection is not honored and Unsaved Changes modal does not display when you edit a record for the first time

CHANGELOG.md, src/routes/package-show.js, src/routes/provider-show.js
Add functionality for retaining search filters after moving on previous page
Update query string with filter query for titles on Package View Page and for packages on Provider View Page
[UIEH-853](https://issues.folio.org/browse/UIEH-853)
[UIEH-847](https://issues.folio.org/browse/UIEH-847)
=> UIEH-853: Retain search within filtered list for provider and package

src/redux/data.js
To make filtering packages by multiple access status types available. Currently, if multiple access status types are selected, then an empty response is received because the request query string is built in the wrong way.
The logic of building request query string for access types is different from how the query string is built in all other cases. Query strings are created deep inside the data layer of the app, so it's not possible to just specify them in components. That's why I chose to handle the creation of query string for access status type filter as a special case in the `redux/data.js`.
=> Make filtering by multiple access types possible

CHANGELOG.md, src/components/settings/settings-access-status-types/settings-access-status-types.js, test/bigtest/network/helpers.js, test/bigtest/tests/settings-access-status-types-test.js, translations/ui-eholdings/en.json
- Add validation for duplicated Access Types
[UIEH-878](https://issues.folio.org/browse/UIEH-878)
=> UIEH-878: Settings > Access Status Types > Able to create duplicate access status types

CHANGELOG.md, translations/ui-eholdings/en.json
- Move permission display names to translation files to be picked up by `react-intl`
=> UIEH-890: eHoldings app: Move permission names to translation file

CHANGELOG.md, src/components/settings/settings-access-status-types/settings-access-status-types.js
- Show count of records where access type is used
- Hide delete button when access type is used in records
[UIEH-868](https://issues.folio.org/browse/UIEH-868)
=> UIEH-868: Hide delete button when access type is used in records

src/components/settings/settings-access-status-types/settings-access-status-types.js, src/redux/actions/delete-access-type-failure.js, src/redux/epics/delete-access-type.js, src/redux/reducers/accessTypes.js, test/bigtest/interactors/settings-access-status-types.js, test/bigtest/tests/settings-access-status-types-test.js, test/bigtest/tests/unit/actions/delete-access-type-failure-test.js, test/bigtest/tests/unit/reducers/access-types-test.js, translations/ui-eholdings/en.json
To let users know if the access status type that they are trying to delete has already been deleted. Also, this access status type should be removed from the list on the page.
https://issues.folio.org/browse/UIEH-860
=> UIEH-860: handle error when trying to delete access status type that doesn't exist

src/components/package/show/package-show.js, src/components/title-list-item/title-list-item.css, src/components/title-list-item/title-list-item.js, test/bigtest/interactors/package-show.js, test/bigtest/tests/package-show-test.js
To show icons next to selection status and visibility status indicators on the titles list on the package show page
=> UIEH-862: package show title list ui updates

src/routes/settings-assigned-users-route.js
Fix infinite spinner when assigning a user to KB has failed
=> UIEH-900: Settings > eholdings > Assigned Users > Attempting to add a user to a second set of credentials results in a length loading indicator

src/components/details-view/details-view.js
To fix scrolling issues in the `DetailsView` component
The component decides whether it should disable or enable scrolling of the page container and the packages/titles list depending on the `scrollTop` property. Sometimes its value has a decimal point which results in the condition always evaluating to `false`. This depends on the height of the viewport.
To fix this, I check if values don't differ by more than 1 pixel, instead of checking if they are the equal. Rounding the numbers won't work because we can't know if we need to round up or down in every specific case.
=> UIEH-897: fix DetailsView scrolling issues

CHANGELOG.md, src/routes/settings-route.js, test/bigtest/interactors/settings.js, test/bigtest/network/config.js, test/bigtest/tests/settings-test.js
- Sort KB credentials in alphabetical order by name in Settings > eHoldings
[UIEH-912](https://issues.folio.org/browse/UIEH-912)
=> UIEH-912: KB credentials do not display in alphabetical order by KB Name

CHANGELOG.md, src/redux/epics/attach-access-type.js, src/redux/epics/attach-agreement.js, src/redux/epics/delete-access-type.js, src/redux/epics/delete-kb-credentials-user.js, src/redux/epics/delete-kb-credentials.js, src/redux/epics/get-access-types.js, src/redux/epics/get-agreements.js, src/redux/epics/get-custom-labels.js, src/redux/epics/get-kb-credentials-users.js, src/redux/epics/get-kb-credentials.js, src/redux/epics/get-proxy-types.js, src/redux/epics/get-root-proxy.js, src/redux/epics/get-user-groups.js, src/redux/epics/post-kb-credentials-user.js, src/redux/epics/post-kb-credentials.js, src/redux/epics/put-kb-credentials.js, src/redux/epics/update-access-type.js, src/redux/epics/update-custom-labels.js, src/redux/epics/update-root-proxy.js
In Settings > eHoldings after re-logging with another user incorrect x-okapi-token was being send with each request.
This is caused by a mistake in writing of epics, which would retrieve okapi token from store only one time per epic, and then use old token with each request. This meant that when you logged in the first time, the epic would get the token from store and (unintentionally) cache it in a closure. After re-logging a fresh token would be saved to a store, but not in epics.
=> UIEH-918: eHoldings app: Incorrect x-okapi-token sent to /access-types after re-login

src/components/settings/settings-knowledge-base/settings-knowledge-base.js
For some reason `router` object from React context is undefined on stable and testing envs, so we need to replace this prop with `history` object from `react-router`
=> UIEH-898: Used history from react-router instead of context

CHANGELOG.md, package.json, translations/ui-eholdings/en.json
Add translations for permission names in the scope of the [UIEH-915](https://issues.folio.org/browse/UIEH-915).
=> UIEH-915: Fix permission error in devtools console

CHANGELOG.md, src/components/package/show/package-show.js, test/bigtest/interactors/package-selection-modal.js, test/bigtest/interactors/package-show.js, test/bigtest/tests/package-add-new-titles-test.js, test/bigtest/tests/package-selection-test.js, test/bigtest/tests/package-show-test.js, translations/ui-eholdings/en.json
With these changes, when a user wants to select a package, they will be asked to confirm this action:
Also, the selection button content was changed from Add to holdings to Add package to holdings (when there are no titles selected) and from Add all to holdings to Add all titles to holdings (when there is at least one title selected):
=> UIIH-907: implement package selection confirmation modal

CHANGELOG.md, src/components/settings/settings-knowledge-base/settings-knowledge-base.js, src/components/settings/settings-root-proxy/settings-root-proxy.js
Layout updates:
- remove headline on KB settings page
- remove headline on Root Proxy settings page
[UIEH-911](https://issues.folio.org/browse/UIEH-911)
=> UIEH-911: Remove headlines from Root Proxy and KB settings pages

CHANGELOG.md, src/components/title/_fields/name/title-name-field.js, src/components/title/_fields/package-select/package-select-field.js, src/components/title/create/title-create.js
[[UIEH-920]](https://issues.folio.org/browse/UIEH-920) Create/Edit Custom Title > Name and Package required field does not display as a red asterisk NOR is it read by a screenreader
Create/Edit Custom Title >
Name and Package required field does not display as a red asterisk
NOR is it read by a screenreader
=> [UIEH-920] Create/Edit Custom Title > Name and Package required field does not display as a red asterisk NOR is it read by a screenreader

CHANGELOG.md, src/components/title/show/package-filter-modal/index.js, src/components/title/show/package-filter-modal/package-filter-modal.css, src/components/title/show/package-filter-modal/package-filter-modal.js, src/components/title/show/package-filter-modal/use-modal-toggle.js, src/components/title/show/package-filter-modal/use-package-filter-select-options.js, src/components/title/show/title-show.js, test/bigtest/interactors/package-filter-modal.js, test/bigtest/interactors/title-show.js, test/bigtest/tests/title-show-package-filter-test.js, translations/ui-eholdings/en.json
This PR implements the functionality of filtering packages on the title page
[Ticket](https://issues.folio.org/browse/UIEH-928)
=> UIEH-928: add possibility to filter packages on the title page

CHANGELOG.md, src/components/details-view/details-view.js
- Fix calculation of scrollable list height to be more precise
[UIEH-960](https://issues.folio.org/browse/UIEH-960)
=> UIEH-960: Package/Title pages experience wobbly 

CHANGELOG.md, src/components/tags/tags.js, src/components/title/show/package-filter-modal/package-filter-modal.js
[[UIEH-939]](https://issues.folio.org/browse/UIEH-939) Pass aria-labelledby to MultiSelection component
Need to find places in ui-eholdings where we're using MultiSelection component and pass aria-labelledby prop that either:
References an already existing element on the page
References an element that has to be created, which has text for screen reader and .sr-only class
=> [UIEH-939] Pass aria-labelledby to MultiSelection component

CHANGELOG.md, src/components/details-view/details-view.js
[[UIEH-924]](https://issues.folio.org/browse/UIEH-924) Package View - Invalid id and aria-labelledby attributes in Pane header
Invalid ARIA attribute value: aria-labelledby="paneHeaderEBSCO Biotechnology Collection: India-pane-title"
=> [UIEH-924] Package View - Invalid id and aria-labelledby attributes in Pane header

CHANGELOG.md, src/components/details-view/details-view.js, src/components/package/show/package-show.js, src/components/provider/show/provider-show.js, src/components/resource/resource-show.js, src/components/tags/tags-accordion.js, src/components/title/show/title-show.js, src/features/agreements-accordion/agreements-accordion.js, src/features/custom-labels-accordion/custom-labels-accordion.js
[UIEH-923](https://issues.folio.org/browse/UIEH-923): Providers, Packages, Titles filter - accordions do not have correct ARIA attributes
Element with a `tablist` role missed children with a `tab` role.
Related PR's
- Added additional props to `DefaultAcordionHeader` 
https://github.com/folio-org/stripes-components/pull/1397
- Added headerProps property to `NotesSmartAccordion`
https://github.com/folio-org/stripes-smart-components/pull/922
=> UIEH-923: Providers, Packages, Titles filter - accordions do not have correct ARIA attributes

CHANGELOG.md, src/components/search-form/search-filters.js, src/components/search-form/search-form.js
[UIEH-925](https://issues.folio.org/browse/UIEH-925): View Package > Find Title - Accordions missing some ARIA attributes
Accordions in search modal were missing `role="tab"` attributes.
Related PR - https://github.com/folio-org/stripes-components/pull/1402
=> UIEH-925: View Package > Find Title - Accordions missing some ARIA attributes

CHANGELOG.md, src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/resource/_fields/resource-coverage-fields/resource-coverage-fields.js, src/components/utilities.js, src/constants/backendDateStandard.js, src/constants/dateFormat.js, src/constants/index.js, src/constants/timeZone.js
After refactoring the `<Datepicker>` component in `stripes-components`, the `<Datepicker>` in the `ui-eholdings` ceased to function correctly for data entry via the input. This problem is inherent in the `<Datepicker>` used with `react-final-form`. The problematic place is the prop `format`, which, when the value changes, aggressively replaces it with a valid value from the store.
[UIEH-961](https://issues.folio.org/browse/UIEH-961)
The solution to this problem was to rewrite the component call as in example from `<Datepicker>` documentation for use with the `react-final-form`. The main props for `<Datepicker>` in this situation are `dateFormat` which helps to keep correct date format in the input and `backendFormatStandard` which allows you to store data in the required format for the …
=> UIEH-961: Fix bug with Datepicker on Resource Edit Page

CHANGELOG.md, src/api/agreements.js, src/components/agreements-list/agreements-list.js, src/features/agreements-accordion/agreements-accordion.js, src/redux/actions/confirm-unassign-agreement.js, src/redux/actions/delete-agreement-lines-failure.js, src/redux/actions/delete-agreement-lines-success.js, src/redux/actions/get-agreement-lines-failure.js, src/redux/actions/get-agreement-lines-succes.js, src/redux/actions/index.js, src/redux/actions/unassign-agreement.js, src/redux/epics/delete-agreement-lines.js, src/redux/epics/get-agreement-lines.js, src/redux/epics/index.js, src/redux/index.js, src/redux/reducers/agreements.js, test/bigtest/interactors/agreements-accordion.js, test/bigtest/network/config.js, test/bigtest/tests/resource-show-test.js, test/bigtest/tests/unit/actions/confirm-unassign-agreement-test.js, test/bigtest/tests/unit/actions/delete-agreement-lines-failure-test.js, test/bigtest/tests/unit/actions/delete-agreement-lines-success-test.js, test/bigtest/tests/unit/actions/get-agreement-lines-failure-test.js, test/bigtest/tests/unit/actions/get-agreement-lines-success-test.js, test/bigtest/tests/unit/actions/unassign-agreement-test.js, test/bigtest/tests/unit/epics/delete-agreement-lines-test.js, test/bigtest/tests/unit/epics/delete_agreement_lines-test.js, test/bigtest/tests/unit/epics/get-agreement-lines-test.js, test/bigtest/tests/unit/reducers/agreements-test.js, translations/ui-eholdings/en.json
Ability to unlink an agreement from package/resource. For implementation, it is necessary to make two requests. First request needed to get agreement lines ids related to current agreement and package/resource. Second one to delete related agreement lines from agreement.
[Issue](https://issues.folio.org/browse/UIEH-956)
=> UIEH-956: Ability to unlink an agreement from package/resource

CHANGELOG.md, src/routes/note-edit.js, src/routes/note-view.js
Fix routing issues when visiting Note Edit page:
1. when on Package View page and after clicking on 'Edit' in Notes Accordion and clicking 'X' - should return to Package View page
2. when on Note View page and after licking on 'Edit' in dropdown menu and clicking 'X' - should return to Note View page
[UIEH-991](https://issues.folio.org/browse/UIEH-991)
=> UIEH-991: Routing issues when clicking Edit on Notes List Accordion

CHANGELOG.md, src/components/resource/resource-show.js, test/bigtest/interactors/resource-show.js, test/bigtest/interactors/resource-usage-consolidation.js, test/bigtest/tests/resource-show-test.js
Add `UsageConsolidationAccordion` on Title+Package (Resource) page
[Issue](https://issues.folio.org/browse/UIEH-949)
=> UIEH-949: Resource View Page: Usage & Analysis accordion

translations/ui-eholdings/en.json
- Fix spelling error in Usage Consolidation month field label
[UIEH-998](https://issues.folio.org/browse/UIEH-998)
=> UIEH-998: Settings > eholdings > Usage Consolidation setting is misspelled 

CHANGELOG.md, src/features/usage-consolidation-accordion/usage-consolidation-accordion.css, src/features/usage-consolidation-accordion/usage-consolidation-accordion.js, test/bigtest/index.js, test/bigtest/interactors/package-usage-consolidation.js, test/bigtest/interactors/resource-usage-consolidation.js, test/bigtest/interactors/title-usage-consolidation.js, test/bigtest/interactors/usage-consolidation-info-popover.js, test/bigtest/tests/package-usage-consolidation-test.js, test/bigtest/tests/resource-show-test.js, test/bigtest/tests/title-show-test.js, test/bigtest/tests/usage-consolidation-info-popover.js, translations/ui-eholdings/en.json
-  Add info popover for Usage Consolidation Accordion
[UIEH-993](https://issues.folio.org/browse/UIEH-993)
=> UIEH-993: Add info popover for Usage Consolidation Accordion

CHANGELOG.md, src/components/package/edit-managed/managed-package-edit.js, src/components/resource/_fields/visibility/visibility-field.js, src/components/styles.css
-  Edit Package/Resource record: Field labels text size is too small
[UIEH-1003](https://issues.folio.org/browse/UIEH-1003)
=> UIEH-1003: Edit Package/Resource record: Field labels text size is too small

CHANGELOG.md, src/components/settings/settings.js, src/routes/settings-knowledge-base.js
-  Add support for Settings (eHoldings): Can create, edit, and view knowledge base credentials.
[UIEH-992](https://issues.folio.org/browse/UIEH-992)
=> UIEH-992: Add support for Settings (eHoldings): Can create, edit, and view knowledge base credentials.

CHANGELOG.md, translations/ui-eholdings/en.json
- Add label for contributor type narrator.
[UIEH-977](https://issues.folio.org/browse/UIEH-977)
=> UIEH-977: Add label for contributor type narrator.

CHANGELOG.md, package.json, src/routes/settings-usage-consolidation-route.js
- Using actual form data instead of hardcoded 'USD' currency
- Added backend permission `kb-ebsco.currencies.collection.get` to get a list of currencies
=> UIEH-1009 Fix Usage Consolidation currency setting not updating

CHANGELOG.md, src/components/settings/settings-usage-consolidation/settings-usage-consolidation.js, src/redux/reducers/usageConsolidation.js, test/bigtest/tests/unit/reducers/usage-consolidation-test.js, translations/ui-eholdings/en.json
Add toast notification for Settings Usage Consolidation page when usage consolidation ID would be updated. Also updated `usage-consolidation` reducer for it and tests.
=> UIEH-1010: Display toast notification for Settings Usage Consolidation

CHANGELOG.md, src/components/resource/resource-show.js
Previous requirements were that when package isn't selected, coverage accordion was collapsed, now it is always expanded.
Issue: [UIEH-1008](https://issues.folio.org/browse/UIEH-1008)
=> UIEH-1008: Make Coverage Accordion in Resource Page be always expanded

CHANGELOG.md, package.json, src/components/settings/settings.js, translations/ui-eholdings/en.json
Add permissions for settings - assign/unassign user from knowledge base
Issue: [UIEH-1018](https://issues.folio.org/browse/UIEH-1018)
=> UIEH-1018: Add assign/unassign user from KB permissions

CHANGELOG.md, src/components/title/show/title-show.js, test/bigtest/interactors/title-show.js, test/bigtest/tests/custom-title-edit-test.js, test/bigtest/tests/title-create-test.js, test/bigtest/tests/title-show-test.js
Add Notes accordion to Title Show page so that users can store information on Titles records even after they are removed from holdings
[UIEH-1033](https://issues.folio.org/browse/UIEH-1033)
=> UIEH-1033: Title Record | Add notes helper app 

src/features/usage-consolidation-accordion/no-cost-per-use-available.js, src/features/usage-consolidation-accordion/summary-table/summary-table.js, src/features/usage-consolidation-accordion/usage-consolidation-content-package.js, src/features/usage-consolidation-accordion/usage-consolidation-content-resource.js, src/features/usage-consolidation-accordion/usage-consolidation-content-title.js, test/bigtest/tests/title-usage-consolidation-test.js
Fix of this [PR](https://github.com/folio-org/ui-eholdings/pull/1272)
Now if no costPerUse data available it should show full text request usage table if usage data present
Issue: [UIEH-1041](https://issues.folio.org/browse/UIEH-57)
=> UIEH-1041: Fix error message for costperuse in record

CHANGELOG.md, package.json, translations/ui-eholdings/en.json
Issue: [UIEH-1104](https://issues.folio.org/browse/UIEH-1104)
=> UIEH-1104: Update permission for eholdings module

CHANGELOG.md, src/features/usage-consolidation-accordion/summary-table/summary-table.js, translations/ui-eholdings/en.json
Add label for Holdings Summary table in Title Record Page
Issue: [UIEH-1109](https://issues.folio.org/browse/UIEH-1109)
=> UIEH-1109: display Holdings Summary heading for title record

CHANGELOG.md, src/components/agreements-list/agreements-list.js, src/components/package/show/components/coverage-settings/coverage-settings.js, src/components/resource/_fields/validate-date-range.js, src/components/settings/settings-access-status-types/settings-access-status-types.js, src/components/utilities.js
* eholdings App: Consume {{FormattedDate}} and {{FormattedTime}} via stripes-component. (UIEH-970)
[UIEH-970](https://issues.folio.org/browse/UIEH-970)
=> UIEH-970: eholdings App: Consume {{FormattedDate}} and {{FormattedTime}} via stripes-component

src/components/eholdings-app-context/eholdings-app-context.css, src/components/eholdings-app-context/eholdings-app-context.js
[UIEH-1108](https://issues.folio.org/browse/UIEH-1108)
- fix issue with incorrect eholding link (if user is not on the home page)
- fix issue with closing accordion
https://user-images.githubusercontent.com/60929399/113398281-02291380-93a7-11eb-8802-5983f4b5f94b.mov
=> UIEH-1108: App context menu dropdown fixes

CHANGELOG.md, src/redux/epics/patch-kb-credentials.js, src/redux/reducers/kb-credentials.js
Fix unable to change Knowledge base name by removing reference to empty response
[UIEH-1122](https://issues.folio.org/browse/UIEH-1122)
=> UIEH-1122 Settings > eholdings > KB configuration > Unable to change Knowledge base name

CHANGELOG.md, src/components/settings/settings-usage-consolidation/settings-usage-consolidation.js
Backend error message was changed. It needs to be updated on UI side too.
Issue:  [UIEH-1123](https://issues.folio.org/browse/UIEH-1123)
=> UIEH-1123: Fix error message for Usage consolidation usage id

CHANGELOG.md, src/components/custom-url-fields/custom-url-fields.js, src/components/title/_fields/description/description-field.js, src/components/title/_fields/description/description-field.test.js, src/components/title/_fields/edition/edition-field.js, src/components/title/_fields/edition/edition-field.test.js, src/components/title/_fields/name/title-name-field.js, src/components/title/_fields/name/title-name-field.test.js, src/components/title/_fields/package-select/package-select-field.js, src/components/title/_fields/package-select/package-select-field.test.js
- Refactoring
- Add tests for DescriptionField, EditionField, TitleNameField, PackageSelectField
- Tests for `CustomUrlFields` was already done
- Add validation test for `PackageSelectField` in scope of testing of `TitleCreate` component
=> UIEH-1051: Add tests for DescriptionField, EditionField, TitleNameField, PackageSelectField components

CHANGELOG.md, src/features/usage-consolidation-accordion/full-text-request-usage-table/full-text-request-usage-table.js, src/features/usage-consolidation-accordion/summary-table/summary-table.js, src/features/usage-consolidation-accordion/titles-table/titles-table.js, src/features/usage-consolidation-accordion/utilities.js
An exception was thrown in cases when no titles were loaded because querySelector wasn't able to find a single row element.
Now focusing on the component container.
[UIEH-1136](https://issues.folio.org/browse/UIEH-1136)
https://github.com/folio-org/stripes-components/pull/1579
=> UIEH-1136: Usage Consolidation: Unable to handle gracefully handle when user attempts to view titles over 200,000

CHANGELOG.md, package.json
Issue: [UIEH-1135](https://issues.folio.org/browse/UIEH-1135)
Avoid .all permissions. There is a possibility that something will fall off after merge.
=> UIEH-1135: Avoid .all permissions

CHANGELOG.md, src/components/resource/components/edit/resource-settings/edit-resource-settings.js, src/components/resource/components/edit/resource-settings/edit-resource-settings.test.js, src/components/resource/components/resource-settings/resource-settings.js, src/components/resource/components/resource-settings/resource-settings.test.js
Display Managed url of a Resource only when a package is managed
[UIEH-1140](https://issues.folio.org/browse/UIEH-1140)
=> UIEH-1140: View/Edit Managed title - Custom Package Record: Custom Package URL field does not display

CHANGELOG.md, package.json
Add missing `module.eholdings.enabled` subpermission to `ui-eholdings.costperuse.view` to show eHoldings module
[UIEH-1142](https://issues.folio.org/browse/UIEH-1142)
=> UIEH-1142: The Eholdings app is NOT displayed in the app bar when the "eHoldings: Can view Usage..." permission is applied

CHANGELOG.md, src/components/agreements-list/agreements-list.js, src/components/agreements-list/agreements-list.test.js
Add tests for AgreementsList
Issue: [UIEH-1055](https://issues.folio.org/browse/UIEH-1055)
If you need to test function with object which it's called, you can use construction `expect.objectContaining()` and set inside object properties. But it doesn't work if parameter is node
=> UIEH-1055: Add tests for AgreementsList

src/components/resource/edit-managed-title/resource-edit-managed-title.js
Fix missing Custom URL value in field when visiting Resource edit page of managed title
[UIEH-1140](https://issues.folio.org/browse/UIEH-1140)
=> UIEH-1140: Fix missing custom url value in resource edit

CHANGELOG.md, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit-managed/managed-package-edit.js, src/components/resource/edit-custom-title/resource-edit-custom-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.js
Saving the update of coverage settings temporarily shows the old date.
This happened because `getInitialValues` function was called after `Save & Close` button was clicked. This function sets form's initial values from existing package `model` object. And because `model` still had old coverage dates - those dates would be set as values to datepicker.
`getInitialValues` function was being called multiple times because of incorrectly set dependencies in `useEffect` hooks - mainly passing functions to dependencies array. When a reference to a function changed that triggered `useEffect`.
[UIEH-1146](https://issues.folio.org/browse/UIEH-1146)
=> UIEH-1146: Saving the update of coverage settings temporarily shows the old date

CHANGELOG.md, src/components/prev-next-buttons/index.js, src/components/prev-next-buttons/prev-next-buttons.css, src/components/prev-next-buttons/prev-next-buttons.js, src/components/prev-next-buttons/prev-next-buttons.test.js, src/components/query-search-list/query-search-list.css, src/components/query-search-list/query-search-list.js, src/components/query-search-list/query-search-list.test.js, src/components/scroll-view/scroll-view.js, src/redux/reducers/packageTitles.js, src/redux/reducers/tests/packageTitles.test.js, translations/ui-eholdings/en.json
- Create `<PrevNextComponent />`
- Add tests
- Update reducer for `packageTitles`
Issue: [UIEH-1163](https://issues.folio.org/browse/UIEH-1163)
After all replacement `<ScrollView />` component should be updated
=> UIEH-1163: Replace loadMoreButton to PrevNextButtons

src/components/prev-next-buttons/prev-next-buttons.js, src/components/prev-next-buttons/prev-next-buttons.test.js, src/components/query-search-list/query-search-list.js, src/redux/reducers/packageTitles.js, src/redux/reducers/tests/packageTitles.test.js
Fix bug described in the [comment](https://issues.folio.org/browse/UIEH-1163?focusedCommentId=109227&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-109227)
Because fetch calls in different places the main propose to keep page value in global state.
=> UIEH-1163: Fix items count per page for PrevNextButtons component

CHANGELOG.md, src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/components/resource/edit-managed-title/resource-edit-managed-title.test.js
Don't copy custom url to initial values when a resource is a managed title in a managed package
[UIEH-1168](https://issues.folio.org/browse/UIEH-1168)
=> UIEH-1168: Cannot edit a package-title (aka resource) record

CHANGELOG.md, src/components/details-view/details-view.js
Changed all detail records headline component size from XXL to XL in order to eliminate excess whitespace.
Issue: [UIEH-1204](https://issues.folio.org/browse/UIEH-1204)
=> UIEH-1204: eholdings: Change all detail records headline component size to XL

CHANGELOG.md, src/components/title/edit/title-edit.js
Fix apparition of 'Are you sure you want to leave' pop-up after clicked Save & Close button while editing Custom Title.
[UIEH-1203](https://issues.folio.org/browse/UIEH-1203)
=> UIEH-1203: Edit Custom Title > Click Save & Close button displays a Are you sure you want to leave pop-up

CHANGELOG.md, src/components/package/edit-custom/custom-package-edit.js, src/components/package/edit/components/edit-package-information/edit-package-information.js, src/components/package/edit/components/edit-package-settings/edit-package-settings.js
- Remove `AccessStatusType` component to `PackageSettings` accordion
Issue: [UIEH-1202](https://issues.folio.org/browse/UIEH-1202)
Tests will be done in a scope of [UIEH-1092](https://issues.folio.org/browse/UIEH-1092)
=> UIEH-1202: Move access status type field to package settings accordion in edit custom package page

CHANGELOG.md, package.json
Replace `.all` permissions
[UIEH-1212](https://issues.folio.org/browse/UIEH-1212)
=> UIEH-1212: Refactor '.all' permissions

CHANGELOG.md, src/constants/costPerUse/costPerUseReduxStateShape.js, src/features/usage-consolidation-accordion/titles-table/titles-table.js, src/features/usage-consolidation-accordion/titles-table/titles-table.test.js, test/jest/__mock__/stripesComponents.mock.js
- Add tests
- Fix `CostPerUseReduxStateShape`
Issue: [UIEH-1181](https://issues.folio.org/browse/UIEH-1081)
Should update `CostPerUseShape`. It has different data structure as in `<TitlesTable>`.
=> UIEH-1181: Add tests for TitlesTable component

CHANGELOG.md, package.json
- Add missing permission
Issue: [UIEH-1222](https://issues.folio.org/browse/UIEH-1222)
Checking `mod-kb-ebsco-java` descriptor for correspondence permissions. Permissions which should be discussed:
["kb-ebsco.configuration.get"](https://github.com/folio-org/mod-kb-ebsco-java/blob/29280795878c3c38da6077c9e9ff83675aae5192/descriptors/ModuleDescriptor-template.json#L429) - ui does not use `eholdings/configuration` 
["kb-ebsco.configuration.put"](https://github.com/folio-org/mod-kb-ebsco-java/blob/29280795878c3c38da6077c9e9ff83675aae5192/descriptors/ModuleDescriptor-template.json#L434) - ui does not use `eholdings/configuration` 
["kb-ebsco.cache.delete"](https://github.com/folio-org/mod-kb-ebsco-java/blob/29280795878c3c38da6077c9e9ff83675aae5192/descriptors/ModuleDescriptor-template.json#L444 …
=> UIEH-1222: Add missed permissions

CHANGELOG.md, src/hooks/useImpagination.js
Fix 3 GET requests instead of 1 are made when searching Providers/Packages/Titles.
The reason 3 GET requests were made is `useImpagination` custom hook where two `useEffect`s were called not only when values in dependencies array changed but also on mount, which was not needed.
The solution refers to [React docs](https://reactjs.org/docs/hooks-faq.html#can-i-run-an-effect-only-on-updates) where it's suggested to add a mutable ref to check if this is the first mount or not.
[MODKBEKBJ-619](https://issues.folio.org/browse/MODKBEKBJ-619)
=> MODKBEKBJ-619: Fix 3 GET requests instead of 1 are made when searching Providers/Packages/Titles

CHANGELOG.md, src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/resource/_fields/resource-coverage-fields/resource-coverage-fields.js
Fix datepicker date format for Custom coverage dates to match current user locale when edit resource.
The date format was forced to be `MM/DD/YYYY` by passing `DATE_FORMAT` constant with this value to `<Datepicker>` component. Removing this prop allows to format date based on current locale.
[UIEH-1227](https://issues.folio.org/browse/UIEH-1227)
=> UIEH-1227: Different date format in eHoldings resource coverage dates

CHANGELOG.md, src/components/list/list.js
This looks like a typo since proptypes were specified twice, and the
second (invalid) settings look like values, not value-types.
Refs [UIEH-1242](https://issues.folio.org/browse/UIEH-1242)
=> UIEH-1242 correctly specify list's proptypes

test/jest/__mock__/stripesComponents.mock.js, test/jest/__mock__/stripesConfig.mock.js, test/jest/babel.config.js
Mitigate a bunch of console noise during tests:
* in stripesComponents, mock `Icon` because it leverages webpack's
`context` function, which node doesn't know about, leading to a warning
during tests.
* in stripesConfig, provide `metadata`, which was added to
stripes-config long, long ago, but after this mock was originally
written.
* in babel.config.js, configure plugin-proposal-private-property-in-object
consistently with others to avoid VERY NOISY console warnings.
=> test config cleanup

CHANGELOG.md, src/components/search-form/search-form.js, src/components/search-form/search-form.test.js
Fix eHoldings app throws an error when 0 tags comes in the response.
This issue occurred due to the response `{totalRecords: 0}` when there's no tags.
Previously the `map` was applied to the array of the kind `[{totalRecords: 0}]` when there's no tags which led to `tag.label` to be `undefined`.
We couldn't just add a check for an undefined inside `map` because then multiselection filter would just display an empty option.
The solution was to filter out tags that don't have label prior to mapping through an array of tags. In this case the `map` applies to an empty array when there's no tags and the multiselection filter displays a user-friendly empty message.
[UIEH-1266](https://issues.folio.org/browse/UIEH-1266)
=> UIEH-1266: eHoldings app throws an error when 0 tags comes in the response

CHANGELOG.md, package.json, src/index.js
Remove react-hot-loader
[UIEH-1265](https://issues.folio.org/browse/UIEH-1265)
=> UIEH-1265: Replace or remove react-hot-loader

CHANGELOG.md, src/components/utilities.js
added bubbles property into submit event
[Bug: Using dispatchEvent 'submit' CustomEvent failure to trigger form onSubmit #20151](https://github.com/facebook/react/issues/20151)
=> UIEH-1269 Save shortcut key does not work

CHANGELOG.md, src/components/settings/settings-access-status-types/settings-access-status-types.js, src/components/settings/settings-access-status-types/settings-access-status-types.test.js
Issue: SettingsAccessStatusTypes - Use react-final-form
https://issues.folio.org/browse/UIEH-1282
=> UIEH-1282 : SettingsAccessStatusTypes - Use react-final-form

CHANGELOG.md, src/features/usage-consolidation-accordion/full-text-request-usage-table/full-text-request-usage-table.js, src/features/usage-consolidation-accordion/full-text-request-usage-table/full-text-request-usage-table.test.js
Fix not all months are displayed in Usage Consolidation.
Issue was caused by slicing months array starting from start month (for example March), but then we need to append months from January to start month at the end
[UIEH-1304](https://issues.folio.org/browse/UIEH-1304)
=> UIEH-1304 Fix Usage Consolidation - does not return 12 months when starting period is not January

package.json
Settings (eholdings): View Usage Consolidation API credentials is extended with new permissions to fetch uc-credentials-client-id and uc-credentials-client-secret.
The previous PR: https://github.com/folio-org/ui-eholdings/pull/1566
The story: [UIEH-1169](https://issues.folio.org/browse/UIEH-1169)
=> UIEH-1169: new permissions

CHANGELOG.md, src/redux/actions/kb-credentials-users/clear-kb-credentials-user.js, src/redux/actions/kb-credentials-users/index.js, src/redux/reducers/kb-credentials-users.js, src/redux/reducers/tests/kbCredentialsUsers.test.js, src/routes/settings-assigned-users-route/index.js, src/routes/settings-assigned-users-route/settings-assigned-users-route.js
Fix exception when navigating from and to Assign Users page after failed attempt to assign a user
Issue was caused by redux state that was not being cleared and showed and error, when component's state that stored user data was cleared and attempting to access it threw `reading prop of undefined` error
https://user-images.githubusercontent.com/19309423/178729034-40b0d205-eae8-41cb-b800-6ce5dd16e637.mp4
[UIEH-1315](https://issues.folio.org/browse/UIEH-1315)
=> UIEH-1315 Clear assigned users redux when leaving Assigned Users page.

CHANGELOG.md, src/components/package/show/package-show.js, src/routes/package-show-route/package-show-route.js, src/routes/package-show-route/package-show-route.test.js
Stop infinity loading of package titles when a user fires adding packages to holdings and immediately starts:
- editing the record;
- removing packages from eholdings.
[UIEH-1349](https://issues.folio.org/browse/UIEH-1349)
https://user-images.githubusercontent.com/77053927/219599279-1d2b2c05-29be-4a2e-ae38-e37c130cb601.mp4
=> UIEH-1349: Stop infinity loading of package titles when a user edits the package record while they are being added/removed to holdings

CHANGELOG.md, src/components/settings/settings-usage-consolidation/settings-usage-consolidation.js, src/redux/reducers/tests/ucCredentials.test.js, src/redux/reducers/ucCredentials.js, src/redux/reducers/usageConsolidation.js
Removed `isFailed` flag when GET uc crendetials fails to use it only when UPDATE fails
https://user-images.githubusercontent.com/19309423/235140006-cbc14d4f-bbec-4120-b576-21452d82b902.mp4
[UIEH-1362](https://issues.folio.org/browse/UIEH-1362)
=> UIEH-1362 Fix  errors appearing when user switch to User Consolidation settings

src/routes/search-route/search-route.js
Don't use Packages collection states until there is no query.
<details><summary>Screencast of infinite loading</summary>
<p>
https://user-images.githubusercontent.com/77053927/235742102-d9be30b4-96f5-4fbf-b6c0-2d23ccb42da0.mp4
</p>
</details> 
[UIEH-1350](https://issues.folio.org/browse/UIEH-1350)
https://user-images.githubusercontent.com/77053927/235742538-0dc6eaa0-c83b-430f-800b-c2187a59d9a9.mp4
=> UIEH-1350: Don't use Packages collection states until there is no query.

CHANGELOG.md, src/components/settings/settings-usage-consolidation/settings-usage-consolidation.js
`moment.months()` returns localized month names. Changed code to use constant months as values instead
[UIEH-1371](https://issues.folio.org/browse/UIEH-1371)
=> UIEH-1371 Fix passed month values to Usage Consolidation settings

package.json
build: erm 6.0
Added okapi interface dependency on new erm interface 6.0
refs ERM-2641
=> ERM-2641: Upgrade to Grails 5 (including Hibernate 5.6.x) for Poppy

CHANGELOG.md, test/jest/babel.config.js
Align the babel config with that in `@folio/stripes-webpack` so that all plugins referenced in the config are actually present in the build.
Refs [UIEH-1380](https://issues.folio.org/browse/UIEH-1380), [STRWEB-87](https://issues.folio.org/browse/STRWEB-87)
=> UIEH-1380 align test babel config with stripes-webpack

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md
Leverage all available CPUs in CI. This is just a config change in the GA workflows; there are no code changes.
Refs [STRIPES-854](https://issues.folio.org/browse/STRIPES-854)
=> STRIPES-854 leverage all CPUs in CI

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
In CI, bump NodeJS from v16 to v18.
Refs [UIEH-1386](https://issues.folio.org/browse/UIEH-1386)
=> UIEH-1386 use NodeJS v18 in CI

CHANGELOG.md, package.json
Remove eslint deps that are already listed in eslint-config-stripes
[UIEH-1389](https://issues.folio.org/browse/UIEH-1389)
=> UIEH-1389 Remove eslint deps that are already listed in eslint-config-stripes

CHANGELOG.md, src/components/resource/_fields/custom-embargo/custom-embargo-fields.js, src/components/resource/_fields/custom-embargo/custom-embargo.test.js, src/routes/resource-edit-route/resource-edit-route.js, src/routes/resource-edit-route/resource-edit-route.test.js
Fix deleting and then saving custom embargo.
[UIEH-1394](https://issues.folio.org/browse/UIEH-1394)
https://github.com/folio-org/ui-eholdings/assets/77053927/a15ceb5b-6e8b-40cc-bdc4-6741971a5788
=> UIEH-1394: Fix deleting and then saving custom embargo.

CHANGELOG.md, src/components/title/_fields/package-select/package-select-field.css, src/components/title/_fields/package-select/package-select-field.js
Make package select field container have relative position to fix packages dropdown list not displayed with the label
[UIEH-1382](https://issues.folio.org/browse/UIEH-1382)
=> UIEH-1382 Make package select field container have relative position to fix packages dropdown list not displayed with the label

CHANGELOG.md, src/components/package/_fields/custom-coverage/package-coverage-fields.js, src/components/resource/_fields/validate-date-range.js, src/routes/package-create-route/package-create-route.js, src/routes/package-create-route/package-create-route.test.js, src/routes/resource-edit-route/resource-edit-route.test.js
Fix deleting last date range when creating a new package or editing title.
[UIEH-1383](https://issues.folio.org/browse/UIEH-1383)
https://github.com/folio-org/ui-eholdings/assets/77053927/31d39149-5100-4f07-8ada-4a9bf66a595a
=> UIEH-1383: Fix deleting last date range when creating a new package or editing title.

src/components/resource/edit-managed-title/resource-edit-managed-title.js, src/routes/package-edit-route/package-edit-route.js, src/routes/package-edit-route/package-edit-route.test.js, src/routes/resource-edit-route/resource-edit-route.js, src/routes/resource-edit-route/resource-edit-route.test.js
Don't display the deleted date range.
Removed `handleToggleResourceHoldings` because is not possible to have `Add to holdings` button on `resource-edit-managed-title.js` page and deleted the corresponding test for it.
[UIEH-1383](https://issues.folio.org/browse/UIEH-1383)
[packages issue](https://github.com/folio-org/ui-eholdings/assets/77053927/f78386f4-acd7-4204-bb03-231c3fd2d930)
[packages fix](https://github.com/folio-org/ui-eholdings/assets/77053927/8703834f-e3c6-451d-a8b6-54e5f7b81c1a)
[resource issue](https://github.com/folio-org/ui-eholdings/assets/77053927/9fd095d6-3351-4e60-a8c9-3d898acd1d66)
[resource fix](https://github.com/folio-org/ui-eholdings/assets/77053927/d8a3a94a-5436-4e80-9da5-8d269d874f17)
=> UIEH-1383: Don't display the deleted date range.

CHANGELOG.md, src/features/agreements-accordion/agreements-accordion.js, src/features/agreements-accordion/agreements-accordion.test.js, test/jest/__mock__/stripesCore.mock.js, translations/ui-eholdings/en.json
Agreements accordion - Add a tooltip for the `New` and `Add` buttons.
[UIEH-1424](https://folio-org.atlassian.net/browse/UIEH-1424)
https://github.com/folio-org/ui-eholdings/assets/77053927/e28f2ba6-cd44-4d92-badf-6fb4d5c2296c
=> UIEH-1424: Agreements accordion - Add a tooltip for the `New` and `Add` buttons.

CHANGELOG.md, src/components/resource/components/resource-settings/resource-settings.js, src/components/resource/components/resource-settings/resource-settings.test.js, src/components/tags/tags.test.js, src/components/title/_fields/package-select/package-select-field.test.js, translations/ui-eholdings/en.json
Show ProxiedURL on Resource show page
[UIEH-1419](https://folio-org.atlassian.net/browse/UIEH-1419)
=> UIEH-1419 Show ProxiedURL on Resource show page

src/components/package/show/components/PackageTitleList/PackageTitleList.css, src/components/package/show/components/PackageTitleList/PackageTitleList.js, src/routes/package-show-route/package-show-route.js, src/routes/package-show-route/package-show-route.test.js
1. Display previous list items while loading new ones (follow-up PR).
2. Preserve the height of the package title container while loading the new list items.
[UIEH-1442](https://folio-org.atlassian.net/browse/UIEH-1442)
1. Remove clear-related functionality. This is legacy code that is no longer relevant for the current implementation.
2. Set a specific height for the package title container.
https://github.com/user-attachments/assets/8ecdf9f5-90ae-47e0-9df0-1516a7ec0048
=> UIEH-1442: Do not run `clearPackageTitles` when loading package titles (follow-up PR).

src/components/package/show/components/PackageTitleList/PackageTitleList.js
add more space to custom coverage column so that when there are multiple custom coverage dates they each fit on a single line
[UIEH-1449](https://folio-org.atlassian.net/browse/UIEH-1449)
=> UIEH-1449 add more space to custom coverage column (follow-up)

CHANGELOG.md, src/components/package/show/components/PackageTitleList/PackageTitleList.js, src/components/package/show/components/PackageTitleList/PackageTitleList.test.js, src/components/package/show/package-show.js
Before switching to MCL Package Titles list showed a loading indicator when a Package was added/removed from holdings and package-titles records were being updated.
In this PR we're adding that functionality back to current implementation.
https://github.com/user-attachments/assets/0a1b41a9-3c7a-4fc4-b5ba-799ea68623b4
[UIEH-1471](https://folio-org.atlassian.net/browse/UIEH-1471)
=> UIEH-1471 Show a loading indicator under Package Titles list when package titles are updating.

CHANGELOG.md, src/components/facet-option-formatter/FacetOptionFormatter.js, src/components/facet-option-formatter/FacetOptionFormatter.test.js
Fix an issue with Packages filter displaying "undefined (undefined)" selected after clearing the filter.
It looks like after refactoring of `<Selection>` component empty option is not just a `null` object, but can be an object with an empty `value` property, so we should also check for this case in our custom `<FacetOptionFormatter>` component.
https://github.com/user-attachments/assets/8ca94016-1908-4728-b7e4-fdfc7daaabb8
[UIEH-1470](https://folio-org.atlassian.net/browse/UIEH-1470)
=> UIEH-1470 Fix "Undefined" displays in input field of "Packages" facet on "Titles" search pane when facet selection is canceled.

CHANGELOG.md, package.json, src/components/package/show/package-show.js, src/components/resource/resource-show.js
Agreements will become a separate application as part of Eureka platform and we need to make erm interface an optional dependency.
In scope of this ticket we need to hide functionality that’s related to Agreements when that interface is missing:
- Package Show page - Agreements accordion
- Package+Title Show page - Agreements accordion
[UIEH-1476](https://folio-org.atlassian.net/browse/UIEH-1476)
=> UIEH-1476 Make "erm" an optional interface in eHoldings.
